### ISSUE TITLE
Get an infinite loop on java.lang.NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#106]
```
Hello,

I started creating an example program and wanted to show  the layout, really 
simple. It just adds some empty panels to a window and then does a 
showWindow(). 

The system response is an infinite loop printing 
"java.lang.NullPointerException". 

Somewhere at the start of the exception it prints something looking like useful 
information, but then scrolls by too fast and in such an amount that the 
information leaves the terminals buffer.

I suspect the error in my example program may be a lack of size information. 
Even if that is so, I should get just an exception. Not an infinite loop of 
exceptions. 
```

Original issue reported on code.google.com by `abonnem...@gmail.com` on 20 May 2014 at 5:37

Attachments:
* [BugWindow.java](https://storage.googleapis.com/google-code-attachments/lanterna/issue-106/comment-0/BugWindow.java)
* [Main.java](https://storage.googleapis.com/google-code-attachments/lanterna/issue-106/comment-0/Main.java)

**Comment by mabe02** [comment]
Hmm, not sure about this one. It's "fixed" in the sense that the GUI loop isn't catching anything anymore and any exceptions are passed back to the caller.
