### ISSUE TITLE
patches for 2.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#125]
```
I don't now how create pull request in google code, so i post them here.

Patches summary:
- Implement ComboBox
- In TextArea add methods for help implement autoscroll
- In CheckBox implement method setSelected
```

Original issue reported on code.google.com by `masL...@gmail.com` on 21 Jan 2015 at 9:48

Attachments:
* [patch_CheckBox_setSelected.diff](https://storage.googleapis.com/google-code-attachments/lanterna/issue-125/comment-0/patch_CheckBox_setSelected.diff)
* [patch_ComboBox.diff](https://storage.googleapis.com/google-code-attachments/lanterna/issue-125/comment-0/patch_ComboBox.diff)
* [patch_TextArea_autoscroll.diff](https://storage.googleapis.com/google-code-attachments/lanterna/issue-125/comment-0/patch_TextArea_autoscroll.diff)

**Comment by mabe02** [comment]
Closing
