### ISSUE TITLE
Request: string support in 3.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#130]
```
Please allow for putting strings in 3.0
```

Original issue reported on code.google.com by `KrystalA...@gmail.com` on 15 Apr 2015 at 8:34

**Comment by avl42** [comment]
Just guessing, and not sure if KrystalA...@gmail.com will actually see it here, but my guess would be about Screen.setCharacter(...). In that case, the answer would be: call newTextGraphics() to create a TextGraphics-object for the Screen(or TextImage, or Terminal), which does have a couple of  putString(...) overloads...

**Comment by mabe02** [comment]
Yep, that should do it.
