### ISSUE TITLE
Throw ArrayIndexOutOfBoundsException with 3.0.0-alpha6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#134]
```
The issues is InteractableLookupMap.getSize() assume it has 1 more rows. So
return new TerminalSize(lookupMap[0].length, lookupMap.length); will throw 
ArrayIndexOutOfBoundsException when it has 0 rows.
```

Original issue reported on code.google.com by `yuxuanch...@gmail.com` on 5 Jun 2015 at 9:07

**Comment by avl42** [comment]
I don't know if something else was fixed to stop a zero-sized InteractableLookupMap from being created, but I think that the class itself should be immune to that problem. Thus the pull-request.

**Comment by mabe02** [comment]
Yep, that's merged now
