### ISSUE TITLE
Bug in Panel / LinearLayout

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#144]
I idly stumbled over that one:  When you have components in a vertical Panel, and one of them changes its contents to become wider (e.g. wider than all other sibling components), then the Panel follows the size-wish and adapts to the new width just fine, but it doesn't actually grant the component any of the new extra space.

I played with the GUIOverTelnet test program, and wanted to clean up the Generics-related warning in it about the AbstractInteractableComponent. Then I changed it to a Button merely with overridden handleKeyStroke (calling setLabel(...) instead of "text="), which now no longer had a constant preferredSize, but one that depended on its label. This made the bug visible when I pressed a control-key. 

I then tried to find an easy fix, but couldn't.  Either we would need to call Panel's invalidateStructure() whenever the Button changes it's width, or the Panel would need to do size-recalculations even without the invalidStructure-flag set (in the loop to draw its components)...  Maybe you've got a better idea?  Anyway, merely setting invalidStructure in response to a change overall preferredSize would not cut that one: if the growing component is still smaller than the others it still wouldn't even get the available horizontal space established by the other components.

**Comment by mabe02** [comment]
Yeah, I've seen similar problems with components changing size after being laid out. We need to be a bit smarter with this.

**Comment by avl42** [comment]
The change getting rid of the "invalidStructure" flag fixed this one.  I'd say this issue can be closed.
