### ISSUE TITLE
Proper way to start gui in Lanterna 3

### ISSUE THREAD

**Issue by dant3** [mabe02/lanterna#149]
With Lanterna 3.0-alpha6 I had [this nice snippet of how would one write "Hello World" with Lanterna 3](https://gist.github.com/dant3/216c9f44b15a745ac048). With Lanterna 3.0-beta1 this does not works anymore, in particular this place:

```scala
gui.getGUIThread.start()
```

I tried to fix this by changing to

```scala
gui.getGUIThread.getThread.start()
```

, but this does not works as thread is already running. Still, I see just black screen and not sure what to do next to make it working. Please advice.

**Comment by mabe02** [comment]
Yes, the GUI threading model was reworked to support modal dialogs and being able to wait for GUI events while being on the GUI thread.

**Comment by mabe02** [comment]
You have two options when you create a MultiWindowTextGUI; either have Lanterna create a dedicated Thread that will deal with all GUI events or you launch the event loop from your current thread. By default, it will use the same thread as created the MultiWindowTextGUI. In this case, you don't need to kick off the GUI thread explicitly, just call WindowBasedTextGUI.addWindowAndWait(..) or WindowBasedTextGUI.addWindow(..) and then Window.waitUntilClosed()

If you want to have a dedicated separate thread, you'll need to start it like you do above. See the TestBase for an example on how to do this.

**Comment by dant3** [comment]
Thanks. I've updated my gist to work with `beta1`. Perhaps it might be a good thing to port it to java & use as obligatory "Hello World" for newcomers?

**Comment by mabe02** [comment]
Yeah, I think we're lacking a proper HelloWorld GUI sample. Still haven't wrapped my head around how the documentation works here on GitHub but I'm getting there.
