### ISSUE TITLE
Issues with Lanterna Terminal Starting/Stopping

### ISSUE THREAD

**Issue by dant3** [mabe02/lanterna#150]
I have a couple of inconvenience running Lanterna 3 app on OS X:

- then I start the app from Terminal, which is using `DefaultTerminalFactory` I always getting Swing terminal windows for my app. This doesn't feel nice. I expect app to run in terminal if I start it from terminal. I guess it has something to do with JVM flags.
- after running my app using `ANSITerminal` my mouse can't scroll terminal contents anymore. Instead it works as `↑` and `↓` arrow keys, making me close terminal to get rid of this effect. This is very inconvenient - mouse should work as it was before after I leaving the app. At least this is what happens if app exits due to exception. I guess there should be some shutdown hook to make it work as it used to before.

**Comment by avl42** [comment]
not sure, if macos works that way, but on unix the decision is made upon existence of the DISPLAY environment variable. there is also a setting about preferrence of graphical or non-graphical terminal in the defaultterminalfactor, iirc.

You're right, exiting from private mode (the one where scrolling is inhibited) should be done in some exit-hook, even if the app terminates on an exception. Until that, you can try the command 'reset'. I think it also resets the private-mode.

**Comment by dant3** [comment]
Yes, on OS X I can see DISPLAY defined in Terminal as well with value `/private/tmp/com.apple.launchd.EbruLstpGr/org.macosforge.xquartz:0`. From what I see in JDK sources the OS X doesn't checked for DISPLAY value, but instead, checked for awt toolkit property.
About the setting you referring to - will it make `UnixTerminal` preferred and fallback to `SwingTerminal` if `UnixTerminal` fails? What will happen if I'll allow user to start my app from Finder? From source code I see there is just `if (headless || preferUnixTerm) { doUnixTerminal(); } else { doSwingTerminal(); }` so it doesn't looks like there are some fallback handling happening.

`reset` does the trick. I think there is a way to preserve exception-dump in UncaughtExceptionHandler you can simply do what you have to do and finally just pass original exception to the original handler. I'll take a look at sources and see if I can implement it & create an appropriate PR.

**Comment by avl42** [comment]
Sorry, no. The setting is merely to force terminal operation even when DISPLAY is set.
The toolkit-property behind "GraphicsEnvironment.isHeadless()" is probably initialized depending on presence of the "DISPLAY" env-var -- at least on unix-like platforms.

There is currently no option for: "if you have a proper tty then use that, else hope for DISPLAY", although it should not be impossible to add one, if you find out how to safely determine presence of a usable terminal without screwing up things elsewhere :-)

I just recently PR'ed some changes in UnixTerminal that involved ".addShutdownHook(...)", but so far it only restores the stty-stuff.  You could add a call to exitPrivateMode(), but be sure to catch IllegalStateException (or check isInPrivateMode(), first) because that method throws it if it isn't in that mode...

**Comment by mabe02** [comment]
I haven't come up with any bulletproof way of telling if the Java process was started from a terminal emulator or not. The current default behaviour when using DefaultTerminalFactory, as pointed out above, is to use SwingTerminalFrame if Java detects a graphical desktop present. You can easily customize this by bypassing DefaultTerminalFactory.

The TTY can end up in a weird state if the app exited uncleanly, even with a shutdown hook you are not guaranteed it will restore it. It can be a good idea to program very defensively around for example RuntimeExceptions

**Comment by dant3** [comment]
Ok, thanks for this info. I'll try to play around and will submit PR if I'll come with something good enough to be useful for Lanterna in general.

**Comment by dant3** [comment]
So, I've worked around first limitation by using the following code:
```scala
import java.io.IOException

import com.googlecode.lanterna.screen.{TerminalScreen, Screen}
import com.googlecode.lanterna.terminal.{Terminal, DefaultTerminalFactory}

class ScreenFactory {
  private val terminalFactory = new DefaultTerminalFactory()

  def createScreen(): Screen = try {
    new TerminalScreen(createTerminal(useSwing = false))
  } catch {
    case ex:IOException if ex.getMessage.startsWith("Timeout while waiting for terminal size report!") ⇒
      new TerminalScreen(createTerminal(useSwing = true))
  }

  private def createTerminal(useSwing:Boolean):Terminal = {
    terminalFactory.setSuppressSwingTerminalFrame(!useSwing).createTerminal()
  }
}
```
This looks pretty hacky (mainly because of the way I'm catching an exception - a more precise subclass of IOException would be a plus here), but works as expected on my OS X and Linux machines.

WRT second issue I tried to do shutdown hook but it doesn't helps for some reason. I'll dig more.

**Comment by avl42** [comment]
Yours seems to be the best bet from a Lanterna-user's POV.

With some help of Lanterna, the UnixTerminal class might offer a static method that tries to execute "stty -g" (as already done in saveSTTY() ), and if it returns an empty string (or null, or an exception), then there is no proper tty.  Not sure if it is actually safe, but it is certainly less potentially disruptive than waiting for the resize-timeout ;)

**Comment by avl42** [comment]
Wait, a Lanterna user might still create his own subclass of UnixTerminal, and from that try to call saveSTTY() and check the result, so, while a bit complicated, it's also still within reach even without enhancing Lanterna itself...

**Comment by dant3** [comment]
Since I've started to test my app with `SwingTerminal` I also noticed another annoying issue - the process does not finishes then I''m doing `stopScreen()` and then `SwingTerminal` is closed. I've edited my `ScreenFactory` to do this:

```scala
import java.awt.event.{WindowEvent, WindowAdapter}
import java.io.IOException
import javax.swing.JFrame

import com.googlecode.lanterna.screen.{Screen, TerminalScreen}
import com.googlecode.lanterna.terminal.swing.SwingTerminalFrame
import com.googlecode.lanterna.terminal.{DefaultTerminalFactory, Terminal}

class ScreenFactory {
  private val terminalFactory = new DefaultTerminalFactory()

  def createScreen(): Screen = try {
    new TerminalScreen(createTerminal(useSwing = false))
  } catch {
    case ex:IOException if ex.getMessage.startsWith("Timeout while waiting for terminal size report!") ⇒
      new TerminalScreen(createTerminal(useSwing = true))
  }

  private def createTerminal(useSwing:Boolean):Terminal = {
    tuneSwingWindow(terminalFactory.setSuppressSwingTerminalFrame(!useSwing).createTerminal())
  }

  private def tuneSwingWindow(terminal: Terminal) = terminal match {
    case swingFrame: SwingTerminalFrame ⇒
      swingFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)
      swingFrame
    case anythingElse ⇒ anythingElse
  }
}
```

While this works as expected I also see this exception afterwards:
```
java.lang.RuntimeException: Unexpected IOException while waiting for window to close
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:278)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:164)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:252)
	at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:19)
	at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:17)
	at com.github.dant3.catlog.ui.GUI$.run(GUI.scala:19)
	at com.github.dant3.catlog.Main$.main(Main.scala:17)
	at com.github.dant3.catlog.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
Caused by: java.io.EOFException
	at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:96)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:53)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:275)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:164)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:252)
	at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:19)
	at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:17)
	at com.github.dant3.catlog.ui.GUI$.run(GUI.scala:19)
	at com.github.dant3.catlog.Main$.main(Main.scala:17)
	at com.github.dant3.catlog.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

I could edit my code like this:
```scala
  private def tuneSwingWindow(terminal: Terminal) = terminal match {
    case swingFrame: SwingTerminalFrame ⇒
      swingFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)
      swingFrame.addWindowListener(new WindowAdapter {
        override def windowClosing(event:WindowEvent): Unit = {
          // HACK! ScreenFactory shouldn't be aware of GUI internals, screen and windows
          import scala.collection.JavaConversions._

          GUI.gui.getWindows.foreach(_.close())
          GUI.screen.stopScreen()
        }
      })
      swingFrame
    case anythingElse ⇒ anythingElse
  }
```

But this doesn't seems very good either.

**Comment by avl42** [comment]
I vaguely suspect that the problem of not finishing the event-loop might be related to and fixed by another recent commit (that's meanwhile merged into mabe02's master branch). Give it a try, at least, if the SeparateTextGUIThread is involved somewhere...

I'm quite non-excited over the "EXIT_ON_CLOSE" feature. One might have multiple SwingTerminalFrames in a single application, and one probably wouldn't want closing one of them kill all of them.  I think it would be worthwhile to find the actual bug, if the fix mentioned above doesn't already solve it, anyway.

**Comment by avl42** [comment]
tiny correction: SeparateTextGUIThread is not relevant here, thus my fix won't help here.

It seems like when the window is closed, then the next KeyStroke seen is EOF, which is dealt with by throwing EOFException.  This exception, or the Window no longer having a textGUI, are what can exit the loop in MultiWindowTextGUI.waitForWindowToClose() . Apparently, the EOFException is what happened in your case. Whether that is so intended or indicates a bug ... I have no idea yet.

Could it be that your fix to always return a sensible textGUI had an effect here?

**Comment by dant3** [comment]
The tricky moment is I only have this issue with SwingTerminal. If it was event-loop, UnixTerminal should behave same, right?
I agree with you about `EXIT_ON_CLOSE`, but for my particular app I need only one window, and I want to shutdown my app then this window closes. Currently this doesn't happen.
I'll check if TextGUI changes is the culprit here by reverting them locally.

**Comment by avl42** [comment]
Ok, I mixed up swing windows with textGUI windows.  The EOF-case happens when the swing window (JFrame) is disposed. 

The interesting question is: why does the app not immediately exit after closing of swing terminal window, but instead  still continue to run long enough to throw exceptions for EOF elsewhere...

**Comment by mabe02** [comment]
Hmm, ok, so two separate things here it seems:
 * Auto-detect terminal environment (ANSI or Swing)
 * Problems when closing screen

**Comment by mabe02** [comment]
First one turned out to be a lot easier than I thought; it's kind of obvious but I'd never thought of it during all these years. Simply call "System.console() != null" and if that's true then you can probably use UnixTerminal.

**Comment by mabe02** [comment]
For the second point, agreed, when the window/terminal closes, the TextGUI should exit nicely.

**Comment by mabe02** [comment]
I've added a simple catch for EOFException, could you update to latest master and see if this solves the stacktrace?

**Comment by dant3** [comment]
I've tested using 470c4da299 SNAPSHOT - I replaced `EXIT_ON_CLOSE` with `DISPOSE_ON_CLOSE` and removed my window listener, and can't see any problems now - Lanterna finishes it's execution fine now, with no stacktraces around.

**Comment by avl42** [comment]
I'm not overly excited about commit 20984c32f4cda5db62326ab740f1c7177a841922 :-(

I'd have expected that at some point in future(*) we would eventually drop support for Java 6 and then just restore the ProcessBuilder redirection from the comment. 

Also, you removed the StringBuilder and replaced it by String+ operations, which I think was (even 
if a tiny one) a step in the wrong direction.

(*): not saying that we should drop it any time soon, just that eventually it will just happen, just like support for Java1.4 and Java5 already happened to disappear a while ago...

**Comment by dant3** [comment]
I've noticed new problem then app falls with exception - it now does not allow me to do anything. Process just stucks now, I can't use Ctrl+C to just quit it. Before I was at least able to interact with the shell and call `reset` manually, and now I have to close my terminal emulator and start a new one.

**Comment by avl42** [comment]
Capturing Ctrl-C was imho one of the better things among the most recent changes.
A text-GUI app ought to be able to see a Ctrl-C just like any other KeyStroke.

If your app gets stuck, then *that* is the problem, not "no longer being able to Ctrl-C out".

The new question now is:  *where* does it get stuck now?

**Comment by mabe02** [comment]
I've updated UnixTerminal to kill the application by default if ctrl+c is pressed, but yes, you can customize how you want this to work.

**Comment by mabe02** [comment]
Andreas, I've reverted most of 20984c3, the initial reason for changing it was because it wasn't working when I was testing and I did a lot of moving around code when debugging. Turns out the > should be a < and one line moved; then it worked.

**Comment by avl42** [comment]
When I read about the Java6 build problem, I was obviously in such a hurry to provide a fix, that I not only omitted testing after "successful review", but also goofed with the review in the first place. I'm very sorry for that.  Well, thanks for spotting and fixing them now :)

For handling of Ctrl-c, Lanterna can offer two options:  Either kill the app immediately, or treat it as a normal character to be handled by the app.  Lanterna itself has two spots to take influence on it:  it now has the option of setting intr ... for stty, and it has a filter on readInput and pollInput to treat the keystrokes as app-terminators. My own lanterna app uses a slightly different Terminal-implementation that happens to do "stty raw" in the first place, so my app treats Ctrl-C as a normal keystroke.  When I played with Lanterna's test apps, I always thought it would be the Ctrl-C input-filters that killed the app, but obviously it was the stty-setting. The stty-setting is far superior to the input filtering, because it also works if the app is caught in a loop not reading any input. 

Given that the UnixTerminal has now public methods to do the switching on the tty, I'd like to get rid of the input-filter, which imho makes no sense as the tty does it better and even if the app doesn't look for input.
Next step would be using the Unix(Like)Terminal's constructor argument (instead of that new System-property) to control the stty-setting for "intr", and make the according field non-final.

**Comment by dant3** [comment]
I'm agree that capturing Ctrl+C might be very useful for some console apps. I didn't meant that it's a bad practice. That I don't like is that then something goes wrong console goes to the messy state like still capturing Ctrl+C and so on. If my console app finishes for whatever reason (crash or not) after making console go to some weird state it should get me out of this state to that I had before.

**Comment by dant3** [comment]
I think Lanterna just needs a general Terminal state handler ala "commit & revert" stack here.

**Comment by avl42** [comment]
First of all, there are two kinds of "Terminal state", namely those parts controlled with stty, and the other parts that are controlled by writing byte-sequences to the terminal.

Lanterna uses addShutdownHook to reset all the stty-based terminal attributes, which include Control-key handling and echo-mode.  Other terminal-attributes (including privateMode, mouseModes, reduced scrollRanges and color- & text-attributes) are currently not reset in the shutdownhook, but maybe should, too.

If you can describe the misbehaviours in your terminal-window after some lanterna-app crashes or is killed, then this would help determining if the shutdownhook doesn't hold its promises, or if it is among those things that just aren't yet handled(reset) in it.

**Comment by dant3** [comment]
@avl42 I created a short demo to take a look at. It behaves same way as I experience it.

**Comment by avl42** [comment]
OK, I notice that private mode is left active and the cursor is hidden. Once I also got some strange text-colour left, too, but I couldn't reproduce that.
As it seems, the shutdown hook with stty is working well, but it should also reset the other kind of attributes.

On SwingTerminal side I noticed that the window remained open but inactive. It did react to the WM's close features, but the JVM didn't end.   I'll check that some more with the debugger...

**Comment by dant3** [comment]
JVM also doesn't stops for me with UnixTerminal, althrough with my shutdown hook for reseting private mode it at least exits private mode.
Here is what I did:
```scala
import com.googlecode.lanterna.terminal.Terminal

import scala.sys.ShutdownHookThread

class PrivateModeEscapingTerminal(wrappedTerminal:Terminal) extends ProxyTerminal(wrappedTerminal) {
  private var privateModeMaintainer:Option[ShutdownHookThread] = None

  override def enterPrivateMode(): Unit = privateModeMaintainer match {
    case Some(maintainer) ⇒ // private mode already started - do nothing
    case None ⇒
      super.enterPrivateMode()
      privateModeMaintainer = Some(ShutdownHookThread {
        exitPrivateMode()
      })
  }
  override def exitPrivateMode(): Unit = privateModeMaintainer match {
    case Some(maintainer) ⇒
      super.exitPrivateMode()
      maintainer.remove()
      privateModeMaintainer = None
    case None ⇒ ???
  }
}
```

**Comment by avl42** [comment]
I fear this is mostly a user problem, afterall.
If you add a try-finally into your main method:
>        try {
>            gui.addWindowAndWait(new BasicWindow("Issue150") {{
>                setComponent(createUi());
>            }});
>        } finally {
>            screen.stopScreen();
>        }

then it will quite likely solve most of your problems. (I tried with SwingTerminal and with UnixTerminal).

In normal applications you might further want to catch the exception, to avoid dumping the stack-trace to the user, but otoh., sometimes the dump is valuable diagnosis.

What Lanterna could do is: update the demos and tests to do use try-finally to make for good examples...

**Comment by dant3** [comment]
try/finally is actually easily to encapsulate using `Managed Resource` pattern. I actually have try/finally in my app, it's just I'm being lazy and forgot to take in in account inside of testcase. My app code looks like this:
```scala
object GUI {
  lazy val screen = screenFactory.createScreen()

  def run(guiApp: WindowBasedTextGUI ⇒ Unit): Unit = { // notice try/finally encapsulation
    screen.startScreen()
    try {
      guiApp(gui) // invoke function which implements app workflow
    } finally {
      screen.stopScreen()
    }
  }
}

object Main {
  def main(args:Array[String]) = {
    GUI.run { implicit gui ⇒ // actual function impl doing some stuff with gui.
                                          // Easy to achieve same thing with Java 8 lambdas
      gui.addWindowAndWait(createUi())
    }
  }
}
```

**Comment by dant3** [comment]
After all it looks like a user problem. I added `try/finally { System.exit(0) }` and it works fine now.

**Comment by avl42** [comment]
Well, I'm glad for you that it works for you that way, but it doesn't look like a general solution to me.

The shutdown hook is only necessary, because there is a ressource "the terminal" that will outlive the JVM, and should be set to a sane state, even if Ctrl-C is pressed.

For the other Terminals (Swing, Telnet,...) these particular concerns aren't relevant,  but the SwingTerminal has a default behaviour of disposing the terminal in "exitPrivateMode()".

exitPrivateMode() is called from stopScreen() and user's responsibility is making sure that stopScreen() gets called, and that should typically cause the rest to be taken care of.

If you actually called  stopScreen in your finally-block, then I think it would work, too, and I'd be really interested if it didn't.

**Comment by dant3** [comment]
Andreas, you were right. The issues with private mode and stucking was all my fault. This happened for two reasons:
1. I added finally block at later stage, after I already added shutdown hook for calling `exitPrivateMode`
2. It looks like I have some non-daemon threads doing something then gui layer already finished.

For first thing it would be really nice if there was some recommended shortcut, like:
```java
public class Screen {
    public <T> T start(ScreenApplication<T> screenUser) {
        startScreen();
        try {
            return screenUser.apply(this)
        } finally {
            stopScreen();
        }
    }
}

interface ScreenApplication<T> {
    public T apply(Screen screen);
}
```

**Comment by avl42** [comment]
The idea isn't bad. I'm just not yet sure, if this approach doesn't add more complexity than it solves :-)

**Comment by mabe02** [comment]
That's merged now. Anything else here?

**Comment by dant3** [comment]
@mabe02 just tried `if (System.console() != null) {` as you suggested - it works like a magic. Thank you. It would be awesome to change `DefaultTerminalFactory` behaviour to use it. Otherwise this appears to be solved.

**Comment by avl42** [comment]
That's already done (8 days ago, in commit c487d176...)
If it doesn't work, please report explicitly.
