### ISSUE TITLE
Block graphics shown incorrect

### ISSUE THREAD

**Issue by ernstmoritzhahn** [mabe02/lanterna#152]
Certain block graphic characters are shown incorrectly in the terminal emulator (in Mac OS X). In particular, vertical double lines are shown as single lines. For instance, the sequence ║═╣╬ is shown as seen in the attached figure.
![screen shot 2015-07-14 at 20 43 04](https://cloud.githubusercontent.com/assets/13343877/8690698/74ac5eca-2aea-11e5-9b89-b326bcb6f196.png)

**Comment by avl42** [comment]
I don't have a mac, so can't try that myself, but:
 * If you copy Lanterna's output and paste it somewhere else: do you see single or double vertical bars?
 * If you paste the double-bar characters directly into the terminal (e.g. as argument to an echo), do they show up correctly?
 * Could you start your Lanterna app within the "script"-utility to capture its exact output?  It would be interesting, if Lanterna actually changes the characters (which afaik it only does when the terminal isn't on Unicode - but then the horizontal parts would probably be single lines, too).

**Comment by dant3** [comment]
What font are you using in your Terminal emulator? I think font is the culpit here. Could you share your code so I can try to reproduce it? In my terminal emulator on OS X same char sequence looks as expected.

**Comment by ernstmoritzhahn** [comment]
I did not change anything (intentionally) concerning the font. When the program is ran in headless mode in a terminal, the characters are printed correctly. I am not able to mark characters in the SwingTerminalFrame.

The code I was using is as follows:

    package kwirk;
    import java.io.IOException;
    import com.googlecode.lanterna.graphics.TextGraphics;
    import com.googlecode.lanterna.screen.Screen;
    import com.googlecode.lanterna.screen.TerminalScreen;
    import com.googlecode.lanterna.terminal.DefaultTerminalFactory;
    import com.googlecode.lanterna.terminal.Terminal;
    import com.googlecode.lanterna.terminal.TerminalFactory;

    public class LanternaTest {
        public static void main(String[] args) throws IOException {
            TerminalFactory factory = new DefaultTerminalFactory();
            Terminal terminal = factory.createTerminal();
            Screen screen = new TerminalScreen(terminal);
            screen.startScreen();
            screen.refresh();
            TextGraphics writer = screen.newTextGraphics();
            writer.putString(1, 1, "║═╣╬");
            screen.refresh();
            screen.readInput();
            screen.stopScreen();
        }
    }

**Comment by avl42** [comment]
Oh, my comments were all under the assumption of UNIXTerminal.

Btw., "script" is a utility that can capture the output of programs started from within it.
This is however not relevant to SwingTerminal.

SwingTerminal indeed doesn't yet(?) support copy&paste.

**Comment by dant3** [comment]
Works totally fine for me on OS X
![image](https://cloud.githubusercontent.com/assets/820057/8706993/a50efa22-2b3b-11e5-8e0f-b5f1e7e3b406.png)

**Comment by ernstmoritzhahn** [comment]
It seems to be a problem with the font used. When I choose a font size smaller or larger than 14, the block graphics are shown correctly.

**Comment by mabe02** [comment]
Yeah, with the code in that way, it must be a font issue.
