### ISSUE TITLE
Problem building with JRE 6

### ISSUE THREAD

**Issue by dant3** [mabe02/lanterna#154]
I have a build machine with such settings:

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/share/maven
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-6-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-36-generic", arch: "amd64", family: "unix"
```

which fails to build Lanterna desipite settings in maven project says it's compatible with java 1.6. Error log shows:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /build/src/main/java/com/googlecode/lanterna/terminal/ansi/UnixLikeTerminal.java:[11,31] cannot find symbol
symbol  : class Redirect
location: class java.lang.ProcessBuilder
[ERROR] /build/src/main/java/com/googlecode/lanterna/terminal/ansi/UnixLikeTerminal.java:[82,29] cannot find symbol
symbol  : variable Redirect
location: class com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal
[INFO] 2 errors 
```

Oracle docs says [java.lang.ProcessBuilder.Redirect](http://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.Redirect.html) was introduced in JRE 1.7

**Comment by avl42** [comment]
Damn & sorry, that was my fault...  I'm running with Java 7 here, and casually I inadvertently use something that wasn't yet in Java 6.
In this case it is some feature of the ProcessBuilder, where I try to redirect the Process-input  from a given File-object. If you see an alternative way to specify that redirection with Java 6, then please patch&PR it.  Otherwise, we might need to back-out my commit that removes the need for /bin/sh.

**Comment by mabe02** [comment]
Reflections to the rescue!

**Comment by mabe02** [comment]
...ah, spoke too soon, you are right, the stty command fails on Java 6 without the redirect. We could add a different code path for Java 6 when building the STTY command and call the Java 7+ redirects with reflections.

**Comment by mabe02** [comment]
Ok, should be fine now
