### ISSUE TITLE
Let Border pass through LayoutData

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#167]
This is the outcome of my confusion about TextBox disappearing with Border (Discussion in Issue #166): the original Test case was all ok, it was entirely my fault, but ...

The snippet went like this:
```java
            TextBox textBox = new TextBox( ... );
            textBox.setLayoutData(BorderLayout.Location.CENTER);
            content.addComponent(textBox);
```
I wanted to add a Border to the TextBox, and changed only the last line to:
```java
            content.addComponent(textBox.withBorder(Borders.doubleLine("textbox border")));
```
And after that, the textbox just disappeared. It no longer disappears with BorderLayout in latest version, but it still has potential for surprise, such as just ignoring any layoutData provided.

The reason is simple now in hindsight: the withBorder() wrapped the textBox into a new component, but this new component (the wrapper) did not itself have it's wrappee's layoutData!

And this is where this issue actually starts:
I suggest to have Borders always pass through their wrappee's layoutData as if it were their own.  Inside a Border, the wrapped component's layoutData would not be used, anyway, so just let Border reflect it!

This involves AbstractBorder.getLayoutData() and AbstractBorder.setLayoutData().

**Comment by mabe02** [comment]
Agreed; that's merged
