### ISSUE TITLE
Infinite (scrollable) size terminal

### ISSUE THREAD

**Issue by oserban** [mabe02/lanterna#171]
I want to create something like a simple text, bash-like, terminal in Java and everything goes well, until the screen is filled with text and it does not resize. I use just a plain old Screen for this example and the screen.putString(...) method with an incrementing counter for lines. I know about the text area component, but there are some controls already implemented on the text area (up/down arrows, tabs, etc), which I want to use for my terminal. Any suggestions?

**Comment by avl42** [comment]
One option is the VirtualScreen, which wraps a normal Screen and pretends to be a potentially biiiig Screen itself, of which only a specific part is visible on the real Screen.  Advantage: probably quickest to use. Disadvantage: scrolling is hardwired to Ctrl-Arrowkeys which don't work on every terminal and the Scrollbars (and the extra information line below the horizontal sb) might not be the most pleasing. Also, growing a single Buffer will become slower and slower as it gets larger...

Another option is, to use the (rather new) scrollLines method of Screen (after saving the previous top lines away - ideally in a list of single-line buffers to avoid growing them). If you don't need to save text attributes (bold, underline, color,...) then just saving the Strings saves memory. That seems to me like the most flexible approach.

Third option is to pick ideas from VirtualScreen and replace the scrollbar-drawing code by your own design...  Unfortunately, VirtualScreen is not at all subclass-friendly at the moment (a protected or public setter for a replacement FrameRenderer and an overrideable "filter" method would be nice to have...). You'll still eventually run into problems with too large buffers...

**Comment by oserban** [comment]
Thank you for your information. I managed to solve the problem with the latest source code and by using the scroll function on the terminal. Repository: https://github.com/oserban/simple-terminal

**Comment by mabe02** [comment]
Cool, thanks!
