### ISSUE TITLE
CJK characters not displayed on window title

### ISSUE THREAD

**Issue by chunlinyao** [mabe02/lanterna#174]
CJK Characters not displayed on window title, It also not displayed in list items initially, but select and unselect the item will display CJK characters.
![2015-09-24 8 30 11](https://cloud.githubusercontent.com/assets/148663/10073406/2c773a82-62fb-11e5-846b-81998b1fc04d.png)
![2015-09-24 8 30 24](https://cloud.githubusercontent.com/assets/148663/10073411/336d77a2-62fb-11e5-89d4-d544b5f4956a.png)

**Comment by avl42** [comment]
I could reproduce the problem with a SwingTerminal by editing lanterna/src/test/java/com/googlecode/lanterna/gui2/DialogsTextGUIBasicTest.java  and adding letters テスト to the window  and item labels. Btw., the problem also shows on the first item, which initially has the blue selection bar on it.

Running it in a UnixTerminal, the CJK characters were showing just fine right away, so it is apparently a SwingTerminal-problem.

PS: There is also another problem (independent of Terminal), where adding the CJK-letters at end of first item's label (which is the longest) will have the last letter (ト) chopped off. Seems like CJK-characters need some consideration in getPreferredSize() methods...

**Comment by avl42** [comment]
Just saw that Martin already fixed this bug in the repository.

The cut-off mentioned in the PS: of my previous comment however still happens.

**Comment by mabe02** [comment]
Yes, I did a bunch of CJK bugfixes recently, especially some components didn't consider that cutting off characters because the area is too small sometimes removing two characters if the last one is CJK. Which component did you see the cut-off on?

**Comment by avl42** [comment]
lanterna/src/test/java/com/googlecode/lanterna/gui2/DialogsTextGUIBasicTest.java adding letters "テスト" to the first(the longest) item label, thus: "Simple TextInputDialog テスト".

From the symptoms I suspect that some getPreferredSize() is the culprit here, but I haven't verified it, yet.

**Comment by mabe02** [comment]
Yep, found it. Corrected a few other places that was relying on String.length() being equal to the number of columns it will take up in the terminal too. Almost thinking about creating an immutable TerminalString class that wraps a String and takes care of all these calculations automatically... It's definitely not the last time we'll see CJK errors due to forgetting to use CJKUtil.getTrueWidth to measure strings.

@chunlinyao can you try with latest master branch and see if you case is working now?

**Comment by mabe02** [comment]
Lots of CJK fixes pushed, should be working much better now. Please re-open if this persists.
