### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by fabioticconi** [mabe02/lanterna#176]
Hello, I've just started using Lanterna. It doesn't seem like there is a mailing list or chatroom for this - can't it be setup? Gitter is pretty commonly associated to github repos nowadays, and very useful for quick questions.

Might also be good to port the google code wiki to github wiki (https://code.google.com/p/support-tools/wiki/WikiToMarkdownTool), as we users could give a hand improving it.

Anyway, thanks for this software! Can't wait for 3.0.0 stable.

**Comment by avl42** [comment]
Well, you've found the place, where to complain about missing features or (not-missing) bugs :-)
I'm afraid, the lanterna community isn't yet large enough to keep a chatroom busy (i.e. with timely responses), but you can ask questions here...

About moving the wiki from google code to github we'll have to wait for Martin's answer.

**Comment by fabioticconi** [comment]
Thanks, @avl42. I can live without a chatroom for now, ok :) but to tell you the truth, I'm really craving for examples: do you know of any projects using Lanterna? Particularly the 3.0.0 version.

**Comment by avl42** [comment]
I certainly do know my own project, but unfortunately I can't share it.
Based on previous issues posted here, there seem to be a couple of projects in the wild. the googlecode forum "lanterna-discuss" also had some posts hinting towards uses of lanterna in projects.

**Comment by mabe02** [comment]
Yeah, waiting for me to reply is typically what's going on here :)
