### ISSUE TITLE
InputDecoder not exposed by StreamBasedTerminal

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#177]
Since May 20  (commit 65379cb03905b779489625ef42a14b3cb2dca0a3) the InputDecoder exposes public methods to retrieve and to remove individual CharacterPattern-instances from its internal list of patterns.

Unfortunately, though, the StreamBasedTerminal creates its privately kept instance of InputDecoder, and only offers method addKeyDecodingProfile to add KeyDecodingProfiles to its private InputDecoder,
but nothing else.

This means, that the work done in InputDialog back then is still mostly out of reach for me.

I'd ask for a protected method getInputDecoder() to be added to StreamBasedTerminal, such that derived classes can get hold of the InputDecoder-instance and examine&modify its pattern list.

**Comment by avl42** [comment]
Also, while the class BasicCharacterPattern was made public long ago, its constructor unfortunately was forgotten, so user-code still cannot create its own instances of that pattern class...

**Comment by mabe02** [comment]
Agreed, I've changed it now so that you can access the InputDecoder. Kind of wish I had made it an interface now, but oh well.

**Comment by mabe02** [comment]
I suppose we could go even further an let StreamBasedTerminal take an InputDecoderFactory, make InputDecoder an interface and so on... Overdesign?

**Comment by avl42** [comment]
Factory seems overkill for me, but maybe a setter for an alternative/subclassed InputDecoder.  No interface necessary, imho.
