### ISSUE TITLE
doResizeIfNecessary don't work correctly

### ISSUE THREAD

**Issue by guiguidu60** [mabe02/lanterna#188]
Hi,
I using the "onResized" method from Terminal for re-draw the interface of the console but when I used the method "doResizeIfNecessary" from TerminalScreen, the method don't return the correct new terminal size when I extend the (real) terminal dimensions with the "enlarge" button of the terminal.
More simply: New size are not updated when we used the enlarge button of the terminal.

Sorry for my ba english, I hope you have understand =).

**Comment by avl42** [comment]
Calling onResized() most likely isn't the correct thing to do, except if you actually know the new size already.

If you only want to re-draw the screen, just use the refresh() method of the screen.

Lanterna has some built-in tricks to try to find out when the terminal is resized and what the new size is. These tricks are specific to each type of terminal:  SwingTerminal(-Frame), UnixTerminal, TelnetTerminal, CygwinTerminal, ...  If resizing doesn't work for you, then remove all your calls to onResized() because they might confuse lanterna. If it still doesn't work then let us know which kind of Terminal you're using.

I hope that helps.

**Comment by guiguidu60** [comment]
It's too hard for understand how use Lanterna librairy.
There is no explanation for know how use it (just a description of each element of the librairy).

It would good if you create a documentation to find out in what order and how to use this or that class and finally, how use the librairy correctly.

**Comment by avl42** [comment]
If you have checked out Lanterna from github, then you also have a "test" directory which contains a couple of simple example programs.

For a few months now, there is also an "example" directory, but that so far has only three examples in it.  It was once intended to move the standalone examples from "test" to "examples", but that hasn't happened yet.

About two weeks ago, Benjamin Dale contributed some awesome documentation, which you can find on lanterna's github-page ( https://github.com/mabe02/lanterna ) when you scroll down to "Development Guide" header, and right below that, it says: "See docs for examples and guides." and the word "docs" is a link.  Follow it...

**Comment by guiguidu60** [comment]
Almost all examples are GUI examples.
There is no example for use lower layers of the terminal.
Too bad !

Never mind. Thanks for your help :)

**Comment by avl42** [comment]
The lower levels are much "easier" to use: you open terminal and (if wanted) screen like in the gui examples, and then all you need is javadoc of Terminal or Screen interfaces :-)

**Comment by guiguidu60** [comment]
It's not always easy to understand a javadoc.
For the the terminal and screen layer, there is no example, unfortunetely.

**Comment by avl42** [comment]
I'd suggest the TerminalInputTest as an example for a non-gui application. (you see it in the test tree when you check out lanterna from github)

Also, you can describe what sort of application you plan to do, then we can find more useful examples, and eventually improve docs to include terminal and screen examples.

**Comment by guiguidu60** [comment]
A lot of example (GUI and/or Terminal) are not updated, so not compatible with Lanterna 3.0.

With Lanterna library, I would like to make a non-gui text editor for programmer (a non-gui equivalent to Eclipse, but very simple).

At the moment, I'm trying to build a small library who manage the cursor and the basics key events (arrows, backspace, enter).
I think we could integrate that to the library :)

**Comment by avl42** [comment]
I think, you really need the "GUI" part of Lanterna, then.  Rest assured it isn't graphical in the usual sense - it's really all character oriented.

You might want to google for text-based development environments from old MSDos-days, especially Borland's products, like for example their "Turbo Pascal 5.0".  User-interfaces like that are what Lanterna (with it's GUI Layer) can help you to implement.

A lot has changed in the GUI layer between 2.1.* and 3.0.* - that's true for sure. Rather stick to newer tutorials and examples.  If you see a useful component in an old tutorial, you can ask here on github about it's 3.0 pendant. And if there is none, then asking here is the first step towards getting one added to Lanterna.

Lanterna already solves handling keyboard input for you - it converts those complicated escape-sequences into single KeyStrokes.  See the TerminalInputTest for that.

Have you checked out the complete Lanterna tree from github, yet?

What is your personal background in the world of character-based user interfaces?

**Comment by guiguidu60** [comment]
You're right !
I should use GUI part of lanterna for my program and that what I will do.
It's more simple :)
I don't have a lot of experience in programming, and It's my first time with a character-based user interface.

Thanks for your help !
