### ISSUE TITLE
screen.refresh blackscreens and blocks the thread

### ISSUE THREAD

**Issue by lyze237** [mabe02/lanterna#189]
I've written a simple log program which would allow me to display the log of a program and interact with it.

My main goal right now is to make the components dynamic. So whenever we change the terminal size, the program should adjust itself: ResizeListener -> Change Variable Size -> Refresh

However when I try to refresh the screen it blocks after a couple times and doesn't refresh properly: http://imgur.com/0MuSvir

Initialization of the Screen:

        DefaultTerminalFactory factory = new DefaultTerminalFactory();
        factory.setInitialTerminalSize(new TerminalSize(150,50));
        factory.setSwingTerminalFrameTitle(name);
        terminal = factory.createTerminal();
        terminal.addResizeListener(this);
        screen = new TerminalScreen(terminal);
        screen.startScreen();

        TerminalSize size = terminal.getTerminalSize();

        Panel panel = new Panel();
        panel.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        Panel logAndChannel = new Panel();
        logAndChannel.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));

        channels = new ActionListBox(new TerminalSize(10, size.getRows() - 13));
        logAndChannel.addComponent(channels.withBorder(Borders.singleLine("Channels")));

        log = new TextBox(new TerminalSize(size.getColumns() - 30, size.getRows() - 13), "", TextBox.Style.MULTI_LINE);
        log.setReadOnly(true);
        logAndChannel.addComponent(log.withBorder(Borders.singleLine("Log")));

        panel.addComponent(logAndChannel);

        Panel options = new Panel();
        options.withBorder(Borders.singleLine("Send Message"));

        options.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));

        channel = new TextBox(new TerminalSize(10, 1), "Channel", TextBox.Style.SINGLE_LINE);
        options.addComponent(channel);

        options.addComponent(new EmptySpace(new TerminalSize(1, 1)));

        input = new TextBox(new TerminalSize(size.getColumns() - 36, 1), "Message", TextBox.Style.SINGLE_LINE);
        options.addComponent(input);

        send = new Button("Send");
        options.addComponent(send);

        panel.addComponent(options.withBorder(Borders.singleLine("Send Message")));

        window = new BasicWindow();
        window.setComponent(panel.withBorder(Borders.doubleLine("DarkOwlBot")));

And the resize listener:

    @Override
    public void onResized(Terminal terminal, TerminalSize size) {
        System.out.println("Resized: " + size);
        log.setPreferredSize(new TerminalSize(size.getColumns() - 30, size.getRows() - 13));
        try {
            screen.refresh();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

Launch:

     if (GraphicsEnvironment.isHeadless()) {
                logWindow = new ConsoleLogWindow("Dark Owl Bot");
            } else {
                logWindow = new ConsoleLogWindow("Dark Owl Bot");
                // logWindow = new SwingLogWindow("Dark Owl Bot");
            }

            new Thread(() -> {
                logWindow.display();
              
            }).start();

logWindow.display():

        MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
        gui.addWindowAndWait(window);

Note: I've tried it already with every Refresh Type.

Is there a possibility that I do something wrong?

**Comment by avl42** [comment]
You register your class at the terminal to be notified of size changes.
So does the TerminalScreen class, and in the handler it just stores the new size.

I think there already should be some mechanism to ensure that in the end the screen will be refreshed automatically after a resize.  That means: just remove the call to refresh() (along with the surrounding try-catch), and see if that already solves it all.  I'd expect it does.   If it doesn't, let us know about what didn't work.

PS: My own project doesn't use the GUI layer, so I don't really have much experience with that. I hope it helps, anyway.

**Comment by lyze237** [comment]
Nope. Not doing the refresh it just doesn't resize at all.

**Comment by avl42** [comment]
Ok, I now pasted this into a local file and stepped through it. 
So far, my conclusion is that:
  1.  the call to screen.refresh() really isn't needed and may have been the reason for even worse symptoms.
  2. Panels are lazy about recalculating the sizes of their included components

Just for testing, I declared all the Panels as fields, and within onResized() I call  .invalidate() on them.
I then saw some reaction of the log window growing and shrinking with the window.

There were some more obstacles, though, as the "channels" ActionListBox isn't yet grown, so it sticks at its old height, which prevents the window from shrinking, which then causes the VirtualScreen to show its own scrollbars, as the window no longer fits into the terminal.

I'm not sure if Panel's laziness is a bug or feature, but for now it means, that if you want to control the size of a particular nested component, you always need to invalidate all enclosing panels.

**Comment by mabe02** [comment]
I think windows that resizes along with the terminal is something we should add before 3.0.0 final release. At the moment, it should be doable using a listener for when the terminal has changed its size and then forcibly invalidate some component and set its size to something calculated from the total size.

**Comment by mabe02** [comment]
Ok, if you can, try with latest master and add Window.Hint.EXPANDED to your window. This should make the window manager dynamically size your window dependent on the size of the terminal.
