### ISSUE TITLE
Table and ComboBox component are not present in  maven beta-1

### ISSUE THREAD

**Issue by vacax** [mabe02/lanterna#193]
Hi,

The components Table and ComboBox are not present in maven repository for 3.0.0-beta1.

Regards

**Comment by avl42** [comment]
The beta1 (from 2015-06-28 12:35:45 UTC) is already somewhat aged.

We're all holding our breaths for a new labelled release, and mabe02 makes cleanups and pushes improvements almost every weekend....

We've got to be patient - from watching the commits it seems like our patience will be rewarded :-)

**Comment by mabe02** [comment]
Yes, patience :)
Soooooon!
