### ISSUE TITLE
How do you react to events?

### ISSUE THREAD

**Issue by drozzy** [mabe02/lanterna#196]
Sorry for the dumb question, but none of the examples see to show to how hook up a callback to any of the button or key presses...
Any pointers?

**Comment by avl42** [comment]
A generally common way to do callbacks in any Java framework is to make a class (typically anonymous) that implements the interface "Runnable", and pass an instance of that class to some component.

I just picked some class from lanterna's test hierarchy (GridLayoutTest.java) and it contained a snippet like this:
'''
        contentPanel.addComponent(new Button("Close", new Runnable() {
            @Override
            public void run() {
                window.close();
            }
        }));
'''
class Button has two constructors, one with only a label and one with a label and an action. This snippet uses the second one.   And, to be honest, I don't really see any use for the first one.

If you were just using a binary package of lanterna, then it probably didn't contain the "test" hierarchy, so don't feel bad for not finding it. :-)

**Comment by mabe02** [comment]
Yeah, documentation (Issue #107) is the next thing after getting 3.0 final build released. I know we're lacking at the moment. At least everything should have Javadoc now.
