### ISSUE TITLE
AwtTerminal

### ISSUE THREAD

**Issue by jbergenthal2** [mabe02/lanterna#199]
I have developed an implementation of AwtTerminal, ScrollingAwtTerminal, and AwtTerminalFrame classes.
These are nearly identical to the swing ones, but obviously without swing dependencies.
They are useful for runtimes lacking swing, like embedded systems (JME).
Would the project be interested in these?

**Comment by avl42** [comment]
Martin apparently doesn't login here very often, so if you PR it, he can later decide whether or not to pull it.

It does sound useful to me, for what it's worth...

**Comment by avl42** [comment]
PS: maybe it can also be slightly optimized ("refactored") for less code duplication...

**Comment by jbergenthal2** [comment]
Done, see Pull Request #200.
Surely it asks for refactoring, but lets first see if it's accepted.

**Comment by mabe02** [comment]
Okay, looks like a lot of duplication with the existing Swing code. Let's see if we can reduce some of that by keeping common code in separate implementation-agnostic classes.

**Comment by mabe02** [comment]
There, all merged now. Unfortunately I don't have any AWT-only system available, so please try it out and let us know how it works.
