### ISSUE TITLE
Random white screen with SwingTerminal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#2]
```
On Ubuntu 10.04, sometimes when launching the SwingTerminal, the window starts 
all white and it doesn't draw anything. Seems very random, still haven't been 
able to figure out to reproduce it.

Unverified on any other platform
```

Original issue reported on code.google.com by `mab...@gmail.com` on 28 Jun 2010 at 7:32

**Comment by mabe02** [comment]
I've rewritten the way the program draws the terminal now, so I'm pretty sure (*fingers crossed*) this is fixed now, whatever it was. Please reopen if it persists.
