### ISSUE TITLE
Borders width in Android SSH client

### ISSUE THREAD

**Issue by lnowak** [mabe02/lanterna#206]
I am using lanterna to generate some simple GUI in SSH client. Everything looks OK, but when I try to add some borders to panels the width is larger that it should be. The problem is only on SSH client on Android device. When using Linux terminal all looks OK. 

Any ideas how to fix it?

**Comment by avl42** [comment]
This is a bug of either android (for the fonts) or of the ssh-client. I've
seen it with juice-ssh and reported it to no avail, yet.  Btw., mc is also
affected.

**Comment by avl42** [comment]
All was fine on some android 4.2 device that I once had.

**Comment by mabe02** [comment]
Do you have any screenshot? As @avl42 is pointing out, it's probably an issue with the terminal emulator software in the ssh client

**Comment by avl42** [comment]
![img_20160211_235403_651](https://cloud.githubusercontent.com/assets/5255346/12993541/03fd074c-d11b-11e5-9382-c2252abf9f8c.jpg)

here is a screenshot. (sorry for the dark patches, but i had to "censor" it, and the only editing app for images on my device allowed only freehand drawing...)

**Comment by lnowak** [comment]
I am having the same issue as @avl42 showed on the screenshot. I have tested couple of terminal app on Android 5.

**Comment by avl42** [comment]
I'd appreciate if anyone with an Android 6 device could check it.

**Comment by mabe02** [comment]
Weird, the fonts look like they are monospace so I don't see why it's not aligning correctly... @avl42, are you using GUI layer for this?

**Comment by avl42** [comment]
This isn't a lanterna problem!
lanterna is in textterminal mode on a real machine, and we use an ssh-app
to connect to that machine to run the application. it doesn't matter, if we
run lanterna or e.g. mc , longer streaks of linedrawing characters are
drawn too wide.

maybe we can workaround this problem, by inserting space-backspace
sequences, but i need to test it, and even then it would degrade
performance for other uses, so would need to be triggerable from outside,
e.g with some envvar.

**Comment by avl42** [comment]
PS: sending space-backspace between subsequent line-characters unfortunately doesn't help...
   I'll try more tricks as I think of any...

**Comment by avl42** [comment]
To anyone with any ssh-app on an android 5 (or higher) device:
Here is an experiment: save the following block to a file and have it displayed through the device's app.
```
x------y
x──────[0m0[m
x──────[1m1[m
x──────[2m2[m
x──────[3m3[m
x──────[4m4[m
x──────[5m5[m
x──────[6m6[m
x──────[7m7[m
x──────[8m8[m8
x──────[9m9[m
x──────y
```
This block contains escape characters, and I'm not sure, if this will even pass through correctly...

**Comment by avl42** [comment]
When I view my previous post in my browser on my PC, all the line-parts (──────) are equal long to the dashed one in first row, and the sorry remains of the escape-chars are strictly at same horizontal position as the y's.

If I see this in a browser on android, the lines are already a bit longer than the dashed line. 

If I view the original file (with real Esc chars for the �s) on android, then depending on the formatting of next character the lines are equal to the dashed one, or longer. Thus, displaying e.g. a bold character after the line will cause the line to be right length. 

This doesn't mean that the line is drawn correctly, only that the bold character causes a repositioning to the right spot.   You can see it, if you replace the line part of the row with attribute 3  to `─a─b─c` .

So much for now.  If any(or every-)thing unclear, ask.
If you don't have an Android device, or don't have any ssh-app on it, or don't have any unix machine to log in to via the app, then you can safely ignore it.

**Comment by avl42** [comment]
[tmp_5309-line-test475353312.txt](https://github.com/mabe02/lanterna/files/128352/tmp_5309-line-test475353312.txt)
Here is a shorter file that can be downloaded to the device and `cat`ed on local device.

**Comment by mabe02** [comment]
I tried it on my phone (Android 5.0) and I got the same weird result:
![lanterna-android-5 0](https://cloud.githubusercontent.com/assets/10136489/13027332/1d213cce-d28e-11e5-9c74-d291bb51acbc.png)

What weird was that if you selected, copied and pasted one of the horizontal line characters, they were rendered as 1.5x wider than a regular character but the input reacted as if they were normal. So with two line characters and the final 'y', when I move the cursor to the end of the line (_after_ the 'y') I get this:
![lanterna-android-5 0-2](https://cloud.githubusercontent.com/assets/10136489/13027352/251e470e-d28f-11e5-80fa-6ce8bd4bdd8c.png)

So unless we are using the wrong horizontal line character (I don't think we are), this looks like a font problem on Android.

**Comment by avl42** [comment]
meanwhile I could think of some approachess, but some would be unacceptable for non-android terminals, thus would need some explicit switch:

-  map horizontal lines to dashes. corners and such will still be a bit wider but it won't add up that much

- map all linedrawing to dashes, pipes and plus

- toggle the blink(?) attribute for every linedrawing char. JuiceSSH seems not to blink anyway, but it causes it to draw next char at correct position. not sure if it was really the blink attr, though. among the attributes from 1 to 7 there were two whose visual effect was not recognizable, but only one of them had the position-correcting effect.

- send a report to JuiceSSH and other app's developers and hope that they code a workaround where it fits best.

**Comment by avl42** [comment]
PS: people are having troubles with that also outside terminals: 
  http://stackoverflow.com/questions/33226826/nexus-5-monospace-font-has-different-width-for-unicode-circles

it's definitely google to blame here...

**Comment by mabe02** [comment]
Yeah, looks like they've inofficially acknowledged that by tagging it:
https://github.com/googlei18n/noto-fonts/issues/617

I'm going to close this issue, we shouldn't be the ones putting in workarounds.
