### ISSUE TITLE
BorderLayout can cause a busy-loop freeze if content is too large

### ISSUE THREAD

**Issue by nikiroo** [mabe02/lanterna#213]
(Using version 3.0.0-beta2)

I'm adding Labels (new Label("some text")) to a Panel set to BorderLayout on LEFT and RIGHT.

When the LEFT label is too large (it exceeds the remaining space), it is truncated to take all the remaining space.
But then, if there is some components left, probably either at CENTER or RIGHT (I tried with RIGHT, but since it causes a busy-loop I still didn't test all possibilities), it is assigned a 0-width size.

This 0-width component creates a busy-loop and freeze the application.

If I force-set it to, say, 1, it works (though it is not optimal in the sense that I know see one character of the RIGHT label which should have be erased or fully shown, but not half shown).

If I have some time tomorrow, I'll have a better look at what causes this.
Setting a minimum-forced-size is not such a good idea since then you cannot create a BorderLayout with less than [number-of-comps] * x of width...

(The code I looked at, which may not be the actual culprit but just something happening before it, is in BorderLayout.java
```public void doLayout(TerminalSize area, List<Component> components)```
after the 
```//Now divide the remaining space between LEFT, CENTER and RIGHT```
comment.)

**Comment by avl42** [comment]
Thanks for you report.

It's about time we found all components that have trouble with 0
width/height.
Apparently BorderLayout with a large LEFT (or TOP) component is a good
means to trigger bugs in those other components.

I might not get to eclipse until tomorrow, so if you could go ahead and
select various components as RIGHT (or BOTTOM) such that they'll end up
with a zero width (or height), that would help us checking what's wrong in
those components.

From a cursory look into BorderLayout, it's logic seems alright, but it
definitely will assign a 0 size to secondary components, and those
components either can deal with it, or they should be fixed so they can.


At least, please tell us which components you currently have in RIGHT
location that caused the freeze.

**Comment by nikiroo** [comment]
Well, a Label.

Also, from what I see of the code, you can try to assign negative values as the component size.
Unless maybe it's fixed later on? I didn't check the TerminalSize class, and I don't have Eclipse right now.

I'll make sure to report any other component I see with the same problem -- I actually thought it was linked to the Layout type, that's good to know.

**Comment by avl42** [comment]
I got to play around a bit...

with one example (with a BorderedWindow) I could trigger an exception in TerminalSize about negative sizes (The whole decorated window was at size [1,42], and for the interior it would have constructed a [-1,40] TerminalSize) -- but no problems yet around width or height 0.

Just my results so far. Maybe this time Martin is faster with diagnosing this (and the Table issue, too)

**Comment by nikiroo** [comment]
Ok, I've got more information.
It seems the same kind of problem can also happen in a LinearLayout Panel (still with a Label) -- which was to be expected with the information you gave me.
I dug a bit and found out why it happens.

It seems to happen in TerminalTextUtils.java # getWordWrappedText(...).
You create an infinite loop in some situation (when the text is too long to fit on the scrreen) in this part of the code:
```
				if (characterIndex == 0) {
					// Failed! There was no 'nice' place to cut so just cut it
					// at maxWidth
					result.add(row.substring(0, maxWidth));
					linesToBeWrapped.addFirst(row.substring(maxWidth));
				} 
```

I'm still on 3.0.0-beta, but I think I saw something about this method that changed recently for another bug?

Still, if I may, one possible correction would be:
```
				if (characterIndex == 0) {
					// Failed! There was no 'nice' place to cut so just cut it
					// at maxWidth
					result.add(row.substring(0, maxWidth));
					// ..if it is not possible, it is not possible.
					if (maxWidth > 0)
						linesToBeWrapped.addFirst(row.substring(maxWidth));
				}
```

**Comment by avl42** [comment]
Yes, this bug is already fixed on github (issue #210). The method
getWordWrapedText got some update...

**Comment by nikiroo** [comment]
Nice. I will check the correction as soon as I'm done reporting another issue (sorry if it seems like I bombard you with so many issues, I'm just using the lib for the first time --- I hope you don't mind ^.^")
I'll close this one after I confirm the fix (since I guess this is why the Close button is available).
Thanks.

**Comment by avl42** [comment]
Bug reports are always welcome, and even more so, when they arrive still in
beta-stage. That's what beta stage is for :-)

Yes, if you see it working with latest github, then please close it, and
I'll open another one for the negative size observation with borderedwindow.

**Comment by nikiroo** [comment]
Ok, I confirm that with the latest sources, the problem is fixed.
Thanks!
