### ISSUE TITLE
TextBox masking is no longer functional

### ISSUE THREAD

**Issue by spatula75** [mabe02/lanterna#215]
It looks like it broke in this commit: 

https://github.com/mabe02/lanterna/commit/cc60afad600ba943a8de1ac74bee2f1eb4f9eb03#diff-67489bde50927a5349221ed81f6c2656

The mask feature is now inoperative.

**Comment by mabe02** [comment]
Yes, it was lost when re-writing TextBox draw method earlier. I've put it back in now, thanks!
