### ISSUE TITLE
IndexOutOfBoundsException when adding row to TableModel

### ISSUE THREAD

**Issue by FrozenDroid** [mabe02/lanterna#216]
Read the title. 

`terminal = new DefaultTerminalFactory().createTerminal();
            screen = new TerminalScreen(terminal);
            screen.startScreen();

            // Create panel to hold components
            Panel panel = new Panel();
            panel.setLayoutManager(new GridLayout(2));

            panel.addComponent(new Label("Forename"));
            panel.addComponent(new TextBox());

            panel.addComponent(new Label("Surname"));
            panel.addComponent(new TextBox());

            panel.addComponent(new Label("Table"));
            table = new Table<String>("Test");
            tableModel = table.getTableModel();
            tableModel.addRow("hi");
            panel.addComponent(table);

            panel.addComponent(new EmptySpace(new TerminalSize(0,0))); // Empty space underneath labels
            panel.addComponent(new Button("Submit", () -> {
                tableModel.addRow("haiiii");
            }));

            // Create window to hold the panel
            BasicWindow window = new BasicWindow();
            window.setComponent(panel);

            // Create gui and start gui
            MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
            gui.addWindowAndWait(window);`

With that code, I get an exception; `java.lang.IndexOutOfBoundsException: Index: 1, Size: 1`

**Comment by avl42** [comment]
I've looked into it, and it seems to be indeed a problem within Lanterna...

When a row is added to the tableModel, the table itself doesn't know about the change, and so it doesn't recalculate its own fields (`rowSizes` and `columnSizes`), but instead shortcuts it in getPreferredSize().

To solve it (this is directed to @mabe02), I'd see two approaches:
 - add a "generation" counter to the TableModel class, that will be incremented on each modification (adding/removing rows/columns, maybe even setCell). In getPreferredSize() have table compare it's own cached value with tableModel's current value and if different, consider itself invalidate()d.

 - use Observer/Observable pattern, and let each table "register" to the tableModel. The TableModel then would then "update" all registered tables, which in turn invalidate() themselves.

@FrozenDroid: thanks very much for reporting!

**Comment by avl42** [comment]
Even if it is a bug in Lanterna that needs to be fixed,  it can be worked around for simple cases.
In the given example, you could add a call to `table.invalidate();` to the `.addRow("haiiii");` line.

**Comment by mabe02** [comment]
Yeah, the invalidate() workaround will do it, but I agree it should automatically detect table model changes

**Comment by mabe02** [comment]
Okay, I've pushed a fix that seems to work for your test case. Closing pre-emptively, please re-open if it still is not working.

**Comment by avl42** [comment]
This fix only works as long as  each tableModel is only used in a single table.

My two suggested fixes would solve it generally.

**Comment by mabe02** [comment]
Yeah, I had some seconds thought on this. Going to change it to use a table model listener.

**Comment by avl42** [comment]
"table model listener" definitely sounds like a good approach.

**Comment by mabe02** [comment]
Pushed

**Comment by avl42** [comment]
:+1: That should solve it for sure, and also for most future demands :-)
