### ISSUE TITLE
gui.addWindowAndWait(window) and closing Swing Window

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#217]
I played around with a simple Lanterna app (in particular the one from previous issue), and noticed, that the simple idiom:
```
        MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, ... , ... );
        gui.addWindowAndWait(window);
```
will not finish when the SwingTerminalFrame is closed through the WM. Instead, it just keeps running the loop of polling for input (getting null, not(!) EOF) then sleeping for a millisecond.

The culprit might be in SwingTerminalFrame, where the "disposed" flag (still false) seems not to reflect the fact that the real window is already gone.

**Comment by avl42** [comment]
PS: the JFrame's  defaultCloseOperation apparently was still on it's default HIDE_ON_CLOSE.  Having the SwingTerminalFrame's constructor call  `setDefaultCloseOperation(DISPOSE_ON_CLOSE);` seems to fix it, but I don't know the whole picture well enough to be able to judge if that is the right thing...  

Most of the test-apps get this done in TestTerminalFactory.createTerminal(), but this should probably be done either in the SwingTerminalFrame constructor directly or at least in the DefaultTerminalFactory.

**Comment by mabe02** [comment]
Yeah, I think I've fixed it now so that you always get EOF if the window has been closed... Can you try again?

**Comment by mabe02** [comment]
Actually, just hiding the window won't give an EOF in the current implementation. But we have to be careful, we don't want minimizing the window to cause EOF.

We could special-case SwingTerminalFrame so any WM close operation, no matter if it's set to just hide or dispose, is interpreted as an EOF. But, I think the AWT thread won't die until all windows are disposed, so maybe just leave it like this?

**Comment by mabe02** [comment]
Going to set `setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE)` in SwingTerminalFrame constructor, can't see any strong reason not to and it's probably going to save people a lot of trouble figuring out why their java process isn't shutting down. Makes sense?

**Comment by avl42** [comment]
It might still be a good thing to tie it to the CloseOnExitPrivateMode-thing. If a user requests the swing terminal window to be discarded upon exitPrivateMode, then (and only then) he likely wants it the other way round, too, namely that closing the swing-window also leads to EOF.

**Comment by avl42** [comment]
After another thought... forget my last comment...  Clicking the "x" just means "to the devil with that window" and that definitely must mean EOF on input ;-)

**Comment by mabe02** [comment]
Yeah, exactly, and you could change the default close mode on SwingTerminalFrame too, if you want to.
