### ISSUE TITLE
autoCloseTrigger ... can't have both CloseOnExitPrivateMode & CloseOnEscape

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#218]
A while ago, there were only two values for TerminalEmulatorAutoCloseTrigger, namely DoNotAutoClose and CloseOnExitPrivateMode. Essentially that was a "verbose boolean" flag.

As much as I liked the change to add CloseOnEscape as an option (instead of having it always on), one now cannot have the Escape Key and exitPrivMode **both** terminate the application.

We probably should make autoCloseTrigger an EnumSet rather than a simple reference, and change
the setter to clear the Set when called with `DoNotAutoClose`, and take a varargs style argument.  On the other end of matters, we'd change tests like `if(autoCloseTrigger == TerminalEmulatorAutoCloseTrigger.CloseOnEscape)`  to `if(autoCloseTrigger.contains(TerminalEmulatorAutoCloseTrigger.CloseOnEscape))`

Depending on replies I'll probably make a PR this weekend...

**Comment by mabe02** [comment]
Seems like a good idea

**Comment by mabe02** [comment]
Done!

**Comment by avl42** [comment]
I'm thinking about generalising that EnumSet to all kinds of emulation-specific flags.  For the moment I'd think of a choice for visible versus audible bell that could be added as a flag.

In that case, the  autoCloseTriggers would become "emulationOptions"...

While the underlying structure would be a Set, I'd leave the interface in the Factory to know about groups of dependent settings: setting the NoAutoClose option would just remove both positive auto-closers (escape and exitPriv), and setting visualbell would unset audiblebell and vice versa...   
Just an idea...

**Comment by mabe02** [comment]
Yeah, the problem is those settings that requires more that just a flag, so we need some value attached to it. If we go down the `TerminalEmulationOption` route, which properties do you think would fit in there?

**Comment by avl42** [comment]
I'll think this through more deeply. I do have some ideas about options with values, too, and I'll PR them eventually...
What is your opinion about option groups where setting one has the effect of possibly unsetting others? It may look odd from an abstract point of view, but seems to fit the expectations for the specific options. It should even be possible to have the exclusion logic local to the options, rather than "somewhere else" in the terminal factory...

**Comment by avl42** [comment]
PS: it would mimic an API that works like RadioButtons: set some options and some other options will pop out, if they conttradict the new one.

**Comment by mabe02** [comment]
Sure, sounds like a good idea

**Comment by avl42** [comment]
Just a note on progress...
I started yesterday with the easier parts (just the auto-close and bell-options and their radio-button like behaviour).

At the moment I could do with some decision-help about device-, font- and color configurations: I'd tend towards turning them all into a whole big bunch of individual options, like splitting deviceconfiguration up into separate options for cursor (shape,colors,blink-timings) and scrollback-lines, ... each one a single entry in some optionsMap.

For anyone dealing with Terminals directly (and not just asking DefaultTerminalFactory for one) this might induce some incompatibilities and migration effort.

**Comment by mabe02** [comment]
I'm not too worried about the AWT/Swing terminal API (I've broken it before several times), it's only supposed to be used for testing.
