### ISSUE TITLE
Ring terminal bell?

### ISSUE THREAD

**Issue by null-dev** [mabe02/lanterna#219]
Is there any way the ring the terminal bell from lanterna?

(I mean this: https://en.wikipedia.org/wiki/Bell_character)

**Comment by avl42** [comment]
This topic certainly rings a bell ;-)

If you're on a real textterminal, then terminal.putCharacter('\7'); might work (depending on the terminal's settings. The swing-terminal didn't handle it, though, last time I tried. 

maybe a "bell()" method on Terminal would be fine...

**Comment by mabe02** [comment]
Hah, I'm going to replace \7 with ␇ if put into a Screen :)

**Comment by mabe02** [comment]
...actually, this reminds me that the awt/swing terminal needs code to deal with unprintable characters

**Comment by mabe02** [comment]
Well, there's the bell() for now

**Comment by avl42** [comment]
An audible bell might have been much easier to implement (for awt and swing).  Now that we even have the more complex visual bell in the emulated terminals, maybe we could offer both (as a DefaultTerminalFactory setter) ;-)

**Comment by mabe02** [comment]
Ehh, I'd rather not get into the sound domain... Is there a way to trigger the system's default notification sound from AWT/Swing? I've never had to do anything like that before.

**Comment by dant3** [comment]
How about:
```
import java.awt.Toolkit;

//...

Toolkit.getDefaultToolkit().beep();
```
?

**Comment by mabe02** [comment]
Let's add that then

**Comment by avl42** [comment]
I'd suggest two new methods audibleBell(dale's suggestion) and
visibleBell(what's now in bell) in the common superclass of the graphical
emulations, and have plain bell call one of them.

Once I get to it, i'd then change bell to call either one -  based on
options.
