### ISSUE TITLE
Up/down arrows in AbstractListBox

### ISSUE THREAD

**Issue by boekhold** [mabe02/lanterna#225]
The up-down arrows (`Symbols.ARROW_UP` and `Symbols.ARROW_DOWN`) are very hard to read on my terminal, especially when I change the theme colors to `TextColors.ANSI.DEFAULT` (which results in black background and white foreground on my system).

Could you consider different characters for that, or possibly allow customization of these characters through the theme?

Suggestions for alternatives:
- http://www.fileformat.info/info/unicode/char/25b3/index.htm
- http://www.fileformat.info/info/unicode/char/25b2/index.htm
- http://www.fileformat.info/info/unicode/char/25bc/index.htm
- http://www.fileformat.info/info/unicode/char/25bd/index.htm

**Comment by mabe02** [comment]
Yeah, I'm actually looking at changing those because they don't work very well with vanilla Linux terminal either

**Comment by avl42** [comment]
Just curious... could anyone post a screenshot of the arrows looking bad?
(I'd like to know if the arrows look so much different on other terminals, or if my demands are just low... ;-)

**Comment by boekhold** [comment]
Hi,

Here's screenshots of a "RadioBoxList" which has 3 items, and TerminalSize(15, 2).

Before scrolling to the last item:

![2016-04-04 09_25_45-swingterminalframe](https://cloud.githubusercontent.com/assets/3764084/14238939/9a5a120c-fa47-11e5-807c-b03c64fc84fd.png)

After scrollling down to item 3:

![2016-04-04 09_26_10-swingterminalframe](https://cloud.githubusercontent.com/assets/3764084/14238947/c09012d2-fa47-11e5-9b55-f2197dbbb2b5.png)

This is using the attached theme.

Maarten

**Comment by boekhold** [comment]
Here's what it looks like if I use a more realistically size list of items and TerminalSize(15, 4) so that the arrow_up, block_middle and arrow_down actually fit inside the specified size:

![2016-04-04 09_50_45-swingterminalframe](https://cloud.githubusercontent.com/assets/3764084/14239273/ea1039c2-fa4a-11e5-8104-8bfac960bbba.png)

Still not stellar...

**Comment by avl42** [comment]
Totally agree that these are not satisfying.  I made another screen shot to show that the arrows look quite different here, but github (or my browser) fail to let me upload it: I get some "Something went really wrong, and we can’t process that file." message.

So, a verbal description will have to do...

I tried with  SwingTerminalFrame, gnome-terminal, xterm and putty, and in all four of them, the arrowhead was wider and easily recognizable as an arrowhead.  on gnome-terminal it seemed like the arrow was picked from a different font, and the head was slightly clipped at the right edge of the character cell.

**Comment by mabe02** [comment]
That is really a very tiny arrow

**Comment by mabe02** [comment]
I tried the ones that you suggested but they don't work well with the standard linux terminal. I think the default theme should be as compatible as possible when it comes to characters (yes, the slim/fat lines in the scroll area has to go too...) so I'll try to find something else

**Comment by avl42** [comment]
How about ^,v,<,> ? ;-)

**Comment by mabe02** [comment]
Yeah, well, I've looked around and I can't find any good suggestions actually... < and > works well enough as they are balanced but ^ and v are not really the opposites of each other so it will look a bit weird

**Comment by mabe02** [comment]
Wonder if the triangle is more widely adopted than the arrows?

**Comment by mabe02** [comment]
Hmm, let's try out the triangles for a while and see how it feels

**Comment by mabe02** [comment]
Triangles looks pretty terrible with xfce4-terminal:
![scrollbar-test](https://cloud.githubusercontent.com/assets/10136489/14334499/adfb6250-fc4c-11e5-999b-093b5342abf8.png)
same on gnome-terminal:
![scrollbar-test2](https://cloud.githubusercontent.com/assets/10136489/14334503/b32b50fa-fc4c-11e5-8c47-506274a29729.png)

**Comment by avl42** [comment]
Actually, I'm not sure whether the scrollbars even need arrows at all.
It's not like you could click on them, anyway, or can you? (perhaps with mouse support?)

**Comment by mabe02** [comment]
It's more for historical reasons... :)
But I think also a horizontal scroll bar could be mistaken for a progress bar without the arrows

**Comment by mabe02** [comment]
Let's close this as stale
