### ISSUE TITLE
Correct Behaviour for Empty CheckBoxList/RadioBoxList

### ISSUE THREAD

**Issue by dkartaschew** [mabe02/lanterna#231]
Hi,
Just like to clarify what is the desired and expected behaviour for an empty CheckBoxList/RadioBoxList in regards to navigation?

In our application, in some circumstances a CheckBoxList or RadioBoxList may be presented to the user that contains no items. When using keyboard navigation, the input focus appears to disappear when the user traversing into the List, requiring the user to press a key again to leave the list and move to the next UI widget.

Some users have commented that if the list is empty, keyboard navigation should skip/bypass the List, and move onto the next UI widget. 
eg, we have a dialog that is made up as:
```
+---------------------------------+
|  [*] ListA - Item 1             |
|  [ ] ListA - Item 2             |
|                                 |
+---------------------------------+
| List B (empty)                  |
|                                 |
|                                 |
+---------------------------------+
| ButtonA | ButtonB | Button C    |
+---------------------------------+
```
When a user navigates from items in List A, should the cursor move to List B (and disappear) or move directly to Button A? (In our case, Button A is a refresh operation that may dynamically add or remove items from either list, based on results of a database/network operation).

Some of our users have found it confusing when the cursor stops in the empty List widget (and the cursor is not displayed), expecting it to skip to Button A instead, and likewise, moving from Button A stops in the empty list, and doesn't move to Item 2 of List A.

From the lanterna's developers view, what is the desired and correct behaviour in regards to cursor movement in this case?

**Comment by avl42** [comment]
It seems reasonable to me that a currently empty (Radio|Check)BoxList should - by default - be skipped for focus traversal.

However, there should still be a way for subclasses to change this behaviour, if they want to handle further KeyStrokes on their own and e.g. offer a Key to dynamically add items. In such a case, that *BoxList would need input focus even while empty.

just my two cents as another user...  It's Martin (@mabe02)'s decision.

**Comment by mabe02** [comment]
Yeah, agreed, if it's empty it should be skipped. I have thought of this before but never got around to implement it.

**Comment by mabe02** [comment]
Done and pushed
