### ISSUE TITLE
TextBox method for move caret to end of text

### ISSUE THREAD

**Issue by rjhdby** [mabe02/lanterna#233]
Login form for example.
All logins need to start with "U_"

I create new TextBox with default text
`final TextBox loginField = new TextBox("U_").setValidationPattern(Pattern.compile("U_[A-Z0-9]{0,6}")).addTo(panel);`

But caret positioning on first character instead of thrid column

**Comment by avl42** [comment]
I'd say you're expecting too much here.  The validation pattern is checked using Java's Regex Pattern engine, but not pre-analyzed by Lanterna to determine any initial (or trailing) fixed parts...

In your case, I'd just stick a Label with text "U_" left of the TextBox and make sure that the "U_" gets prepended to the TextBox's content, whereever you need the whole string.

**Comment by rjhdby** [comment]
Question not about this case, but about moving caret to end of already existing text inside TextBox
`    public TextBox setCaretToEndOfText() {
        this.caretPosition = new TerminalPosition(getLine(lines.size() - 1).length() + 1, lines.size() - 1);
        return this;
    }`

**Comment by avl42** [comment]
You're right, There isn't any public method to set the caretPosition as of now.

@mabe02 ?

In the meantime, you can try: textBox.handleKeyStroke(new KeyStroke(KeyType.END));

**Comment by mabe02** [comment]
I've create a public method manipulate the textbox caret position (just pushed), can you see if it does what you need?

**Comment by avl42** [comment]
@rjhdby ?

**Comment by mabe02** [comment]
Stale, closing...
