### ISSUE TITLE
[New Release] Please release a new mavenized 3.0 beta

### ISSUE THREAD

**Issue by notes-jj** [mabe02/lanterna#240]
I'm very interested in the change:
- https://github.com/mabe02/lanterna/issues/217 gui.addWindowAndWait(window) and closing Swing Window

I think it is a very essential fix. Could you please release a new mavenized 3.0 beta release with this fix.
I tested with the checked out version. But it better to use an official maven version.

**Comment by mabe02** [comment]
Yes, yes, it's on the way...
