### ISSUE TITLE
TextBox Ctrl + Space handling

### ISSUE THREAD

**Issue by celyo** [mabe02/lanterna#246]
Hi,

I have a problem while trying to handle Ctrl + Space inside a TextBox. the problem is that in handleKeyStroke the character in keyStroke is (char)128 not (char)32 and isCtrlDown == false.
I think that the problem is inside TerminalInputListener.keyTyped where SPACE character is shifted.

**Comment by avl42** [comment]
Please specify the type of terminal you use. Is it one of the GUI terminals
(swing,awt), or running in a unix terminal?

if the latter, also tell us in which terminal emulator it is running in.
(e.g. gnome terminal, xterm, kde terminal, raw linux textconsole,...)

**Comment by celyo** [comment]
It's inside GraphicalTerminalImplementation. Currently I'm just testing from IDE so I suppose and using DefaultTerminalFactory().createTerminal() which returns me SwingTerminalFrame.

**Comment by mabe02** [comment]
Yep, I've reproduced it. Fix on master branch.
