### ISSUE TITLE
Request: Button.addListener

### ISSUE THREAD

**Issue by davidsusu** [mabe02/lanterna#248]
Currently `Button` has an optional `Runnable` constructor parameter. There is no way to change/remove it - or to register more listeners. Other components have complete event handling support with specific event types and `addListener`/`removeListener` methods.

Could a full event handling support be integrated for the `Button` component too?

(Remember HTML's `onclick=""` vs `addEventListener()`.)

**Comment by avl42** [comment]
In principle I agree that offering the Observer(/Listener)-pattern would be nice for Button (and some similar components), but it is not impossible to "roll your own" with current Lanterna.  For that you'd create your own Runnable & Observable and pass it to Button's C'tor and from within run() it would notify all its Observers.

Could be worthwhile though to wait a bit and hope that Martin adds it directly to Lanterna.

**Comment by davidsusu** [comment]
> create your own Runnable & Observable and pass it to Button's C'tor

This is exactly what I have done. Nonetheless the difference between `Button` and the other components remains slightly uncomfortable.

**Comment by mabe02** [comment]
Yeah, good point. Let's do that.

**Comment by mabe02** [comment]
How about e45e1c6, do you think that will do what you need?

**Comment by avl42** [comment]
looks good, but maybe triggerAction should be protected, so the actions
could also be triggered from within a Button's subclass. maybe even public,
so it could be triggered from a masks hotkey-handling code.

**Comment by mabe02** [comment]
Yeah, why not, I think I've seen that pattern in other APIs
