### ISSUE TITLE
(Copy &) Paste?

### ISSUE THREAD

**Issue by schuettec** [mabe02/lanterna#252]
I really like what you have done there!
I use Lanterna as a small maintenance GUI for server apps. It would be useful to have a Copy&Paste feature. Correct me if I'm wrong but this feature is not present in a SwingTerminal isn't it? 
I tried CTRL+V and SHIFT+Insert.

Is it possible to get this working?

**Comment by mabe02** [comment]
Yeah, this isn't implemented. Paste would probably be easy to add, it's just about transforming a string into individual keystrokes, unfortunately copy is much harder because selection isn't implementation either.

**Comment by schuettec** [comment]
Hi, thanks for your answer. I will wait patiently for your new commits ;) :+1:

**Comment by mabe02** [comment]
Paste is implemented but select and copy isn't. I don't really have enough time to implement it either : /

**Comment by schuettec** [comment]
Hey! Thank you!
Paste is awesome! Do you have any hints how a copy feature can be
implemented? I could have a look. I think it is only needed to implement it
on SwingTerminal since Copy is working out of the box when using native
terminals right?

2017-01-15 14:07 GMT+01:00 mabe02 <notifications@github.com>:

**Comment by mabe02** [comment]
Yeah, the problem with copy right now is that the SwingTerminal/AWTTerminal doesn't have any code for selecting text. I imagine it would be non-trivial to implement this...

**Comment by schuettec** [comment]
Yes a saw that too. Hard to implement.
