### ISSUE TITLE
Is mouse supported?

### ISSUE THREAD

**Issue by aghasemi** [mabe02/lanterna#253]
Hi,
Thanks for the great job. Is mouse also supported?

**Comment by mabe02** [comment]
Thank you! Mouse support is partially supported through the ExtendedTerminal interface. The Swing/AWT implementation of Terminal doesn't implement this though, so you need a "proper" terminal emulator to test it.

**Comment by teras** [comment]
I tried to find a way to use my mouse events in the demo applications you provided.

So I created a UnixTerminal (on Linux)  and then setMouseCaptureMode(MouseCaptureMode.CLICK_RELEASE_DRAG) 

Still I wasn't able to see any interactivity with the default widgets.

Am I missing something?

**Comment by avl42** [comment]
As of now, default mouse support(once enabled) in the text gui classes is
limited to setting the focus to the component at the click location.
Admitted, that's likely less than satisfying for user experience, and you'd
have to "explain" to each component what really to do with a mouseclick,
-move or -drag.

Sorry for no better answer.

Panayotis <notifications@github.com> schrieb am Mi., 30. Mai 2018, 08:43:
