### ISSUE TITLE
ScrollBars on a Table do not inherit the theme of the parent component

### ISSUE THREAD

**Issue by ekoutanov** [mabe02/lanterna#259]
The problem is that DefaultTableRenderer does not call ScrollBar.onAdded() to assign a parent component, meaning that the scrollbar's render will fall back to the default theme.

(On the other hand, if you look at something like a TextBox, the renderer explicitly calls the onAdded() method, which propagates theme information to the scrollbars).

**Comment by ekoutanov** [comment]
on 3.0.0-beta3

**Comment by mabe02** [comment]
Yep, I just merged your pull request
