### ISSUE TITLE
How to make a component auto fill?

### ISSUE THREAD

**Issue by joshuaavalon** [mabe02/lanterna#262]
I am using `window.setHints(Collections.singletonList(Window.Hint.FULL_SCREEN));`. I would like my `TextBox` to fill entire row. However, I could not find a solution. Is there any way to do this?

**Comment by avl42** [comment]
if you showed us the piece of code, where you create the textbox and add it
to the window, and where you set up the layout manager, then we could point
out what's missing...

**Comment by joshuaavalon** [comment]
I am just trying the one from example.
```
final Panel inputPanel = new Panel();
new TextBox(new TerminalSize(20,1))
    inputPanel.setLayoutManager(new LinearLayout(Direction.VERTICAL));
    .setValidationPattern(Pattern.compile("[0-9]*"))
    .addTo(inputPanel);
```
I assume that if it is `LinearLayout` or `GridLayout` with 1 column, then it should fill the width. But it does not.

**Comment by avl42** [comment]
you need to call setLayoutData on the textbox(!)  with an argument of
LinearLayout.Alignment.Fill

**Comment by joshuaavalon** [comment]
Thx alot! I hope there will be a complete guide one day.

**Comment by avl42** [comment]
wait, sorry, that was too fast...
the argument is really:
`LinearLayout.createLinearLayoutData(LinearLayout.Alignment.Fill)`

**Comment by joshuaavalon** [comment]
I figured it out myself =]
