### ISSUE TITLE
Consider adding travis support and maven wrapper

### ISSUE THREAD

**Issue by htynkn** [mabe02/lanterna#264]
Hey,

I use lanterna v2 for a long time and I really love this project.

I try to use new v3 and build project in my machine then I notice one test `RedundantThemeDeclarationsTest` failed.

I'm not sure it's really fail for some time or it's because I have wrong maven version. And I see we have similar situation such as #227 before, so I suggest to add [travis](https://travis-ci.org/) support to get a free CI to run all tests for each commit. And if we can have [maven wrapper](https://github.com/takari/maven-wrapper), it will be better.

**Comment by mabe02** [comment]
Not planning to add travis, not enough tests/commits to be worth the hassle. Also I don't quite see the point of maven wrapper?

**Comment by mabe02** [comment]
The broken test is fixed now

**Comment by htynkn** [comment]
thanks very much On 2016-09-04 16:27 , mabe02 Wrote: The broken test is fixed now — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
