### ISSUE TITLE
Pressing enter freezes terminal

### ISSUE THREAD

**Issue by cgameing** [mabe02/lanterna#268]
With the following terminal code, pressing enter freezes terminal.

KeyStroke keyStroke = screen.readInput();

else if (keyStroke.getKeyType() == KeyType.Enter) {
	System.out.println("This never gets called");
}

When you press Enter, the first print command is never called. Freezing the terminal, ocasionally it restarts for whatever reason. But the graphics remains frozen.

**Comment by avl42** [comment]
first qestion would be, what type of lanterna's terminal you're working on
(swing/war, unix, telnet,...)

second is, which of lanterna's three layers you use. obviously, you have a
screen, but do you also use gui (windows&components), or just plain screen?

in case of plain screen, then did you initially call startScreen?

in case of gui it is rather unusual to read keys directly.

**Comment by cgameing** [comment]
It occurs with swing, and in the gnome terminal (Default ubuntu (linux) one)

I did screen.startScreen();

And im not sure what you mean by layers, but these are the only things I call from.

terminal = new DefaultTerminalFactory().createTerminal();
screen = new TerminalScreen(terminal);
tGraphics = screen.newTextGraphics();

Other notes:
All other keys work
This occurs with both enters (Left and Right)
It causes the program to hang (I have to manually kill it)

Any other information I can provide?

**Comment by avl42** [comment]
could you run it in eclipse(or any other debugger)?

i'd be curious if it really gets stuck or just puts the terminal into a
strange mode...

other thing: post the complete runnable code.

**Comment by cgameing** [comment]
Working on runnable code, I have eclipse no errors are posted

**Comment by cgameing** [comment]
Heres the source code that replicates the bug.
Sorry its overly complicated, I have a pretty big API, and I made it as small as possible. Also the zip failed to upload, so heres just a copy-paste.

	import java.io.IOException;

	import com.googlecode.lanterna.graphics.TextGraphics;
	import com.googlecode.lanterna.input.KeyStroke;
	import com.googlecode.lanterna.input.KeyType;
	import com.googlecode.lanterna.screen.Screen;
	import com.googlecode.lanterna.screen.TerminalScreen;
	import com.googlecode.lanterna.terminal.DefaultTerminalFactory;
	import com.googlecode.lanterna.terminal.Terminal;
	import com.googlecode.lanterna.terminal.swing.ScrollingSwingTerminal;

	public class mainErrorTest {
	public static Terminal terminal;
	public static Screen screen;
	public static TextGraphics tGraphics;
	public static ScrollingSwingTerminal scrollingTerminal;
	public static String M = "";
	
	public static void main(String args[]) {
		createTerminal();
	}
	
	//Terminal methods
	public static void createTerminal() {
		try {
			terminal = new DefaultTerminalFactory().createTerminal();
			screen = new TerminalScreen(terminal);
			tGraphics = screen.newTextGraphics();
			screen.startScreen();
			screen.clear();
		} catch (IOException e) {
			e.printStackTrace();
		}
		addLine("");
		
		while (M != "exit") { //the main loop
			try {
				screen.refresh(); //Refreshes screen
				render(0, 0, terminal.getTerminalSize().getRows()-3);
				
				getInput(); //calls the method that may have the issues
				
				renderBottomUI();
			} catch (IOException e) {
				e.printStackTrace();
			}
			
		}
	}
	
	//############################################################
	//# The following Lines are where the error occurs i believe #
	//############################################################
	
	public static void getInput() {
		try {
			KeyStroke keyStroke = screen.readInput(); //Gets input
			
			Thread.sleep(5); // Thought this would help but aparently not
			
			if ((keyStroke.getCharacter() != null) && !(keyStroke.getCharacter().equals(null))) { //Makes sure the keyStroke is a character(letter) and not backspace/enter or something
				M = M + keyStroke.getCharacter();
			} else {
				
				if (keyStroke.getKeyType() == KeyType.ArrowRight) { //This does what enter Should do
					addLine(M);
					M = "";
					System.out.println("added line");
					render(0, 0, terminal.getTerminalSize().getRows()-3);
				}
				
				if (keyStroke.getKeyType() == KeyType.Backspace) { //This works fine
					if (M != "") {
						M = M.substring(0, M.length()-1);
					}
				}
				
				if (keyStroke.getKeyType() == KeyType.Enter) { // This failes to work
					addLine(M);
					M = "";
					System.out.println("added line");
					render(0, 0, terminal.getTerminalSize().getRows()-3);
				}
				System.out.println("This should be called after enter"); //This line should be reached after enter is pressed, But its not
			}
		} catch (IOException | InterruptedException e) {
			e.printStackTrace();
		}
	}
	//#######################################################################
	//# Anything after this shoulden't be a issue but its here anyways. . . #
	//#######################################################################
	
	public static String[] lines = new String[1024]; //This stores lines
	public static int startLine = 1; //This is a starting point to draw lines
	
	public static void addLine(String text) { //Adds a line to the array
		if (startLine >= 1024) { 
			startLine = 1;
		}
		System.out.println("changing line " + startLine + " to " + text);
		lines[startLine] = text;
		startLine++;
	}
	
	public static void render(int renderLine, int minHeight, int maxHeight) {
		int renderPoint;
		if (renderLine <= (1024 - startLine)) { //renderLine is less then the boundary
			renderPoint = renderLine;
		} else {
			renderPoint = (1024 - startLine) - renderLine;
		}
		for (int y = maxHeight; y > minHeight; y--) {
			if (lines[renderPoint] != null) draw(0, y, lines[renderPoint]); //If the variable in the array contains something render it
			renderPoint++;
		}
	}
	
	public static void draw(int x, int y, String text) {
		tGraphics.putString(x, y, text); //Easy draw method
	}
	
	public static void renderBottomUI() {
		try {
			draw(1, terminal.getTerminalSize().getRows()-2, "                                                                                  "); //This clears the line
			draw(1, terminal.getTerminalSize().getRows()-2, M); // his replaces it
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
`

**Comment by cgameing** [comment]
I couldn’t upload, a zip so heres a copy paste, I made it as small as possible.

	import java.io.IOException;

	import com.googlecode.lanterna.graphics.TextGraphics;
	import com.googlecode.lanterna.input.KeyStroke;
	import com.googlecode.lanterna.input.KeyType;
	import com.googlecode.lanterna.screen.Screen;
	import com.googlecode.lanterna.screen.TerminalScreen;
	import com.googlecode.lanterna.terminal.DefaultTerminalFactory;
	import com.googlecode.lanterna.terminal.Terminal;
	import com.googlecode.lanterna.terminal.swing.ScrollingSwingTerminal;

	public class mainErrorTest {
	public static Terminal terminal;
	public static Screen screen;
	public static TextGraphics tGraphics;
	public static ScrollingSwingTerminal scrollingTerminal;
	public static String M = "";
	
	public static void main(String args[]) {
		try {
			terminal = new DefaultTerminalFactory().createTerminal();
			screen = new TerminalScreen(terminal);
			tGraphics = screen.newTextGraphics();
			screen.startScreen();
			screen.clear();
			
			while (M != "exit") {
				screen.refresh(); //Refreshes screen
				
				getInput(); //calls the method that may have the issues
				
				renderBottomUI();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	//############################################################
	//# The following Lines are where the error occurs i believe #
	//############################################################
	
	public static void getInput() {
		try {
			KeyStroke keyStroke = screen.readInput(); //Gets input
			
			Thread.sleep(5); // Thought this would help but aparently not
			
			if ((keyStroke.getCharacter() != null) && !(keyStroke.getCharacter().equals(null))) { //Makes sure the keyStroke is a character(letter) and not backspace/enter or something
				M = M + keyStroke.getCharacter();
				tGraphics.putString(0, terminal.getTerminalSize().getRows()-5, "           ");
			} else {
				
				if (keyStroke.getKeyType() == KeyType.ArrowRight) { //This does what enter Should do
					tGraphics.putString(0, terminal.getTerminalSize().getRows()-5, "Enter!");
					M = "";
				}
				
				if (keyStroke.getKeyType() == KeyType.Backspace) { //This works fine
					if (M != "") {
						M = M.substring(0, M.length()-1);
					}
				}
				
				if (keyStroke.getKeyType() == KeyType.Enter) { // This failes to work
					tGraphics.putString(0, terminal.getTerminalSize().getRows()-5, "Enter!");
					M = "";
				}
				System.out.println("This should be called after enter"); //This line should be reached after enter is pressed, But its not
			}
		} catch (IOException | InterruptedException e) {
			e.printStackTrace();
		}
	}
	//#######################################################################
	//# Anything after this shoulden't be a issue but its here anyways. . . #
	//#######################################################################
	
	public static void renderBottomUI() {
		try {
			tGraphics.putString(1, terminal.getTerminalSize().getRows()-2, "                                                                                  "); //This clears the line
			tGraphics.putString(1, terminal.getTerminalSize().getRows()-2, M); // his replaces it
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}

**Comment by cgameing** [comment]
Updating java fixes the issue, so its not a bug.

**Comment by avl42** [comment]
Could you please (for the record) tell us which exact java version didn't
work?

**Comment by cgameing** [comment]
Im sorry but not sure what version I came from, but the latest java 8 seems to work
Also more specificity Java 8 reports a error, where java 7 didn’t,  Im fairly sure this wasn’t lanternas fault. Im sorry for any inconvenience I may have caused.

**Comment by avl42** [comment]
Lanterna is meant to work with any Java down to 6.  Some of my past PRs
accidentally contained Java7-isms, and they were fixed for compatibility
with 6.

So, if you could find some old logs revealing the previous java version,
that would be very appreciated. Was it oracle java, or a different vendor,
like ibm or openjdk?
