### ISSUE TITLE
Type mismatch: TerminalScreen to Screen

### ISSUE THREAD

**Issue by bartshomer** [mabe02/lanterna#269]
Hi...i'm currently playing around with beta3 to update my older projects.

Not even the HelloWorld example is running fine.

`// Setup terminal and screen layers
 Terminal terminal = new DefaultTerminalFactory().createTerminal();
 Screen screen = new TerminalScreen(terminal);
 screen.startScreen();`

results in: Type mismatch: cannot convert from TerminalScreen to Screen

i've been using the exact code of 
[example code](https://github.com/mabe02/lanterna/blob/master/docs/examples/gui/hello_world.md)

Many thanks for your help

**Comment by avl42** [comment]
maybe, you have a local/nested/inner class named "Screen" within your class
or package, and the java compiler picks that instead of lanterna's Screen
...

Just guessing.  I don't suppose, the exact HelloWorld also fails for you,
or does it?
