### ISSUE TITLE
Polling more than one key stroke at the same time: possible?

### ISSUE THREAD

**Issue by fabioticconi** [mabe02/lanterna#276]
I'm using the Screen layer for a simple ASCII roguelike, and wanted to implement some diagonal, continuous movement by having two arrows pressed at the same time.

Below you can see my basic setup. The game itself is drawn at each frame using `graphics.setCharacter()`, and I check the user input with `screen.pollInput()`. I'm on Linux, and using the latest release (beta3).

Now, if I keep, say, the arrow down key pressed, then I will keep polling ArrowDown events without trouble. If, however, I keep the arrow down pressed and also the arrow left pressed, I will only be polling the ArrowLeft events.

I'm not at all experienced with GUIs and games, so maybe this is how it's supposed to work and I need to write code to handle what I want (ie, recognising when both keys are pressed, not only one). Any advice/input in this direction would be greatly appreciated.

```
Terminal                  terminal;
Screen                    screen;
TextGraphics           graphics;
try
{
    final DefaultTerminalFactory factory = new DefaultTerminalFactory();
    factory.setInitialTerminalSize(new TerminalSize(size_x, size_y));
    factory.setTerminalEmulatorFontConfiguration(AWTTerminalFontConfiguration.newInstance(Options.FONT));
    terminal = factory.createTerminal();
    terminal.setCursorVisible(false);
    terminal.addResizeListener(new SimpleTerminalResizeListener(terminal.getTerminalSize()));
    screen = new TerminalScreen(terminal);

    screen.doResizeIfNecessary();

    screen.startScreen();
    screen.clear();

} catch (final IOException e)
{
    e.printStackTrace();

    throw new RuntimeException("failed rendering");
}

graphics = screen.newTextGraphics();
```

**Comment by mabe02** [comment]
Hi @fabioticconi 
I don't think reading two keys at the same time is possible when using standard input on a real terminal. For example, if you open a shell, hold one key down so it starts repeating, then hold a second key down, you'll see that only the second key will start to repeat. If you release the second key, while having held down the first key the whole time, all output stops.

Of course in the AWT/Swing terminal emulators bundled with lanterna, it's possible to hack them to listen for multiple simultaneous key presses and interleave them in the input queue, but I'm not sure it's a good idea to add functionality that deviates from what we are trying to emulate.

If you're only even going to run your program in the bundles emulators, I'd recommend you get hold of the underlying Frame/JFrame and register your own key listeners. If you are going to run it on a real terminal, you're probably looking at using jna/jni and hook into native code to get better access to the keyboard than what standard input will serve you with.

**Comment by fabioticconi** [comment]
Hi @mabe02,

I see. It doesn't look like I can easily get the Frame though, right? Maybe I overlooked some parts of the code. I shall dig deeper. Thanks for your input!

**Comment by mabe02** [comment]
Actually, SwingTerminalFrame and AWTTerminalFrame both extends JFrame and Frame respectively. Check the type of your terminal implementation, if you are using the terminal emulators bundled in lanterna, it's probably one of them.
