### ISSUE TITLE
Swing Terminal Emulator and startScreen() and stopScreen()

### ISSUE THREAD

**Issue by rednoah** [mabe02/lanterna#289]
I have a batch processing app that occasionally switches into interactive mode for a few selections using lanterna (which works amazingly well) and it's using `startScreen()` and `stopScreen()` to turn the lanterna UI on and off as it processing things.

In the console this works great. However, when testing, the Swing Terminal Emulator seems to shut down when `stopScreen()` is called so subsequent startScreen calls won't work. Ideally `startScreen()` and `stopScreen()` would just hide and show the terminal emulator kind like what's happening in the console.

**Comment by avl42** [comment]
Just a quick reply.  What you need is supported and there is a method in
the DefaultTerminalFactory to define closing behaviours. One of them is
close on exit private mode and is default, another one is close on escape
key. what you seem to want is passing null to a method (haven't got the
name at hand right now) so as to unset them both, or to explicitly set(not
add) the exit on Escape flag if you want it.

If you browse the test hierarchy on github (or if you've checked out the
whole git repository, then there are two samples that do it. (They use a
TestTerminalFactory, but that is now merely a subclass of the
DefaultTerminalFactory.)

On Sat, Nov 26, 2016 at 5:55 AM, Reinhard Pointner <notifications@github.com

**Comment by rednoah** [comment]
Alright, `TerminalEmulatorAutoCloseTrigger.CloseOnEscape` keeps the window from closing. That's good enough for testing.
