### ISSUE TITLE
The table control could use a scroll bar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#29]
```
Currently when the table cannot accomodate all rows in the screen I am seeing 
an exception similar to the one when adding a checkbox to a table fails. It 
would be useful if the table supported a scroll bar to run through the entries.
```

Original issue reported on code.google.com by `m.vino...@gmail.com` on 30 Jul 2012 at 5:36

**Comment by mabe02** [comment]
I'll tackle this one today; trying to get the Table class into good shape and make it use a scroll bar.

**Comment by mabe02** [comment]
Ok, finally! This took a lot longer than I expected. The table class should now be able to do all discussed above.
