### ISSUE TITLE
Unix console is flooded with characters when in mouse capture mode

### ISSUE THREAD

**Issue by czyzby** [mabe02/lanterna#293]
When I set mouse capture mode to `CLICK_RELEASE_DRAG_MOVE`, the console is basically flooded after application exit:

```
CC!CD!CD"CE#CF$CG%CH%CI%CK&CL&CM'CN'CO'CP'CP'CP'CP'CP'CO'CN'CL'CI'CF'CC'CA(C>(C<)C:*C8+C7+C6,C5-C5-C5.C6/C6/C60C70C81C81C91C91C91C91C91C90C8/C7.C5-C3+C1*C.(C+'C)&C(%C'%C&%C&%C&%C&%C&%C'%C*%C-&C0&C4'C8(C;)C?*CB+CE+CH,CJ-CL-CM-CN-CO-CO-CO-CO-CN-CM,CK,CI+CG+CF+CD*CC*CA*C@*C?*C>*C=+C<+C<+C<+C<+C<+C<+ <+@<+@<+@<+@<+@<+@<+@=,@=,@=,@?,@@-@B-@D.@F.@H.@J.@L/@N/@O.@P.@Q.@Q.@Q-@R-@R-@Q,@Q,@Q+@P+@O*@O*@N*@M*@L*@L*@L*@K*@J*@I*@I*@H*@G+@F+@E+@D+@D,@C,@C,@B,@B,@B,@B,@B,@C,@C,#C,CD,CE,CF+CG+CH+CJ+CK+CL+CM+CN+CN+CN, N,@N,@N,@M,@M+@L+@J+@H+@F+@C+@A+@?+@=+@;+@9+@8+@7+@6+@6+#6+C6+C6+C6+C7+C8+C9+C:+C;+C<,C>,C?,C@,CB,CC,CD,CE-CF-CG-CG-CG-CG- G-@H-@H-@H-@H-@I-@I-@J-@J-@K-@L-@M-@N-@O-@P-@Q-@S-@T,@U,@V,@W,@X,@X,@X,@X,@X,@X,@X,@W,@W,@W+@W+@W+@V+@V+@V+@U+#U+CU+CU+CT+CT+CT+CS+CS+CR+CQ+CP+CP+CO+CN,CM,CM, M,@L,@K,@K,@J,@J,@J-@J-@J-@I-@I-@I-@I-@I.@J.@K/@K/#K/CL0CM0CN0CO1CQ1CR1CS1CT1CU1CU1CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CV0CU0CU0CU0CU0CU/CU/CT/CT/CT/CT/CT/CU/CU/CU/CU/CU.CU.CV.CV.CV-CU-CU,CU,CT+CS+CR*CQ)CP)CO(CN(CN(CM(CL(CL(CL(CL(CK(CK(CK)CJ)CJ*CJ* J*@J+@J+@K,@K,@K-@L-@M-@M.@N.@N.@O.@O.@P.@P.@Q.#Q.CQ-CR-CR-CS,CS,CS+CS+CS+CS+CS+CS*CS*CS*CS*CS*CR*CQ) Q)@Q)@P)@O)@N)@N)@M)@M)@L)@L)@L)@L)@L)@L)@L)@L)@L)@L)#L)CL)CL)CL)CL)CL)CK)CK)CK*CK*CJ*CI*CH*CG*CF+CD+CC+CB,CB,CA,CA,C@,C@,C@-C@-C@,CA,CA,CA,CA,CA,CA,CA,CA,CA,CA,CA,CA,CB,CB,CB,CB,CB,CB,CC+CC+CC+CC+CC+CC+CC+CC+CC*CC*CC*CC*CC)CC)CC)CC)CC)CB(CB(CB(CB(CA(CA(CA'C@'C@'C@'C?'C?'C?'C?'C?'C?'C?'C?'C?'C?'C?'C?'C?'C?(C@(C@(C@(C@(C@( @(#@(C@(C@(C@(C@(C@(C@(C@(C@(C@(C@(C@)C@)C@)C@)C@)C@)C@)CA)CA)CA*CA*CA*CA*CA*CB+CB+CB+CB+CC,CC,CC,CC,CC,CC,CD-CD-CD-CD- D-@D-@D-@C-@C-@C-@B-@A-@@-@>-@<-@;-@9-@7-@5-@3-@2-@1-@0-@/-@/-@/-#/-C/-C/-C/-C/-C/-C.-C.-C.-C.,C.,C.,C.,C.,C-,C-,C-,C-,C-,C-+C,+C,+C,+C,+C,+C,+C,+C,*C,*C,*C,*C,*C,*C,*C,*C,*C,)C,)C,)C,)C,)C,)C,)C,)C,)C-)C.)C/(C/(C1(C2(C3(C4(C6(C7(C9(C:'C<'C='C?'C@'CA'CB'CC'CD'CE&CE&CF&CF&CF&CF&CF&CG&CG&CG&CG&CG&CH&CH&CH&CH&CH&CH&CI'CI'CJ(CK(CL)CN*CO+CP,CR-CS.CT/CV0CW1CX2CY2CZ3CZ3C[4C[4C[4C[4C[4C[4C[4C[4C\4C\4C\4C]4C]4C]3C^3C^3C_3C_3C`3C`2Ca2Ca2Cb1Cb1Cc1Cc0Cd0Cd/Ce.Ce.Cf-Cf,Cf,Cf+Cf+Cg*Cg*Cg*Cg)Cg)Cg(Cg(Cg(Cg(Cf'Cf'Cf'Cf'Cf'Cf'Cf'Cf'Ce'Ce'Cd'Cc'Cb&Ca&C`&C^&
```
The output seems to vary from terminal to terminal, but my guess is these are actually "key codes" of mouse events received throughout the application lifetime. And, frankly, there might be a lot of these.

What's interesting, all mouse events cause printing these characters even *after* the application is terminated if you don't do this: `((UnixTerminal) terminal).setMouseCaptureMode(null)`.

I know that mouse events support is experimental, but it would be nice if you could automatically clear mouse capture mode (with `Terminal#close()` or similar method) and if the console, well, would not be flooded at all.

**Comment by avl42** [comment]
I recently (well, It was already last year ;-) )  PR'ed a change for that
and Martin accepted it, but it's not yet in a release.  Try checking out
latest version from github. It should no longer require unsetting
mouse-mode from user code, but instead the mouse mode is auto-reset on
exiting private mode.  Test and report back, please.

**Comment by czyzby** [comment]
I've tried the master branch and you no longer have to manually clear mouse capture mode. The console was flooded with characters as I was not polling the input - I guess this issue can be marked as resolved, unless you want to keep it around until the next release.

**Comment by avl42** [comment]
If it were just the events from during actual mouse-mode that your app didn't consume, then I 'd suggest you to close it.

If your app got terminated (by anything else than kill -9) and the terminal keeps spewing out characters for mouse moves, only then please leave it open and report what exactly happened to the app.

**Comment by czyzby** [comment]
```
If your app got terminated (by anything else than kill -9) and the terminal keeps spewing out characters for mouse moves, only then please leave it open and report what exactly happened to the app.
```
That exactly what happened *before* I switched to the master branch. I guess I'll wait for the next release, thanks.
