### ISSUE TITLE
Lanterna for web (html)

### ISSUE THREAD

**Issue by adam-arold** [mabe02/lanterna#294]
Is it possible to use Lanterna on a web application (html/css/js)? Or is there an alternative to Lanterna for the web?

**Comment by avl42** [comment]
I've heard of terminal-emulators and ssh-clients written in JavaScript,
which could allow you to connect to a server and run lanterna apps.

**Comment by mabe02** [comment]
Yeah, this is for java applications running on your computer. Web integration is way out of scope.
