### ISSUE TITLE
Swing terminal should support mouse capture

### ISSUE THREAD

**Issue by HaasJona** [mabe02/lanterna#302]
Lanterna seems to be unable to listen to mouse events from the Swing terminal, which is unfortunate as it makes testing from IDEs more difficult. Attaching a mouse listener to the JFrame should be relatively easy.

**Comment by mabe02** [comment]
What kind of mouse capture are you referring to here? Just being able to register a mouse listener on SwingTerminalFrame/AWTTerminalFrame?

**Comment by HaasJona** [comment]
Mainly I want to be able to focus / activate controls like text fields by using the mouse like I can do with the telnet or native Unix terminal.

**Comment by mabe02** [comment]
I'm still not quite sure what you are referring to... Is this using the text-based GUI controls built-into lanterna? Or just highlighting text in the terminal emulator to copy?

**Comment by HaasJona** [comment]
On the telnet or native terminal you can focus controls like text fields or
action buttons using the mouse (if you configure it appropriately). On the
swing terminal you can't.

Additional features like selecting text with the mouse probably would be
nice but that's not what I mean.

Am 15.04.2017 6:42 vorm. schrieb "mabe02" <notifications@github.com>:

**Comment by jbergenthal2** [comment]
I tried what would seem to be a simple solution to set the cursor on mouse click. This however turned out to be impossible as the AWTTerminal/SwingTerminal is very stingy giving access to its internal implementation.
In the client class, a MouseAdapter listens to mouse clicks:
`	@Override
	public void mouseClicked(MouseEvent e) {
		SwingTerminal swingTerminal = (SwingTerminal)e.getSource();
		swingTerminal.setCursorPositionPixels(e.getX(), e.getY());

	}
`
And then I had to modify the SwingTerminal class (could not think of another way of doing this):
public void setCursorPositionPixels(int x, int y) {
	setCursorPosition(x / terminalImplementation.getFontWidth(), y / terminalImplementation.getFontHeight());
}

**Comment by mabe02** [comment]
I'm not sure that's really what you want to do, instead you'd want to generate an input event (KeyType.MouseEvent) and put it on the input queue. The code doesn't move the terminal cursor itself, rather it sees the mouse event, figures out where you clicked, figures out if there is any interactable component at this location and then moves focus to there. Depending on how the component works, it may move the terminal cursor too.

**Comment by jbergenthal2** [comment]
Right. In order to do that, and in a more general way, shouldn't the swing terminal implement the ExtendedTerminal methods? I can see all of those methods would be very useful from a swing programming point of view.

**Comment by mabe02** [comment]
Well, some of them might not always fit (for example the minimize method on an embedded terminal). But yeah, I think most can be done, if the time and effort is put down to implement them.

Reviewing the code again, I see that there's actually no way to put 'synthetic' events on the input queue, so you wouldn't be able to pass down a mouse click you captured outside of lanterna anyway. Let me see if I can come up with some easy way to do that.

**Comment by mabe02** [comment]
Okay, I've added a couple of methods to inject custom input events; it's not quite ideal, I think it would be better to have the Swing/AWT interfaces extend from VirtualTerminal, but as that interface looks now it would be somewhat messy and I don't want to go there for a 3.0.x release.
