### ISSUE TITLE
Tutorial 2 and 3 links in the docs section do not work

### ISSUE THREAD

**Issue by srrobinson** [mabe02/lanterna#307]
The links to tutorial 2 and 3 point to non-existent files. Not sure if these were here at one time, couldn't seem to find them in other branches.  Would like to have them available if they are written/ready for publishing.

**Comment by t0r0X** [comment]
@srrobinson Tutorials 2 and 3 have been updated about a month ago, please could you take a look at the current version, maybe the issue is solved.

**Comment by srrobinson** [comment]
Fixed, thank you.
