### ISSUE TITLE
SameTextGUIThread.invokeAndWait() runs callback twice

### ISSUE THREAD

**Issue by haku** [mabe02/lanterna#310]
I think SameTextGUIThread.invokeAndWait() is supposed to return after calling `runnable.run()`.
Instead it invokes the runnable once itself and then calls the super class that invokes it again.
I think you can just remove invokeAndWait() from SameTextGUIThread and always let the super class handle it.

**Comment by mabe02** [comment]
You are absolutely correct, I've pushed a fix for this
