### ISSUE TITLE
TextGUIGraphics should not be final , preventing extensions

### ISSUE THREAD

**Issue by evansdom** [mabe02/lanterna#311]
I need to extend TextGUIGraphics in order to override setCharacter() 

I am using a TextBox, multi-line, and wish to markup certain characters (e.g. highlight mouse-clicked words).

Unless there is another way I may achieve this that I am missing?

Regards.

**Comment by mabe02** [comment]
Reviewing this code now, I'm not entirely sure why TextGUIGraphics is a class at all; it should obviously have been an interface. I'm guessing you are extending from TextBox and want to pass a modified TextGUIGraphics to the draw method?

**Comment by evansdom** [comment]
Hi,

Thanks for looking t this.  Yes, exactly correct.

I made do with postRenderer callback, but have to iterate through all
components to find what I need - it works fine but is a bit procedural .

Thoroughly appreciate lanterna BTW, been looking for something like this
for  a long time.

BTW, I have extended to support xterm extended mouse tracking .  i chose
2005 , though both it and 2015 are awkward  .  If you are interested I
would be happy to provide you with it.

**Comment by mabe02** [comment]
I have now branched release/3.0 which will be where I release 3.0.0 from, on master I've advanced the version to 3.1.0-SNAPSHOT and I've changed TextGUIGraphics to an interface there.

**Comment by avl42** [comment]
just wondering, if removing the "final" would still be acceptable for 3.0.*
...

**Comment by mabe02** [comment]
I suppose we could
