### ISSUE TITLE
Missing last two characters when displaying window title

### ISSUE THREAD

**Issue by ben-dale** [mabe02/lanterna#313]
To replicate:
- Setup a simple window and set a title
- Note that when displayed, the last two characters of the title are missing

<img width="632" alt="screen shot 2017-07-01 at 23 24 01" src="https://user-images.githubusercontent.com/8825200/27765813-651fcdb6-5eb4-11e7-8cbc-f46666f196ff.png">

```java
Terminal terminal = new DefaultTerminalFactory().createTerminal();
Screen screen = new TerminalScreen(terminal);
screen.startScreen();

BasicWindow window = new BasicWindow();
window.setTitle("Hello World");

MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
gui.addWindowAndWait(window);
```

Initially I thought this was because the default window size was cutting off the title at a certain point, however, I tried with a longer string and noticed the same behaviour:

```
Hello World World World World
```
<img width="634" alt="screen shot 2017-07-01 at 23 29 38" src="https://user-images.githubusercontent.com/8825200/27765830-2de045d2-5eb5-11e7-969d-8c50b8c61dab.png">

**Comment by Janrupf** [comment]
Usually you add components to the window. If there components that are longer then the current length this problem fixes itself.

**Comment by mabe02** [comment]
Could be a theme thing, I'll take a look

**Comment by mabe02** [comment]
Yeah, this is an older bug for when I was re-working the theme system. I've fixed it now.
