### ISSUE TITLE
Permission to use MIT as license for a (partial) Kotlin port of this project.

### ISSUE THREAD

**Issue by adam-arold** [mabe02/lanterna#314]
Hi. I'm working on an [ASCII display library for game developers](https://github.com/Hexworks/zircon) and I've ported parts of the codebase of this project to Kotlin in the process. I'm not sure how LGPL applies here so I'd like to ask for a written permission to use MIT as license in my library.
Thanks!

**Comment by icryan** [comment]
+1 to this, LGPL is a problem if you want to actually use this library in anything other than a private personal project. MIT would be better.

**Comment by zilti** [comment]
How so? The LGPL is exactly made for being able to use an LGPL-library in a project licensed under whatever other license, closed ones included?

**Comment by adam-arold** [comment]
This is not that simple. I'm not a lawyer but LGPL is problematic from a licensing perspective for Java projects ([see here](https://www.gnu.org/licenses/lgpl-java.en.html)). By using Lanterna in any program you create a *derivative work* and you have to go thorugh hoops to comply with LGPL. I don't want my users to be bothered with stuff like this. My work is not linking to Lanterna because it is a Kotlin port of sorts so I needn't comply with it but as I said before I'm not a lawyer that's why I ask here for a written permission.

**Comment by mabe02** [comment]
So if I get this right, LGPL is problematic for you because you have ported over Lanterna from Java to Kotlin, which isn't linking to the library but rather modifying it?

**Comment by adam-arold** [comment]
No, *LGPL* is problematic for my future users who might want to use the lib in a project and I'd like to use *MIT* instead.

I've read through the license texts and it is not clear for me whether I **have to** use *LGPL* (and ask for a permission to use a different license) or not. That's why I felt it was simpler to just ask here and let you decide.

For my project I looked at the source of Lanterna and ported parts of it (`input`, `terminal`, `graphics` and `screen` packages) to Kotlin. I also did some heavy rewriting but the functionality is similar. The main difference is that I only support virtual terminals (Swing currently) and that I'll write my own component framework (I did not port the `gui2` packages).

Nevertheless Lanterna is an impressive project and the code quality is superb. My hats off to you!

**Comment by mabe02** [comment]
Okay, let's do this. Let me know (either here or by email) when you've got all the ported code from lanterna that you'll use in place and I'll give you MIT license permission for that code set. 
As for this library, I'm not planning to re-license it anytime in the near future.

**Comment by adam-arold** [comment]
Okay. I've got the ported code under this tag: [2017.1.0-RELEASE](https://github.com/Hexworks/zircon/tree/2017.1.0-RELEASE).
I can modify it if needed or you can add a PR to the `master` branch.

**Comment by mabe02** [comment]
Sorry (one month later) I'm not sure what you need me to do? I should create a PR over on your project for 2017.1.0-RELEASE to master?

**Comment by adam-arold** [comment]
No problem. I don't think you need to do anything, this issue can serve as a documentary. I've added a notice to the [`README.md`](https://github.com/Hexworks/zircon/blob/master/README.md) to state that parts were ported from Lanterna. I'm not a lawyer so I don't know what else needs to be done but my guess is that we are done here.

**Comment by mabe02** [comment]
Okay, I'm not a lawyer either, let's say it's good like that.

**Comment by adam-arold** [comment]
Thanks again!
