### ISSUE TITLE
Terminal loses focus on MacOSX

### ISSUE THREAD

**Issue by bartitsu59** [mabe02/lanterna#319]
Hi,

When launched on MacOSX, an application that uses a lanterna terminal sets the focus on the minimized java task icon, not on the terminal itself.
You then need to click back on the terminal window to regain control of it.
It's annoying for keyboard only applications (I'm using lanterna for programs generated by a Basic compiler I wrote).
On Linux and windows, the focus is correctly set, respectively, on the Linux Terminal and on the SwingTerminal.
That said, I'm unsure on whether it is due to lanterna itself, or in the way java applications are launched on OSX.

Thanks,

**Comment by Janrupf** [comment]
I think (I'm not an lanterna developer) its Java it self cause as I see, lanterna isn't using natives for OSX.

**Comment by avl42** [comment]
I'm a bit confused now as to whether the app is running directly in the
terminal, or just started from the terminal (and displaying its own Swing
window with the textgui), or if java opened some window on its own, but the
textgui running inside the terminal app...

What exactly is the "minimized java task icon", and after what action
(keyboard or mouse interaction, or from your java code, or initial startup
of the application) does the wrong thing get focus?

bartitsu59, please clarify.

**Comment by bartitsu59** [comment]
Hi,

I'm launching my app from an OSX Terminal window, from the command line.
No SwingTerminal is involved since the OSX Terminal is seen as a valid UnixTerminal.
I just found this post explaining my situation and proposing a solution :
https://stackoverflow.com/questions/8911748/how-can-i-prevent-command-line-java-processes-from-stealing-focus-in-osx

So janrupf was right : it's a common behaviour for java apps on OSX and it can be solved by adding the following runtime option "-Djava.awt.headless=true".

Thanks for your help sorting this out, I will close this issue.
