### ISSUE TITLE
how i can switch between Windows ?

### ISSUE THREAD

**Issue by WhiteDruid** [mabe02/lanterna#320]
i  am newbie pls help me , how i can switch between windows ? 
like : if we clicked on a button the app goes to another window ?
thank you

**Comment by avl42** [comment]
check the MultiWindowTextGUI

it has methods to retrieve all windows, and to set a window active.

tying it to button clicks would be left to you to do as you need it. e.g.
you could create a "taskbar" at the bottom...


Am 25.07.2017 09:59 schrieb "WhiteDruid" <notifications@github.com>:

**Comment by WhiteDruid** [comment]
how define TextGUI.Listener ?

**Comment by avl42** [comment]
Not sure I understand the question correctly, as it seems so simple...
maybe i'm missing some specific aspect of it...

you create some new class that 'implements' the said interface and thus
also the method onUnhandledKeyStroke to do whatever you want done -
probably checking if the keystroke is some specific key/mouseaction and
only for those do something...

then you create an instance (new ...) of your class and pass that instance
to the textgui's addListener method.

**Comment by WhiteDruid** [comment]
i got what you said . 
i have a Table and a Button . 
i want when the user clicked the button . 
the app goes to another place and show table . 
like method showDialogMessage .

and thank you sir for helping me

**Comment by Janrupf** [comment]
Thats easy, 
```java
Button b = new Button("Label", new Runnable(
  @Override
  public void run(){
    System.out.println("Clicked!");
    MessageDialog.showMessageDialog(MultiWindowTextGui:<your text gui>,String: <title>,String<message>);
}));
```
Just look at the docs, there really helpfull ;)
