### ISSUE TITLE
New RC release?

### ISSUE THREAD

**Issue by MartyIX** [mabe02/lanterna#323]
Hi,

would it be possible to release new RC version of Lanterna 3? It seems to contain various bugfixes. I would like to test it in my project.

Regards,
Martin

**Comment by mabe02** [comment]
Yeah, I'm out on vacation now so I don't have my keys needed to deploy to Sonatype. I'll probably do a 3.0.0 final release when I get home on Monday, we can't keep doing RC:s forever.

**Comment by MartyIX** [comment]
Thank you :-)
