### ISSUE TITLE
ComboBox - setDefaultValue

### ISSUE THREAD

**Issue by MartyIX** [mabe02/lanterna#325]
Hi,

I tried to change default value for my ComboBox and I had to do it as follows:

            for (i in 0 until comboBox.itemCount - 1) {
                val item = comboBox.getItem(i)

                if (item.equals(value)) { // comboBox value is equal to my value
                    comboBox.selectedIndex = i
                }
            }

Maybe it is a good idea to add a helper method that does something similar for convenience.

Regards,
Martin

**Comment by avl42** [comment]
What would be a sensible thing to do if the value does not exist in the
list?

Your snippet seems to imply: leave previous default untouched.
An alternative could be:  adding the item to the list.
(I don't know if there is even a need for the item to be present in the
list.)

**Comment by MartyIX** [comment]
This behavior seems reasonable to me: https://docs.oracle.com/javase/7/docs/api/javax/swing/JComboBox.html#setSelectedItem(java.lang.Object)

**Comment by mabe02** [comment]
See if a07f8611a5723c9871cc072560c29a125dc9ecd6 has what you need

**Comment by MartyIX** [comment]
It look great! Thank you :-)
