### ISSUE TITLE
Resizing SwingTerminalFrame wont grow the terminal

### ISSUE THREAD

**Issue by klaushauschild1984** [mabe02/lanterna#326]
I have a project using the SwingTerminal. All other terminals are out of scope.

The nice thing about the SwingTerminal is: the user can resize it. But it does not behave I am expecting. When I shrink the SwingTerminalFrame the size of the embedded SwingTermin will also decreased. But growing the SwingTerminalFrame resizes the embedded SwingTerminals size just to the initial given size of the terminal.
Is there a way to make the terminal bigger than initial? As a recap all other terminal backends and there problems with those behaviors are out of scope.

Thanks

**Comment by mabe02** [comment]
I just tried with one of the tests that's using SwingTerminalFrame and I could resize it freely to both smaller and bigger with the embedded SwingTerminal following in size.
The SwingTerminalFrame class extends from JFrame and sets a BorderLayout JPanel with the SwingTerminal as it's center component. If the embedded SwingTerminal doesn't extend beyond its initial size when making it bigger, it almost sounds like Swing isn't resizing the component properly?

**Comment by klaushauschild1984** [comment]
Maybe. But I noticed that the TerminalSize wouldn't exceed its initial size. I will try a seperate test for this scenario to eliminate side effect from my actual project.

**Comment by klaushauschild1984** [comment]
I opened a PR to show a minimal example of my situation.

There is no problem with the resizing. After writing the I found a terminal initialization issue in my project. Actual there was another Screen over the one SwingTerminals one. This was not properly resized. After fixing this there is no problem anymore.

You can merge the PR or dicard it. Nothing fancy there. Just to show my use case.
