### ISSUE TITLE
Minimal width for columns in tables

### ISSUE THREAD

**Issue by MartyIX** [mabe02/lanterna#330]
Hi,

is it possible to set that a column in table has some minimal width?

I resorted to doing this:

```
table.tableModel.setCell(0, rowIndex, Strings.padEnd(name, 40, ' '));  // minimal width of this cell should be 40 characters
table.tableModel.setCell(1, rowIndex, Strings.padEnd(category, 20, ' '));
table.tableModel.setCell(2, rowIndex, Strings.padEnd(price, 10, ' '));
```

as a quick fix. Yet, I would be more happier to do it cleanly.

Best regards,
Martin

**Comment by mabe02** [comment]
You can set a custom TableCellRenderer (easiest to extend from DefaultTableCellRenderer and modify getPreferredSize(..), which is called on every cell when the size is calculated)

**Comment by MartyIX** [comment]
Thank you. It seems like a good solution ;-)
