### ISSUE TITLE
readInput on Terminal from TelnetTerminalServer returns immediate EOF

### ISSUE THREAD

**Issue by ljosa** [mabe02/lanterna#332]
Thanks for Lanterna! I'm trying to use it as a telnet server, and I'm running into an issue that I think may be a problem with Lanterna.

**Version**: `[com.googlecode.lanterna/lanterna "3.0.0"]` (jar from Maven)

**Code that demonstrates the problem:**

```java
import com.googlecode.lanterna.terminal.*;
import com.googlecode.lanterna.terminal.ansi.*;

class DemoTelnet {
     public static void main(String args[]) throws java.io.IOException {
          TelnetTerminalServer server = new TelnetTerminalServer(8050);
          Terminal t = server.acceptConnection();
          System.out.println(t.readInput().toString());
          t.close();
     }
}
```

**Directions to reproduce:**

1. Start server with the code above.

2. `telnet localhost 8050`

**Expected behavior:** wait for the telnet user to press a key, then close the connection.

**Observed behavior**: closes the connection immediately, without waiting. The program prints `KeyStroke{keytype=EOF}`.

**Notes**

The following code, which is similar but uses `DefaultTerminalFactory`, works as expected in a terminal on macOS (where the factory returns a UnixTerminal).

```java
import com.googlecode.lanterna.terminal.*;

class DemoText {
     public static void main(String args[]) throws java.io.IOException {
          Terminal t = new DefaultTerminalFactory().createTerminal();
          System.out.println(t.readInput().toString());
          t.close();
     }
}
```

**Comment by avl42** [comment]
This is also reproducible on Linux, and the problem is, that
TelnetClientIACFilterer (nested within TelnetTerminal) doesn't do a proper
blocking read() - instead, if no input is available then it just returns -1
rather than wait for input.

Btw., this problem doesn't show in the TelnetTerminalTest, because that
test only does non-blocking reads.

Good catch!
