### ISSUE TITLE
Adding all empty strings to GridLayout causes infinite loop

### ISSUE THREAD

**Issue by crosscontrol** [mabe02/lanterna#334]
I'm using Lanterna 3.0.0.

I created a [GridLayout](https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/gui2/GridLayout.java) and added (as place holders) multiple labels with empty strings (""). When you do this, [GridLayout](https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/gui2/GridLayout.java) constantly returns early from the [doLayout function](https://github.com/mabe02/lanterna/blob/a226ed3b38073b00fbd516902c05714a0da715dc/src/main/java/com/googlecode/lanterna/gui2/GridLayout.java#L400) due to the following block of code:

`if(area.equals(TerminalSize.ZERO) ||
                table.length == 0 ||
                area.getColumns() <= leftMarginSize + rightMarginSize + ((table[0].length - 1) * horizontalSpacing) ||
                area.getRows() <= bottomMarginSize + topMarginSize + ((table.length - 1) * verticalSpacing)) {
            return;
        }`

the bit that is returning true is:
`area.getColumns() <= leftMarginSize + rightMarginSize + ((table[0].length - 1) * horizontalSpacing)`

When this happens it causes an infinite loop of trying to update the display because `this.changed = false;` never gets set.

The temporary workaround for this is to make at least one of the Label strings in the GridLayout not empty (e.g. a blank space: " ").

**Comment by mabe02** [comment]
It wasn't quite as easy as I thought to reproduce but I eventually got it. Have pushed a fix to release/3.0 and master branches.
