### ISSUE TITLE
setVisibleRow/Column in Table

### ISSUE THREAD

**Issue by BrunoEberhard** [mabe02/lanterna#344]
I think the visible rows / columns concept in the table is broken. I want simply to display the table as many rows as possible. I don't want to set setVisibleRows. As a workaround in my application I override the sitzSize method:

```@Override
    public synchronized Table<String> setSize(TerminalSize size) {
    	setVisibleRows(size.getRows() - 1);
    	return super.setSize(size);
    }
```

But that doesn't handle the left right scrolling. Also I think in the current implementation there might be a confusion between character columns and table columns.

**Comment by KyuBlade** [comment]
Yes, visibleRows is never set.
I fixed it by providing a custom DefaultTableRenderer to the table overriding the getPreferedSize method to update the visibleRows variable.

`override fun getPreferredSize(table: Table<String>): TerminalSize {
        // Hack to fix scrollbars
        table.visibleRows = Math.min(4, table.tableModel.rowCount)

        return super.getPreferredSize(table)
    }`

**Comment by mabe02** [comment]
Yeah, there isn't any straight-forward way to do this. I haven't looked into the Table code in ages, I think it would require some major changes to allow for this to work out of the box. You can achieve roughly the same by overriding the TableRenderer with a composite class and inspect/compare the component size with the screen size.

**Comment by MartyIX** [comment]
@BrunoEberhard Table was refactored by mabe02 recently.

**Comment by mabe02** [comment]
Yes, on master branch the Table has been reworked to solve some of the layout and sizing problems. Please give it a try.

**Comment by BrunoEberhard** [comment]
Works nicely on the master branch. I could remove the workaround.
PageUp/Down Home/End is also welcome enhancement.
