### ISSUE TITLE
isAltDown not evaluated on MacOs

### ISSUE THREAD

**Issue by upeuker** [mabe02/lanterna#346]
The function does not respect the pressed ALT-key.
It always deliveres false.

The getCharacter()- function delivered the modified value of the key not the plain key value.

The same issue  for isShiftDown

**Comment by avl42** [comment]
I'm wondering, if the "Alt" key on Mac just has a different meaning.  If it
is used to send a completely different character, then the "alt" is already
"consumed" by the OS.  On PCs (at least with some non-US keyboards), there
is an "AltGr" Key, which turns q into @, e into € and m into µ but isn't
visible to the application...

**Comment by upeuker** [comment]
It seem to behave as the AltGr-Key.

**Comment by mabe02** [comment]
There's a test program available to debug this if you have the repository cloned: com.googlecode.lanterna.terminal.InputTest

Try pressing f+<enter> and then <alt>f + <enter> and see if there's any difference in the output. On my side, I see:

> f
> 102 (0x66, b1100110, 'f')
> 10 (0xa, b1010, '<control character>')
> 
> 27 (0x1b, b11011, '<control character>')
> 102 (0x66, b1100110, 'f')
> 10 (0xa, b1010, '<control character>')

So essentially, the terminal adds a 0x1b before the character when ALT key is held down (Windows/Linux). I don't have a Mac to try this on myself.

**Comment by upeuker** [comment]
On Mac it delivers pressing "f" followed by "Enter"

f
102 (0x66, b1100110, 'f')
10 (0xa, b1010, '<control character>')

Pressing Alt+f followed by "Enter"

ƒ
198 (0xc6, b11000110, 'Æ')
146 (0x92, b10010010, '<control character>')
10 (0xa, b1010, '<control character>')

**Comment by DEichEich** [comment]
I am running into the same/similar issue. I tried running [tutorial 1](https://github.com/mabe02/lanterna/blob/master/docs/tutorial/Tutorial01.md) and it produced different results. My setup:
OSX 10.13.2 (High Sierra)
Mid 2014 MacBook Pro
Java 9

Swing Terminal Output:
![screen shot 2018-01-02 at 10 52 34 am](https://user-images.githubusercontent.com/23559402/34489810-a95f8a38-efab-11e7-80ae-e322db5d59a3.png)
Default "Terminal" App:
![screen shot 2018-01-02 at 10 52 08 am 1](https://user-images.githubusercontent.com/23559402/34489824-b66f27f6-efab-11e7-981b-3cd59fa0256b.png)
iTerm2:
![screen shot 2018-01-02 at 10 52 15 am](https://user-images.githubusercontent.com/23559402/34489837-c018fad4-efab-11e7-85fb-d5011f4be2b4.png)

Any help would be appreciated.

**Comment by mabe02** [comment]
> ƒ
>198 (0xc6, b11000110, 'Æ')
>146 (0x92, b10010010, '')
>10 (0xa, b1010, '')

This is interesting. It looks like your Mac terminal translates ALT+F into a completely different character. Seems like it might be impossible to tell from inside Java that this is really an ALT+key stroke as opposed to that character. Wonder why they would break xterm compability in such a way?

**Comment by avl42** [comment]
Fwiw, these two bytes 0xc6 and 0x92  are the utf-8 for a symbol "ƒ", a slanted f.

Apparently, Apple Corp saw more value in being able to enter that character from the keyboard, than in an app being able to safely recognize all Alt-modifed characters...

I suppose we have to live with it, just like we have to live with Ctrl-letter not always being the letter with Ctrl-flag set.

**Comment by mabe02** [comment]
I think so, can't think of anything else to do
