### ISSUE TITLE
Bitmap fonts?

### ISSUE THREAD

**Issue by klaushauschild1984** [mabe02/lanterna#348]
How about this feature:
I'm using lanterna the most with the emulated terminals (Swing/AWT). The actual installed fonts of a system limits the creativity a little bit. It would be nice to have the posibility use a bitmap font instead a TrueType font for these two emulators.

Could this be a feature in the near future?
Or is there a way to hack it into for my special case?

**Comment by avl42** [comment]
Aren't bitmapped fonts a relic of the past? ...of those times where pre-rendering and storing a font for some discrete couple of sizes was still a neccessity?  I don't really have any idea about what support Java provides for such fonts.  If it does support it, then that's one obstacle out of the way.

The other obstacle then would be Lanterna's current internal bookkeeping of font size.  Setting a different font would for example require making sure that this change doesn't happen while a redraw is in progress, and apart from that, that the Swing/AWT implementation gets into a consistent state based on that new font.  It might need some public setFont(Font ...) method, that either does all necessary locking or just sets the new font in a volatile field to be picked up, measured and adopted lateron synchronously.

Maybe you can experiment a bit along these lines, or along other better lines, and see what is possible, while not letting complexity grow all that much  :-)

**Comment by jbergenthal2** [comment]
I'd say it's easier to first install your own custom font, and then use that in lanterna.

**Comment by klaushauschild1984** [comment]
That are all possible ways but I decided to go a complete other one. Most of the features of lanterna I do not need for my project: a classic ascii art roguelike.
So I spawned my own project [rl4j](https://github.com/klaushauschild1984/rl4j)

Maybe it a fault an I come back but at least I learned and done something new. Thanks

**Comment by mabe02** [comment]
You mean using a custom bitmap font that isn't registered as a system font? Because if you have a system font that isn't truetype that you'd like to use, I'm pretty sure that's doable through the usual font configuration object when creating the terminal.
