### ISSUE TITLE
Race condition with separate GUI thread.

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#355]
While playing with WelcomeSplashTest for issue 353, I noticed that I didn't _always_ get to see the Dialog.  Sometimes the empty BackgroundPane would just sit there forever with nothing to do in it (apart from Alt-F4, of course).

So far, I only see that in those failing cases, the TextGUI receives EOF from the SwingTerminal and expectably stops.  I'm just clueless why it gets an EOF, when the TerminalWindow is obviously there.

I'll leave it at that for now.  I might pick it up later, but that might be only after a week or month...

**Comment by mabe02** [comment]
Hmm, I can't reproduce it... What OS?

**Comment by avl42** [comment]
My OS is Linux, and running the app within eclipse ("Debug as ...") made it
trigger at a rather high rate.

Having a break point in afterGUIThreadStarted() method (and just continuing
when they're hit) seemed to trigger the race condition almost always.

My debugging so far showed that
https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/gui2/SeparateTextGUIThread.java#L121
was triggered in those bad cases, and that again was triggered by an
KeyType.EOF keystroke received from the SwingTerminal.

**Comment by mabe02** [comment]
Okay, I've been able to reproduce it too now, but it happens very rarely. Tried to put the computer under heavy CPU load to see if that caused it to happen more often but rather the opposite happened, I never got it into this state.

**Comment by mabe02** [comment]
Okay, I found it:
```
    @Override
    protected synchronized KeyStroke readKeyStroke() throws IOException {
        KeyStroke keyStroke = super.pollInput();
        if(eofWhenNoWindows && keyStroke == null && windows.isEmpty()) {
            return new KeyStroke(KeyType.EOF);
        }
        else if(keyStroke != null) {
            return keyStroke;
        }
        else {
            return super.readKeyStroke();
        }
    }
```
We need to check that at least a single window has been displayed earlier before returning EOF.

**Comment by mabe02** [comment]
That should do it
