### ISSUE TITLE
Exeception while resizing terminal window. 3.0.0

### ISSUE THREAD

**Issue by zella** [mabe02/lanterna#361]
When I resize window by dragging from bottom to top i gets error:

> 
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
> 	at com.googlecode.lanterna.graphics.BasicTextImage.copyTo(BasicTextImage.java:174)
> 	at com.googlecode.lanterna.screen.ScreenBuffer.copyTo(ScreenBuffer.java:117)
> 	at com.googlecode.lanterna.screen.TerminalScreen.refresh(TerminalScreen.java:149)
> 	at com.googlecode.lanterna.screen.VirtualScreen.refresh(VirtualScreen.java:196)
> 	at com.googlecode.lanterna.screen.AbstractScreen.refresh(AbstractScreen.java:179)
> 	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:122)
> 	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:221)
> 	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
> 	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:406)
> 	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:269)
> 	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:370)
> 

Scenario:

![_2018-05-19_03-50-35](https://user-images.githubusercontent.com/3839393/40263257-50d4c24c-5b18-11e8-8ca6-763d1d9c46e1.png)
![_2018-05-19_03-50-58](https://user-images.githubusercontent.com/3839393/40263258-50ff4436-5b18-11e8-97c6-0cd756e33b5b.png)

Code:
```

import com.googlecode.lanterna.gui2.*;
import com.googlecode.lanterna.screen.*;
import com.googlecode.lanterna.terminal.*;

import java.util.Arrays;

public class Bug {

    public static void main(String[] args) throws Exception {

        Terminal terminal = new DefaultTerminalFactory().createTerminal();
        Screen screen = new TerminalScreen(terminal);
        screen.startScreen();

        BasicWindow window1 = new BasicWindow();
        window1.setHints(Arrays.asList(Window.Hint.CENTERED));

        BasicWindow window2 = new BasicWindow();
        window2.setHints(Arrays.asList());

        // Create gui and start gui
        MultiWindowTextGUI gui = new MultiWindowTextGUI(screen);
        gui.addWindow(window2);
        gui.addWindowAndWait(window1);
    }
}
```

**Comment by mabe02** [comment]
I've merged the PR from @avl42 that should fix this
