### ISSUE TITLE
Disabled components in a border mess up focus traversal

### ISSUE THREAD

**Issue by honzasterba** [mabe02/lanterna#374]
When you have a disabled component (setEnabled(false)) in a border (addComponent(other.withBorder()) and it gets hit by find-next-thing-focus traversal it returns it as focusable, eventually it gets checked for being enabled and discarded and focus does not traverse anywhere making TAB effectivelly broken.

(I am just writing this down here so that I do not forget, test-case, and PR with a fix coming soon.)

**Comment by avl42** [comment]
The PR will be appreciated.
Please target it to branch "release/3.0" .  That will make it easier to
have it both in a future 3.0.2 and forward-merged to trunk.

**Comment by mabe02** [comment]
Pull request merged, thank you!
