### ISSUE TITLE
Any way to manually redraw?

### ISSUE THREAD

**Issue by cilki** [mabe02/lanterna#375]
I'm porting a small AWT library that uses `java.awt.Component.validate()` and I can't figure out what the Lanterna equivalent would be. Is there any way to directly trigger a redraw rather than simply suggesting it with `invalidate()`? It seems like I shouldn't just call `draw(TextGUIGraphics)` from the outside.

I'm working in an `AbsoluteLayout` if that makes any difference.

**Comment by avl42** [comment]
My personal guess would be that you can just remove the "validate()" calls,
or maybe provide a dummy-implementation for logging purposes.

redrawing a textual screen is surely pretty different from a graphical
screen, where explicitly validating parts is mostly a means to avoid
performance issues.

There is, however an option to just use the textscreen (class
TerminalScreen) as a textual "canvas" and not use the "gui2" components and
their processing loop at all.

**Comment by mabe02** [comment]
Yes, we don't keep track of components needing to re-layout vs re-paint, so just `invalidate()` should do. The UI thread will then do the work at the next available opportunity.
