### ISSUE TITLE
[FileDialog] When an absolute file name is entered in fileBox, the file should not be relative to directory in directoryListBox.

### ISSUE THREAD

**Issue by lolo101** [mabe02/lanterna#378]
When I open a FileDialog, it's sometimes faster to type an absolute path in the fileBox rather than navigating to the directory in the directoryListBox.

However the converted path is **always** relative to the directory.

I believe the path should be considered absolute whenever it starts with '/' (in Linux).

Example :
![capture](https://user-images.githubusercontent.com/555864/41712170-30154558-754a-11e8-90b4-0956e66cd11e.PNG)

I expect the resulting path to be "/dev/sda1" however I get "/home/engineer/Documents/GitHub/fatChains/dev/sda1"

**Comment by lolo101** [comment]
BTW that's how Swing's JFileChooser works.

**Comment by mabe02** [comment]
PR is merged, thank you!
