### ISSUE TITLE
GridLayout behaves differently when a spanning component was added before

### ISSUE THREAD

**Issue by hupfdule** [mabe02/lanterna#380]
Assume the following code:

    // two column grid               
    final Panel p= new Panel(new GridLayout(2));
                                     
    // spanning component in the first row 
    p.addComponent(new Label("My dummy label"), GridLayout.createLayoutData(
        GridLayout.Alignment.FILL,
        GridLayout.Alignment.BEGINNING,
        true,                        
        false,                       
        2,                           
        1)                           
    );                               
                                     
    // col 1, row 2                  
    p.addComponent(new TextBox(),         GridLayout.createLayoutData(
            GridLayout.Alignment.FILL,
            GridLayout.Alignment.FILL,
            true,                    
            true)                    
    );                               
    // col 2, row 2                  
    p.addComponent(this.buildButtonPanel(), GridLayout.createLayoutData(
            GridLayout.Alignment.BEGINNING,
            GridLayout.Alignment.BEGINNING,
            false,                   
            false));                 
                                     
    // spanning component in row 3                                                                                                                                    
    p.addComponent(this.buildButtonBar(),   GridLayout.createLayoutData(
        GridLayout.Alignment.CENTER,
        GridLayout.Alignment.BEGINNING,
        false,                       
        false,                       
        2,                           
        1)                           
    );                           

This results in a panel like the one below: 
![wrong](https://user-images.githubusercontent.com/36069345/41977090-d63e167a-7a1e-11e8-9aa5-8d597976b99b.png)

However, the TextBox on the left should fill its area horizontally. When removing the spanning component in the first row, it gets calculated correctly:
![correct](https://user-images.githubusercontent.com/36069345/41977161-fbfbb4b2-7a1e-11e8-9a04-96e16ee0f6f5.png)

**Comment by mabe02** [comment]
Yes, that's not correct. Something's not right with the grid code

**Comment by mabe02** [comment]
Okay, I found the issue, it broke recently when I fixed another bug in the grid. How much I wish we could have used SWT's GridLayout instead... :(

**Comment by mabe02** [comment]
That should be fixed now
