### ISSUE TITLE
Ability to stretch a single column of a Table.

### ISSUE THREAD

**Issue by RobertZenz** [mabe02/lanterna#384]
A nice feature would be to be able to specify a stretched column in the `Table`.

The stretched column would simply consume all space which is still left over from all the other columns.

**Comment by mabe02** [comment]
You can kind of achieve the same thing by using GridLayout if your content is read-only, but I'm assuming it's not? You'd want to be able to navigate to this stretched column and interact with it as well?

**Comment by RobertZenz** [comment]
> You can kind of achieve the same thing by using GridLayout if your content is read-only, but I'm assuming it's not?

Can you give me an example? Do you mean of having three tables side by side in the grid layout?

 > You'd want to be able to navigate to this stretched column and interact with it as well?

Ideally, yes.

To be exact, I'm trying to replicate [this layout](https://gitlab.com/RobertZenz/jMathPaper/raw/master/screenshots/01-main-view.png).

**Comment by mabe02** [comment]
Except for the tabs (we don't have any tab component (yet)), that looks doable. Which one is the "stretchable" column in the example above, the text box at the bottom?

**Comment by RobertZenz** [comment]
The middle column "Expression" of the table is stretched to fill the remaining width. The textbox is right aligned, if you haven't guessed from my other ticket. Pretty much the whole [UI is working so far](https://i.imgur.com/SD1fC1D.png), with the sole exception of these two tickets (and that I haven't added a menu).

I've started working on *something* like a Tabbar, you can find the current development state in [the tui2-dev branch of jMathPaper](https://gitlab.com/RobertZenz/jMathPaper/blob/tui2-dev/src/org/bonsaimind/jmathpaper/uis/tui2/components/PseudoTabBar.java) (sooner or later that branch will be in master). It is not that impressive, though, as it does not actually switch components.

I'd be happy to assist with my tickets by actually implementing them, but I'm not sure when I will find the time for it in the next time.

**Comment by mabe02** [comment]
Ah, ok, now I see what you mean. You'd like a table column to stretch out and take all the excess space when the component is larger than it needs to be. That might be not too hard to do.

**Comment by mabe02** [comment]
Can you try latest release/3.0 and see if that works for you? I've added a method on the default table renderer that will allow you to select which column to expand if there is more space available.

**Comment by RobertZenz** [comment]
I just retried with release/3.0 branch and I'm not seeing the exception there. Thank you very much.
