### ISSUE TITLE
Table and PgUp & PgDn support

### ISSUE THREAD

**Issue by MartyIX** [mabe02/lanterna#387]
Hi,

I have noticed that [`Table`](https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/gui2/table/Table.java) does not support `PgDn` and `PgUp` keys. It would be nice to support them. 

Having a quick glimpse at the code, it does not seem so hard to add the functionality and I may be able to do provide a PR.

Best regards,
Martin

**Comment by mabe02** [comment]
Contributions are much welcome!
