### ISSUE TITLE
com.googlecode.lanterna.gui2.PanelTest throws NPE

### ISSUE THREAD

**Issue by MartyIX** [mabe02/lanterna#393]
Hi,

I have tried to build latest master (i.e. 6dc0fb95bd47b801c9c66f93b4f1b9a9390f2e73) and to run `PanelTest`. The test ends with NullPointerException.

Does anybody know how to fix it?

Regards,
Martin

**Comment by MartyIX** [comment]
There is actually one more bug I can see: `com.googlecode.lanterna.gui2.TableTest` allows me to give focus to something UNDER <ADD> button (to panel?)

**Comment by mabe02** [comment]
You're right, this test seems to have been bad for quite some time now

**Comment by mabe02** [comment]
Alright, `PanelTest` is ok now

**Comment by mabe02** [comment]
Not sure what you mean by the TableTest, I do see the menu when I activate the [Add...] button:
![bild](https://user-images.githubusercontent.com/10136489/45251014-f35a5b80-b379-11e8-87f6-9e0aac0b87d1.png)

**Comment by mabe02** [comment]
Still looks fine over here (Windows 10, haven't tried Linux yet):
![bild](https://user-images.githubusercontent.com/10136489/48934334-ef84b100-ef46-11e8-980a-5e7b0af8669a.png)
Using latest master branch and running the table test class without any further modifications. Are the buttons disabled from the beginning or when you add all those rows?

**Comment by avl42** [comment]
When I run TableTest, I get an NPE, too, but it is caused by LocalizedString.Cancel.toString() returning null in ActionListDialog.java:76

My Locale is "de_DE"

**Comment by mabe02** [comment]
Strange, why would it fail with de_DE but work with sv_SE? Anyway, I've added to code on release/3.0 to do a proper fallback if the localized string can't be found. Let's see if that fixes it.

**Comment by avl42** [comment]
I intend to analyze further why it didn't find the files for "de_DE" locale, but even if it turns out to be a local eclipse mis-configuration, then (as it seemed from reported NPE) others might have the same, so having a safe fallback is certainly a good Idea.

I'm a bit puzzled, though, in that I thought something had already been done years before to improve finding of localization data.  Now, either that change disappeared (maybe it was in a specific branch), or something else changed to break it.

**Comment by avl42** [comment]
Analysis done.   I had forgotten to add   src/main/ressources as a "source folder" to the build path in eclipse.  The new behaviour of getting just English labels is much better than getting NPE :-)

**Comment by mabe02** [comment]
Oh, nice one! :)
