### ISSUE TITLE
Chinese Characters

### ISSUE THREAD

**Issue by xp4u1** [mabe02/lanterna#395]
# Chinese Characters

The gui can not represent Chinese characters

<image src="https://i.imgur.com/9ZpLQpQ.png">
<image src="https://i.imgur.com/i9ysv3t.png">

---
## system informations
`os: linux`

`java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)`

**Comment by avl42** [comment]
swingterminal or tty ?

>

**Comment by avl42** [comment]
you could look in the classes near swingterminal for a class with
FontConfig in its name...

if you find it, you can play with fontnames to get one that supports
chinese chars.  apparently, the font chosen by lanterna doesn't on your
system.

Are you regularly working with chinese letters (e.g. is it one of your
languages), or just trying your app for chinese support?

>

**Comment by MartyIX** [comment]
I would suggest to clone Lanterna via git and run a modified test with Chinese characters in your IDE. 

https://github.com/mabe02/lanterna/tree/master/src/test/java/com/googlecode/lanterna/issue - some tests are here

**Comment by jbergenthal2** [comment]
What'd be the name of that default font?

**Comment by mabe02** [comment]
It depends on the OS:
```
private static List<Font> getDefaultWindowsFonts() {
        int fontSize = getFontSize();
        return Collections.unmodifiableList(Arrays.asList(
                new Font("Courier New", Font.PLAIN, fontSize), //Monospaced can look pretty bad on Windows, so let's override it
                new Font("Monospaced", Font.PLAIN, fontSize)));
    }

    private static List<Font> getDefaultLinuxFonts() {
        int fontSize = getFontSize();
        return Collections.unmodifiableList(Arrays.asList(
                new Font("DejaVu Sans Mono", Font.PLAIN, fontSize),
                new Font("Monospaced", Font.PLAIN, fontSize),
                //Below, these should be redundant (Monospaced is supposed to catch-all)
                // but Java 6 seems to have issues with finding monospaced fonts sometimes
                new Font("Ubuntu Mono", Font.PLAIN, fontSize),
                new Font("FreeMono", Font.PLAIN, fontSize),
                new Font("Liberation Mono", Font.PLAIN, fontSize),
                new Font("VL Gothic Regular", Font.PLAIN, fontSize),
                new Font("NanumGothic", Font.PLAIN, fontSize),
                new Font("WenQuanYi Zen Hei Mono", Font.PLAIN, fontSize),
                new Font("WenQuanYi Zen Hei", Font.PLAIN, fontSize),
                new Font("AR PL UMing TW", Font.PLAIN, fontSize),
                new Font("AR PL UMing HK", Font.PLAIN, fontSize),
                new Font("AR PL UMing CN", Font.PLAIN, fontSize)));
    }
```

You are supposed to be able to use the virtual "Monospaced" which the JVM will then resolve to the preferred monospaced font on the platform but for reasons I can't remember (this was many years ago now) it wasn't working very well and I hard-coded it like above instead.
