### ISSUE TITLE
TextImage <-> File

### ISSUE THREAD

**Issue by klaushauschild1984** [mabe02/lanterna#396]
In my understanding of the implemenation of TextImage it is a memory-only thing.
It would be a nice addition to read a TextImage from a file or store it there. Is there any common file format for ascii art?

**Comment by avl42** [comment]
Well, the most common format for ascii-art is of course (*drum roll*) ascii
:-)

It's only when it is supposed to also store attributes and colors that ANSI
escape sequences are often used. these otoh are a bit memory-NON-optimized,
such that unless the textimages are pretty small or sparsely colored, one
might rather invent one's own markup.

I had that task of retrieving text back from a terminalscreen back in the
days of v2.x, when the textimage wasn't yet there. I wrote a special
"Terminal", and let the screen output itself to my special terminal, that
would record all the attribut settings, cursor movements and single
characters while the screen was forced to a full refresh. Back then, that
was the only way, but now in 3.x, one can easily query all the chars and
attributes using public api.


Klaus Hauschild <notifications@github.com> schrieb am Sa., 8. Sep. 2018,
11:08:

**Comment by klaushauschild1984** [comment]
You'r right and I actualy know by myself that ascii is the format to go storing an ascii image. My question goes for colors and other stuff stored nicely in a text file.
In a future application I want to provide external created ascii images and draw them to a terminal. Like you would do with an PNG or JPG.

**Comment by klaushauschild1984** [comment]
Before the existance of TextImage I tryed a three file approache.
A text file defined the characters and two PNGs defined foreground and background. But if you use it to actually create art with this beast of hopping from file to file it is hard to reach the imagined result.

**Comment by avl42** [comment]
for inspiration about rich text formats used for textual images, have a
look at "ascii cam" app (android).  i believe to remember that it could
save to html but maybe others as well...

if i were to invent such a thing, i'd go to define esc+single letter
sequences for the attributes (e.g. uppercase turns on, lowercase turns off)
and esc + number + some letter to set colors either 16, indexed or rgb,
like lanterna's color modes.  that's shorter than html or real ANSI, but
it's just an internal format.  to share it with people not using your
application, you'd export to html or ansi...

Klaus Hauschild <notifications@github.com> schrieb am Sa., 8. Sep. 2018,
21:46:

**Comment by klaushauschild1984** [comment]
Thanks for the replies and suggestions.
I implemented something you can find here: https://github.com/klaushauschild1984/lanterna-game/blob/master/src/main/java/com/googlecode/lanterna/game/TextImageIO.java

The implementation is based on three files. A text file defines the glyphs and two image files define the foreground and background color. All three files have to have the same dimension. You can store all three files in a directory or in a zip archive.

For visual testing a provided a viewer that reloads the image every time something changes at the files. Maybe your interesseted in integrating the sources to lanterna.
