### ISSUE TITLE
transparency for TextImage

### ISSUE THREAD

**Issue by klaushauschild1984** [mabe02/lanterna#397]
Hi there,

the current implementation of TextImage does not support transparency. Do you see a chance to implement this in the near future?
I would go for some thing like defining the transparent color in one of the four corners or hard wired pink.

**Comment by avl42** [comment]
Not sure whether you also support text attributes like underline, bold or
fraktur in your code... if you do, then you could use one of those for the
transparency bit. you could use the text attributes to store transparency
info from the pngs and write a transparency supporting copyTo variant for
use in your code.

Another idea, while you're at it: you could add a "shade" bit, that will
just darken the color of the char below it, but not affect the symbol
displayed.


If it were done in lanterna, there'd be a few issues (that wouldn't matter
in your own code):

Adding it directly would degrade performance a bit, as copyTo(...) couldn't
just use arraycopy anymore. For that, there'd need to be a separate method
for selective copying of characters, and maybe also respective variants of
drawImage(...) in TextGraphics...

There could be a specific TextCharacter instance that would be recognized
(with "==", not based on its char,attrs or color) and skipped in a new
copyToTrans(...).
That instance would be accessible as a static final constant of
TextCharacter.

Another TextCharacter instance could trigger shading, but each such special
textcharacter would need to be checked for, and thus slow down the process
a bit.

@mabe02, what's your stance on it?




Klaus Hauschild <notifications@github.com> schrieb am Di., 11. Sep. 2018,
19:42:

**Comment by klaushauschild1984** [comment]
First I was not precise with transparency. In my mind was just the idea of replacing the background color of the current character within the image by the background color of the character in the buffer underneath. For my application there is no need for graduated transparency.

Thanks for the hint with a special TextCharacter. Maybe I will adopt it. Now I have to find the right place to implement. But I will figure it out by myself.

Thank you.

**Comment by mabe02** [comment]
I've been thinking about something along these lines in the past but it seems very niche. Not sure if it's worth the effort and extra overloads to put it in the API.
