### ISSUE TITLE
Add mouse reporting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#40]
```
See this: http://myfreebsd.homeunix.net/freebsd/mouse_events_shell.html

We should expose these mouse events through the Terminal interface
```

Original issue reported on code.google.com by `mab...@gmail.com` on 21 Sep 2012 at 12:29

**Comment by mabe02** [comment]
Link is dead but still available here:
http://web.archive.org/web/20121030072230/http://myfreebsd.homeunix.net/freebsd/mouse_events_shell.html

**Comment by mabe02** [comment]
This is another pretty good reference: http://invisible-island.net/xterm/ctlseqs/ctlseqs.html

**Comment by mabe02** [comment]
This is now implemented in Lanterna 3, although implementation vary. For instance, I've noticed konsole has a really odd implementation of xterm mouse input while gnome-terminal, xfce4-terminal and xterm work pretty well. Supported operations are left, right, middle click, drag, scroll wheel up/down and mouse hoovering.
