### ISSUE TITLE
TextGraphics.putCSIStyledString doesn't work with 8-bit colors

### ISSUE THREAD

**Issue by BioRyajenka** [mabe02/lanterna#402]
Hi!
I found that TextGraphics.putCSIStyledString() works with 3/4 bit colors only. I'm going to fix it and create PR. 

(also, I didn't find any rules or recommendations on how to do it, so I will create branch bugfix/issue402 and will request merge right into master)

And also, I wonder what's the reason of using Java 1.6 and not 1.8? It is really unconvinient and strange.

**Comment by avl42** [comment]
Looks good at first glance.   @mabe02 ?

**Comment by mabe02** [comment]
Yep, looks good

**Comment by mabe02** [comment]
@BioRyajenka I'll merge this to release/3.0
