### ISSUE TITLE
Constant part of a screen, lanterna 

### ISSUE THREAD

**Issue by javaboi03** [mabe02/lanterna#405]
So I want to make a frame around my gui stuff, but when I do screen.clear(); it disappears. Any ideas How to make it stay? Also I cant make a method caleed makeFrame(); or anything like that because you need to make some objects to do anything actually. Please help. Here is the code for the frame

for (int i = 0; i < 78; i++) {
    tg.putString(i, 0, String.valueOf(Symbols.DOUBLE_LINE_HORIZONTAL));
}
for (int i = 0; i < 23; i++) {
    tg.putString(0, i, String.valueOf(Symbols.DOUBLE_LINE_VERTICAL));
}
for (int i = 0; i < 78; i++) {
    tg.putString(i, 23, String.valueOf(Symbols.DOUBLE_LINE_HORIZONTAL));
}
for (int i = 0; i < 23; i++) {
    tg.putString(78, i, String.valueOf(Symbols.DOUBLE_LINE_VERTICAL));
}
tg.putString(0, 0, String.valueOf(Symbols.DOUBLE_LINE_TOP_LEFT_CORNER));
tg.putString(0, 23, String.valueOf(Symbols.DOUBLE_LINE_BOTTOM_LEFT_CORNER));
tg.putString(78, 0, String.valueOf(Symbols.DOUBLE_LINE_TOP_RIGHT_CORNER));
tg.putString(78, 23, String.valueOf(Symbols.DOUBLE_LINE_BOTTOM_RIGHT_CORNER));
But also this stuff needs to be here

        Terminal terminal = new DefaultTerminalFactory().createTerminal();
        Screen screen = new TerminalScreen(terminal);
        TextGraphics tg = screen.newTextGraphics();

**Comment by avl42** [comment]
After drawing the frame you might want to call tg.newTextGraphics( ... ) to get a TextGraphics for a smaller region.

Rather than screen.clear()  you'll then rather call  the fill method from the confined TextGraphics.

**Comment by mabe02** [comment]
Yep, what @avl42 suggests is what I would suggest too. Does that work for you?

**Comment by mabe02** [comment]
I guess it did?

**Comment by javaboi03** [comment]
I havent tried yet. I had this problem 7 months ago. I just forgot to close it
