### ISSUE TITLE
Modularize (java 9/11) lanterna

### ISSUE THREAD

**Issue by loic-prieto** [mabe02/lanterna#407]
Hi there!

Thanks for the excellent work you've been doing so far with the library. I'm using it to create a 4X framework (xDD), and it is helping me a lot :)

I'm trying to migrate to Java 11 from Java 8, and one of the benefits of doing that is to be able to create compact java images with jlink. But all of your dependencies must be modularized too in order to do that, no automodularized packages can be included in that image. Which means that unless all libraries I use are modularized, I'm "stuck" with deploying my java app the usual way.

So, my request would be to make lanterna a java module, with the module-info.java class and all of those things required to do that. I've been looking at the dependencies of lanterna itself, and it almost depends on nothing, which I think would make for a painless conversion to the module system.

Would that work for you?

Best regards,
Loïc Prieto.

**Comment by jrb0001** [comment]
That sounds like a great idea. It should be possible to compile everything except `module-info.java` with -source/-target 1.6 to keep compatibility with older versions.

**Comment by mabe02** [comment]
I'd be happy to, but I have no experience in Java 9+ so I'm not sure how to do this.

**Comment by mabe02** [comment]
By the way, I'm also considering moving master branch to Java 8 finally. Not that it helps much with modules though.

**Comment by jrb0001** [comment]
The minimal version doesn't matter for modularizing. As far as I know, you have to execute the `maven-compiler-plugin` twice, once with the minimal source/target version and excluding `module-info.java` and once with source/target 9 but for `module-info.java`.

**Comment by loic-prieto** [comment]
I'm no expert myself. I'm currently struggling to migrate my app to Java11. It is proving to be challenging. The app itself is easy, but making the dependencies work and be able to test things and making them run on IntelliJ is very difficult. I'm running constantly into resource visibility issues.

I'm reading the following book: Java 9 Modularity 
To try to make sense of it all.

**Comment by Nzen** [comment]
I'm of the understanding that lanterna has two options to accommodate requests for modular jars :

1. Ensure that the resulting jar manifest has an entry with an `Automatic-Module-Name` . This is typically accomplished by adding an [extra config](https://github.com/Nzen/Enohar/blob/master/pom.xml#L140) to the maven jar plugin.
2. Utilize two maven build profiles to build two separate jars. One will have the pre-java-9 [compiler configuration](https://github.com/Nzen/Enohar/blob/master/pom.xml#L247); the other will have a post-java-9 [compiler configuration](https://github.com/Nzen/Enohar/blob/master/pom.xml#L315). Releasing to a repository involves running maven twice, and changing either the artifact id or the version to distinguish which is which. For example, `mvn release` (assuming the default profile is j6-8) ; \*change pom\* ; `mvn -P j9 release` (assuming the modularized profile is called j9).

I can submit a pull request for either, but the decision lies more with the individual creating releases, given that this may change hiso'er workflow.

There's another aspect, albiet relevant to #422 : this project can create two jars, but there are classes for the same package in each, `com.googlecode.lanterna.terminal`. A modular runtime will reject one of those jars. For callers that desire both on jre 9 or later, y'all may need to either move the native integration classes to a different package or unite them with mainline.

**Comment by jrb0001** [comment]
`Automatic-Module-Name` has the disadvantage that it doesn't work with `jlink`, which can create minimalistic runtime images based on the needs of the application.

There is also a third option:

3. Use two compiler passes, the second for producing Java 9+ bytecode into `META-INF/versions/9` (or whichever bytecode version you want to use). This will work on all runtime versions and is needed if you want to provide alternative versions of some classes for newer runtime versions (usually because of `Unsafe` or similar deprecated classes, there can be other reasons as well though).

**Comment by mabe02** [comment]
That sounds promising, do you have any reference material on how to set this up?

**Comment by jrb0001** [comment]
@mabe02 I have never actually tried it myself and all examples on the internet seem to call out to ant (ungh) so I decided to give it a try now. #429 is the third option mentioned above plus some small tweaks to support running without the `java.desktop` module.

**Comment by jrb0001** [comment]
#429 has been merged into master. @mabe02 When can we expect a release with it to Maven Central?

**Comment by mabe02** [comment]
Within a few weeks probably, I need to get the Java 8 migration working and also update all the themes to support the new menu functionality

**Comment by mabe02** [comment]
lanterna-3.1.0-alpha1 has been released and pushed to Sonatype
