### ISSUE TITLE
Resize Listener Problems

### ISSUE THREAD

**Issue by zenharris** [mabe02/lanterna#410]

**Comment by zenharris** [comment]
I have upgraded from Lanterna 2.1.7  to ver 3.01 and there seems to be a problem with the resize listener, I attach one to each window but resizing any window makes all the listeners think their individual windows have all been changed.

**Comment by avl42** [comment]
That would be quite strange.   Each Terminal has it's own list of registered listeners.
Are you sure you don't register the same instance with all the Terminals you have,
rather than create a new instance for each Terminal?

**Comment by avl42** [comment]
I just created a test: creating 3 SwingTerminals, each with the same instance of a custom TerminalResizeListener implementation that would report to stdout in its onResized() method. Even that worked fine.  The correct Terminal's resizing was reported, each time I resized one of these Terminals.

Maybe you're using static fields in your TerminalResizeListener ?

**Comment by avl42** [comment]
```
package com.googlecode.lanterna.terminal;

import com.googlecode.lanterna.TerminalSize;
import com.googlecode.lanterna.terminal.swing.SwingTerminalFrame;

public class TerminalListenerTest {
    public static void main(String[] args) {
        DefaultTerminalFactory tf = new DefaultTerminalFactory();
        TerminalResizeListener trl = new MyResizeListener();
        for (int i=1; i <= 3; i++) {
            spinoff( tf.createSwingTerminal(), trl, i );
        }
    }
    static void spinoff(SwingTerminalFrame terminal, TerminalResizeListener trl, int id) {
        terminal.setVisible(true); terminal.addResizeListener( trl );
    }
    static class MyResizeListener implements TerminalResizeListener {
        public void onResized(Terminal terminal, TerminalSize newSize) {
            System.out.println("Terminal "+terminal+" was resized to "+newSize+".");
        }
    }
}
```

Could you try it, or provide a (short!) example that misbehaves?

**Comment by zenharris** [comment]
In reducing the problem to its simplest form and trying your code, I see now the resize operations are sound. The problem is all in my code. I'll just close this off. Thanks for taking the time to respond.
