### ISSUE TITLE
about Window size

### ISSUE THREAD

**Issue by Saint-Theana** [mabe02/lanterna#416]
Ive been trying a lot to set a Window's width to harf a terminal's width.can anybody tell me the solution?

**Comment by avl42** [comment]
I'm assuming now that the problem is something else than just obtaining the size of the terminal, dividing the width of the terminal by 2 and using the result as width for the window.

Maybe, you mean you want the Window to grow or shrink if the terminal is grown or shrunk?

**Comment by Saint-Theana** [comment]
no,I just wanted to set a window's size to any size,bot window.setsize wont work,only by using gridLayout.setHorizontalSpacing did I manage to chane a window's size,And I dont have any idea size.getrows() has anything to do width width.

**Comment by avl42** [comment]
The getRows() method of a TerminalSize object returns the height, not the width.  The getColumns() returns the width.

You say that setting the size on the Window doesn't work. What size does the Window instead have?

Maybe you "forgot" to set the FIXED_SIZE hint. Not giving this Hint means that the Window will try to size itself based on the contained components.

Another possible (but less likely) explanation might be that you (accidentally) add one of the FULL_SCREEN or EXPANDED Hints.

**Comment by Saint-Theana** [comment]
Thanks problem solved.
