### ISSUE TITLE
Here comes another problem.

### ISSUE THREAD

**Issue by Saint-Theana** [mabe02/lanterna#419]
I dont want a scroll bar aside with textbox shown,is there anysolution?

**Comment by avl42** [comment]
This is unfortunately a bit complicated.

First, you need to get the Renderer of the TextBox, then you need to make sure it is really a "DefaultTextBoxRenderer" (it usually is, unless you explicitly set one yourself) and cast to it,
then call method .setHideScrollBars(true) on the renderer.

e.g.:
```
    TextBox tb = new TextBox("abc\ndef\nghi"));
    if (tb instanceof DefaultTextBoxRenderer) {
        DefaultTextBoxRenderer dtbr = (DefaultTextBoxRenderer)tb;
        dtbr.setHideScrollBars(true);
    }
```

**Comment by Saint-Theana** [comment]
Thank you for your help

**Comment by Saint-Theana** [comment]
some how it does not work,it should be due to unequred instance of DefaultTextBoxRenderer,when I delete cause,it worked!
'''
com.googlecode.lanterna.gui2.TextBox.TextBoxRenderer tbr = this.textbox.getRenderer();
		com.googlecode.lanterna.gui2.TextBox.DefaultTextBoxRenderer dtbr = (TextBox.DefaultTextBoxRenderer) tbr;
	    dtbr.setHideScrollBars(true);
'''java

**Comment by avl42** [comment]
"instanceof" is a java keyword and it has no blank between "instance" and "of".
