### ISSUE TITLE
What am i missing?

### ISSUE THREAD

**Issue by tardistravler** [mabe02/lanterna#432]
Hello, 
i have a try catch in my static void main method, 
terminal = new DefaultTerminalFactory().createTerminal();

The method createTerminal() from the type DefaultTerminalFactory refers to the missing type IOException

I'm new to GITHUB. :-) 
I downloaded the project via GitHub in Eclipse and then created a jar file. 
I added the jar file to my existing project. 
Why am I getting this error? 
Thanks.

**Comment by RobertZenz** [comment]
Is it possible that you're using Java 9+, have a module project and did not specify/import `java.base`?

**Comment by tardistravler** [comment]
That was it! Thank you kindly!

**Comment by RobertZenz** [comment]
Then I suggest you close this.

**Comment by tardistravler** [comment]
Thank you again for the help Robert!
