### ISSUE TITLE
Question on input

### ISSUE THREAD

**Issue by tardistravler** [mabe02/lanterna#433]
Hello!
I got a quick question on input. I usually use Scanner(System.in)

How do i implement an input? For example, 
Enter your name : 
someone enters their name, 
I understand KeyStroke is the way to go but its Only for 1 Char. 

Thanks.

**Comment by RobertZenz** [comment]
Huh? There are components which are doing all that for you, if you want to read input, you place down a TextBox. See the [gui2 package](https://github.com/mabe02/lanterna/tree/master/src/main/java/com/googlecode/lanterna/gui2) for all available components.

**Comment by mabe02** [comment]
Yes, you probably need to read up on the documentation. If you're using the lowest-level `Terminal` interface, the only way to read input is key-by-key like what you've found already. You could easily write a method that reads all `KeyStroke`s until the user press Enter and assemble it into a `String`.
