### ISSUE TITLE
Undecorated window support

### ISSUE THREAD

**Issue by reibitto** [mabe02/lanterna#438]
I'd like to make the Swing terminal window undecorated, but the issue is that you have to call `jframe.setUndecorated(true)` before it's displayable, otherwise you'll get `java.awt.IllegalComponentStateException: The frame is displayable.`.

I initially thought to use `setAutoOpenTerminalEmulatorWindow(false)`, set undecorated to false, and then `setVisible(true)` after that. But that doesn't work either because this `pack()` call also triggers `displayable` to be true:
https://github.com/mabe02/lanterna/blob/4d083e9d33c6067fb3691397b07b0a503f2e561f/src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminalFrame.java#L116

And by then it's too late.

I could see multiple ways of fixing this. Adding a `setUndecorated` method is one way (such as to the terminal factory), or perhaps delaying the pack() call when `autoOpenTerminalEmulatorWindow` is false? Which would be preferable? Or is there a different approach that can be taken?

**Comment by mabe02** [comment]
Interesting, I wasn't aware of that. I think you might be able to extend from SwingTerminalFrame and override the pack method to suppress the call when it's done in the constructor. But I've changed the code on release/3.0 branch so it doesn't call `pack()` until `setVisible()`, hope that helps!

**Comment by reibitto** [comment]
Thanks! Yeah, that's basically the workaround I was using.

I'll have to try the new code. Sounds like it would solve it.
