### ISSUE TITLE
Graal native image support

### ISSUE THREAD

**Issue by reibitto** [mabe02/lanterna#440]
Still trying to figure this one out. Running native-image with a dependency on AWT/Swing seems to be an issue. See https://github.com/oracle/graal/issues/664 for example.

As an experiment though, I removed the AWT/Swing terminal emulators from lanterna and native-image worked. And the nice thing was that my command line application was noticeably faster to load while also capable of running at a much lower memory footprint. This makes me wonder if it would make sense to split off the terminal emulators into a separate module so that users could use a lanterna-core without any complications.

There might be some other way around all this but I'm still investigating. I'll post an update when I find out more. I have one other idea that I need to try first.

**Comment by jrb0001** [comment]
This reminds me of my work in #429. It should run without java.desktop (and thus AWT/Swing) so it sounds like native-image adds it to the dependency graph even though it isn't needed?

**Comment by reibitto** [comment]
@jrb0001 I think I figured it out. I created a PR (#441). Basically the issue seems to be that AOT compilation can't know AWT/Swing isn't going to be needed by looking at `createTerminal()`.

AWT/Swing support with native-image when it's ready would be nice too, but I'm not sure there's anything that needs to be done on laterna's side for that besides possibly documenting whatever command line options will be needed to make it work. Assuming it gets solved in the first place.

But at least plain command line applications can be run as a native executable. I think that's fairly significant. I'm already seeing noticeable performance benefits.

**Comment by avl42** [comment]
If you want to make sure that the AOT compiler *knows* you're not going to
use AWT/Swing, you can also skip the DefaultTerminalFactory altogether and
instead instanciate the appropriate *Terminal subclass directly.

**Comment by reibitto** [comment]
That is true and something I was contemplating too. I would be fine with just closing my current PR then.

The only thing is that you don't get the telnet/windows/unix terminal switching logic out of the box, but it's only 5 lines or so anyway so it's not a big loss. 

And I was feeling a bit uneasy about polluting the `TerminalFactory` contract. The other alternative is to just leave the interface alone and have `createHeadlessTerminal` for re-use in the concrete implementation only? I don't have strong feelings about this though.

**Comment by avl42** [comment]
I could also imagine a DefaultHeadlessTerminalFactory, whose createTerminal
method would only consider non-graphical Terminal implementations.

Anyway, adding a method to DefaultTerminalFactory wouldn't imply any need
to also put it into TerminalFactory interface.   There are already a couple
of createXxxTerminal methods that aren't in the interface.

**Comment by reibitto** [comment]
Yeah, that's a good point. For now I just reverted the interface change.

**Comment by neuromantik33** [comment]
I just wanted to chime in, without reopening the issue, that resizing is currently unsupported when build native images due to the reflection used in [registerTerminalResizeListener](https://github.com/mabe02/lanterna/blob/20ecf7b701d2c75892f207c53d34203161167721/src/main/java/com/googlecode/lanterna/terminal/ansi/UnixLikeTTYTerminal.java#L89-L109). Although not very portable, I was forced to rewrite it without reflection and it worked! I just thought I would let you know in case someone else encounters the problem.

```java
@Override
protected void registerTerminalResizeListener(Runnable onResize) {
    //noinspection UseOfSunClasses
    handle(new Signal("WINCH"), sig -> onResize.run());
}
```

**Comment by mabe02** [comment]
I'm open to improve it in a way that's compatible with both the standard JVM and Graal, if anyone has any suggestions :)
