### ISSUE TITLE
Create new module for the terminal.swing package

### ISSUE THREAD

**Issue by cilki** [mabe02/lanterna#444]
Thanks for turning this library into an explicit module!

It would be nice if the `com.googlecode.lanterna.terminal.swing` package was included in a separate module. I'm not using Swing at all, so I don't really like the dependency on `java.desktop` when building custom runtime images.

Thanks again for this library.

**Comment by jrb0001** [comment]
`java.desktop` is an optional dependency ([module-info.java:33](https://github.com/mabe02/lanterna/blob/master/src/main/java9/module-info.java#L33)) so your custom runtime image shouldn't need it.

**Comment by cilki** [comment]
@jrb0001 You're right. I overlooked the `requires static` part. Thanks!
