### ISSUE TITLE
does lanterna have support for box drawing unicode characters?

### ISSUE THREAD

**Issue by git-somenumber** [mabe02/lanterna#445]
[U2500.pdf](https://github.com/mabe02/lanterna/files/4085435/U2500.pdf)
These are unicode box drawing characters.
Just wanted to check if these features are wanted and if they exist??

PS: I am new to contributing to open source pardon any mistakes in phrasing the question.This is the first issue I am opening

**Comment by git-somenumber** [comment]
They would be useful to create games like myman

**Comment by mabe02** [comment]
Yes, they are! You can find many of them defined as constants in `com.googlecode.lanterna.Symbols` although there's nothing preventing you from printing any of these block characters straight out to the terminal through `Terminal#putCharacter(..)`. The screen and GUI layers supports them as well, just put them in a string and you should see them.
