### ISSUE TITLE
ArrowDown and ArrowUp have unexpected behaviour when used with Menus

### ISSUE THREAD

**Issue by duubi474** [mabe02/lanterna#446]
My fork: [duubi474/lanterna](https://github.com/duubi474/lanterna)
Branch: arrow_key_bug

Basically the problem is this. If you create components like this [WorkingUpKeyMenuTest.java](https://github.com/duubi474/lanterna/blob/arrow_key_bug/src/test/java/com/googlecode/lanterna/integration/WorkingUpKeyMenuTest.java):

Menu
TextBox
QuitButton

And then you browse the components using ArrowUp and ArrowDown keys the ui somehow completely skips over the TextBox.

However, if you add non-interactable component between Menu and TextBox the browsing seems to work. Basically the layout here is like so [FailingUpKeyMenuTest.java](https://github.com/duubi474/lanterna/blob/arrow_key_bug/src/test/java/com/googlecode/lanterna/integration/FailingUpKeyMenuTest.java):

Menu
Label
TextBox
QuitButton

**Comment by mabe02** [comment]
Confirmed, that's a bug. I've fixed it on master.
