### ISSUE TITLE
Set size for terminal 

### ISSUE THREAD

**Issue by umocolombo** [mabe02/lanterna#447]
hi everyone
Sorry i have stupid question!
How i can set size for terminal?
I mean size horizontal and vertical.
can your share your code, and show.

**Comment by mabe02** [comment]
If you're using the SwingTerminalFrame, you can get the underlying JFrame and resize it with code. For regular terminal emulators, some of them supports programmatic resizing but lanterna doesn't implement that feature. I'd recommend you to code your program to obey whatever size the user sets, unless you have something very special in mind.

**Comment by umocolombo** [comment]
ok! thank you very much ;)
