### ISSUE TITLE
SimpleTheme.makeTheme() gives an error

### ISSUE THREAD

**Issue by AObuchow** [mabe02/lanterna#453]
Hey,
I'm trying to use SimpleTheme.makeTheme() to theme my application.

As a test, I'm trying out 
```
gui.setTheme(SimpleTheme.makeTheme(true, TextColor.ANSI.WHITE, TextColor.ANSI.BLACK, TextColor.ANSI.MAGENTA, TextColor.ANSI.BLUE, TextColor.ANSI.YELLOW, TextColor.ANSI.RED, TextColor.ANSI.GREEN));
````

However this is throwing a `java.lang.IllegalArgumentException: Collection is empty`
Here's the full stacktrace:
```
Exception in thread "main" java.lang.IllegalArgumentException: Collection is empty
	at java.base/java.util.EnumSet.copyOf(EnumSet.java:173)
	at com.googlecode.lanterna.graphics.DefaultMutableThemeStyle.<init>(DefaultMutableThemeStyle.java:58)
	at com.googlecode.lanterna.graphics.SimpleTheme.<init>(SimpleTheme.java:110)
	at com.googlecode.lanterna.graphics.SimpleTheme.makeTheme(SimpleTheme.java:61)
	at com.aobuchow.sample.manager.App.main(App.java:74)
```

It seems `DefaultMutableThemeStyle(TextColor foreground, TextColor background, SGR... sgrs)` doesn't work with an empty set of SGR.

If you'd like me to submit a PR for this, just let me know :)

Thanks!

**Comment by avl42** [comment]
I'm somewhat confused by that.  It seems like `java.base/java.util.EnumSet.copyOf` was the one that doesn't accept empty sets.  That's so bizarre, I just don't want to believe it yet...

**Comment by avl42** [comment]
After some initial confusion, it is now clear, that the route array->Collection->enumSet indeed doesn't work for empty arrays.  apparently, Java has no way of inferring the correct EnumSet-type in that case.

I'd guess that one could create an empty EnumSet<SGR> ahead, and then just addAll(sgrs).

If you have arrived at the same (or a nicer) solution, then please PR it.  We'll have to wait for the boss (@mabe02) to merge it, though.

**Comment by AObuchow** [comment]
Sounds good. I'll work on a PR soon and submit it :)

**Comment by mabe02** [comment]
Ouch, good catch! Since you've already started coding on it, please give it a try and raise a PR when ready.

**Comment by AObuchow** [comment]
Thank you to everyone who helped with this issue (@avl42, @jrb0001 & @mabe02) ! :)

Is there a planned release date/schedule for the next version of Lanterna? I look forward to using `SimpleTheme.MakeTheme()` in my application :)

Additionally, I was going to suggest: maybe I can help set up some CI instances for this repository through GitHub actions? 
There could be a CI workflow to verify that PR's build successfully, and another workflow to deploy to Maven Central when the Master branch is modified.

If this idea is worth looking into, I can create a new bug to track it :)

**Comment by mabe02** [comment]
Yeah, I'll push a new version tomorrow

**Comment by AObuchow** [comment]
Okay, awesome :)

**Comment by mabe02** [comment]
3.0.3 was just released to Sonatype

**Comment by AObuchow** [comment]
Great, can’t wait to consume all the fixes & features in this new version :D
