### ISSUE TITLE
Is it possible to temporarily hide a component?

### ISSUE THREAD

**Issue by AObuchow** [mabe02/lanterna#456]
Is it possible for components to be hidden (not be rendered) somehow? I'd like to make a component appear only when a specific keystroke is inputted and later disappear. 

I couldn't find any function to do this, perhaps there's a workaround?

**Comment by keithkml** [comment]
I think the workaround is simply to remove and re-add the component later. You could also try setting its preferred size to 0,0, though that might mess up layout, especially if the layout manager uses inter-component spacing.

**Comment by AObuchow** [comment]
Okay sounds good, thanks for the response :)

**Comment by mabe02** [comment]
Yeah, there isn't any visible flag on the GUI components unfortunately. You'll need to remove and re-add them.
