### ISSUE TITLE
TextColor.ANSI should support bright foregrounds and backgrounds

### ISSUE THREAD

**Issue by keithkml** [mabe02/lanterna#475]
TextColor.ANSI [only supports](https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/TextColor.java#L103) the normal versions of the basic 4-bit colors. Why not include the bright versions of the colors? (The code mentions that bold can make the color brighter in some terminals, but that only works for foreground.)

**Comment by avl42** [comment]
If you had a character with a bright background... do you know how to send it as an ANSI-color escape sequence?    I think, most terminals only have 3bit of color info for foreground, and 3bit for background, plus one more bit for bold.   If you want more colors for a terminal that supports it, like swingterminal, then just used Indexed colors or full RGB.
