### ISSUE TITLE
CheckBoxList with Horizontal ScrollBar

### ISSUE THREAD

**Issue by rednoah** [mabe02/lanterna#485]
Does `CheckBoxList` support Horizontal Scrollbar? I can't seem to figure out how to make a `List` that can scroll both vertically and horizontally.

**Comment by AObuchow** [comment]
I've also run into this issue! 

If this feature doesn't exist, I could hopefully provide a patch for it (although I might need a bit of guidance).

**Comment by rednoah** [comment]
Indeed, only vertical scroll is currently implemented:
https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/gui2/AbstractListBox.java#L363

**Comment by avl42** [comment]
If I'm not mistaken, a CheckBoxList always is a vertical list of
checkboxes. That's why it scrolls only vertically.
A need to scroll such a list sideways means that one has provided too long
labels to each checkbox ;-)

**Comment by AObuchow** [comment]
@avl42 correct :)

In my case, the labels in the checkbox are file paths, which can be of variable length, and the checkbox has it's own window (I implemented a checkboxListDialog, which I plan to submit upstream eventually :) )
As a result, an exception would be thrown if the labels were so long that the checkbox list's window would expand past the size of the terminal (or something similar, I can give the exact stack tracer tonight).

The workaround was to limit the size of the checkboxListDialog's window, however, this means that certain labels aren't fully-readable as they exceed the maximum-visible length. 

I'm not sure if this is a good enough use case to require horizontal scrollbars though, maybe there's a workaround?

@rednoah what's your use case? I'm curious if you're facing a similar issue.

**Comment by rednoah** [comment]
Essentially the same use case as @AObuchow I suppose. File paths. Not generally a problem, but some users do have crazy long file paths for some reason.

e.g.
![image](https://i.imgur.com/SKFw41i.png)

**Comment by avl42** [comment]
I'm tempted to think of "good ol' norton commander" or midnight commander
on unix.  You have panels of files, and if filenames are too long, they are
shortened with maybe the begin, the end, or some middle part being replaced
by "..."

Even if the user needs to be able to see the full 256 chars or longer
filename, I'd probably instead let the labels themselves scroll (with
cursor right/left), while leaving the "[ ]" checkboxes fixed against
horizontal scrolling.

Unfortunately, however, if you need it, you need to implement it yourself,
as of Lanterna's current state.

**Comment by AObuchow** [comment]
> I'm tempted to think of "good ol' norton commander" or midnight commander on unix. You have panels of files, and if filenames are too long, they are shortened with maybe the begin, the end, or some middle part being replaced by "...".

I'm actually making a type of Norton Commander clone, and have this implemented with a `ListItemRenderer` :D

> Even if the user needs to be able to see the full 256 chars or longer filename, I'd probably instead let the labels themselves scroll (with cursor right/left), while leaving the "[ ]" checkboxes fixed against horizontal scrolling. Unfortunately, however, if you need it, you need to implement it yourself, as of Lanterna's current state.

Okay I'll go with this approach. I assume there's no way to do this with a `ListItemRenderer` correct? I'd have to override the labels of the checkbox (if that's possible?).

**Comment by rednoah** [comment]
I've looked into `Table` which does seem to implement vertical scroll, but at least in my test case vertical scrolling didn't work, rows are just cut off, with no scrollbars or sideway scrolling. I'll look into it again some other time.

**Comment by mabe02** [comment]
@AObuchow yes, unfortunately there is no native support for horizontal scrolling of list item labels. There is a ScrollBar component you can use, but you'll have to implement your own renderer (with scrolling state) for the listbox and then hook that up to the scrollbar.

**Comment by AObuchow** [comment]
@mabe02 that's fine with me :) I'll use the approach you described and let you know how it goes.

**Comment by rednoah** [comment]
Closing this issue in favour of the generic `ScrollPanel` feature request:
https://github.com/mabe02/lanterna/issues/490
