### ISSUE TITLE
Bar and pie charts

### ISSUE THREAD

**Issue by FuriosoJack** [mabe02/lanterna#489]
I am going to develop an inventory and accounting system, all the business logic will be developed in node.js in another server. However I would like to use this library as the front of the application.

My software will have several views, therefore the question arises if it is advisable because there are several modules to create a window(Extend AbstractWindow) for each module?

In addition to this, they believe that it is possible to create bar and pie graphs to show the supports, the latter being that it is not in the library but they believe that with the functions that already exist, it can be designed?

![image](https://user-images.githubusercontent.com/26976637/83977016-654f3400-a8c3-11ea-9d0c-0a845f700481.png)

**Comment by ginkoblongata** [comment]
I am not familiar enough to answer your first question.

For your second question, yes this library would be able to provide bar chars fairly straighforwardly.
For pie charts, I am not sure the rationale, pie charts are fancy to look at but if you do a pie chart with this library you would have pixels the size of your characters.

**Comment by FuriosoJack** [comment]
> I am not familiar enough to answer your first question.
> 
> For your second question, yes this library would be able to provide bar chars fairly straighforwardly.
> For pie charts, I am not sure the rationale, pie charts are fancy to look at but if you do a pie chart with this library you would have pixels the size of your characters.

Regarding the first question, I still don't understand how to use the menu component.

Since I see that the menu component that I want is one that is always at the top where each menu item changes the content below it.

**Comment by mabe02** [comment]
You can definitely do bar charts quite easily by creating a custom component. When it comes to a multi-view application, it's up to you how you want to do it. Multi-window or multiple views inside of one window are both possible.

Menu component works like regular desktop application's main menu, it's always at the top of the window. Context (right-click style) menus are not available but there are several modal dialogs available for user input and selection.
