### ISSUE TITLE
Would like mouse CLICK outside of popup MENU (& others) to be treated same/similar to ESCAPE key.

### ISSUE THREAD

**Issue by ginkoblongata** [mabe02/lanterna#494]

**Comment by mabe02** [comment]
Yes, agreed. Should be possible to get the TextGUI implementation to detect a menu is open and then automatically close it.

**Comment by ginkoblongata** [comment]
Being addressed in pull request: https://github.com/mabe02/lanterna/pull/492

**Comment by ginkoblongata** [comment]
This functionality has been merged into release/3.1.
