### ISSUE TITLE
MultiWindowTextGUI, windows list ordering is coupled to moveToTop()

### ISSUE THREAD

**Issue by ginkoblongata** [mabe02/lanterna#497]
The windows list being coupled to the moveToTop() method has the effect of making the WindowManager layout tricker since it will not be getting the windows in the same order each time.

It seems that a z-ordering mechanism could be added to afford WindowManagers an easier time of things.

Comments?

**Comment by mabe02** [comment]
I'm not sure I follow, the z-ordering of the windows is the same as the order of the windows in the list that is passed to `WindowsManager#prepareWindows`

**Comment by ginkoblongata** [comment]
This functionality has been merged into release/3.1.
