### ISSUE TITLE
Unable to use SGR codes in TextBox

### ISSUE THREAD

**Issue by MaryWeeb** [mabe02/lanterna#506]
Using `"Sample \u001b[30mText"` as text inside a field shows up as `Sample [30mText`
While I am aware of TextGraphics, this is not a great solution when you want to use a scrollable buffer of colored text.

(EDIT: Replaced \u009b with \u001b, it differs based on the source used, but neither work)

**Comment by mabe02** [comment]
Unfortunately the text box components do not support colored text or any other escape codes. You'll have to create your own component to do that. I believe someone contributed (read-only) labels that can do this but no interactable components.
