### ISSUE TITLE
Making all windows to be of the same size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#52]
```
I tried setting the windowSizeOverride property to be the same TerminalSize for 
the windows, but when I use the GUIScreen to display these windows the first 
window is of one size and all other windows are of a different size. I am 
attaching a sample program that reproduces the issue I am observing.
```

Original issue reported on code.google.com by `m.vino...@gmail.com` on 28 Nov 2012 at 7:43

Attachments:
* [TestMain.java](https://storage.googleapis.com/google-code-attachments/lanterna/issue-52/comment-0/TestMain.java)

**Comment by mabe02** [comment]
With Lanterna 3, you can more easily extend the WindowManager and decide window sizes and placements yourself
