### ISSUE TITLE
Question: Possible to have a full-width, unpadded menu bar?

### ISSUE THREAD

**Issue by io7m** [mabe02/lanterna#522]
Hello!

Is it possible to, instead of having a menu that looks like this:

![menuOffset](https://user-images.githubusercontent.com/612494/98438896-532d2800-20e5-11eb-810d-01dd5cfcdfa0.png)

... have a menu that looks like this:

![menuOk](https://user-images.githubusercontent.com/612494/98438900-5c1df980-20e5-11eb-946d-e681883a1eef.png)

That is, the menu is the full width of the window and is rendered without the margin around the outside.

**Comment by io7m** [comment]
Here's a nice looking example from the abandoned Jexer library:

![Jexer](https://jexer.sourceforge.io/screenshots/demo_main.png)

**Comment by mabe02** [comment]
Yes, but not completely out of the box. You can assign a MenuBar to the TextGUI's background pane and then use a custom renderer to customize the look. If you create additional windows, they might take focus and prevent accessing the menu through normals means, so you might have to listen to unhandled keystrokes and manually trigger the menu.

**Comment by io7m** [comment]
Interesting. Thank you!
