### ISSUE TITLE
Missing Menu folder in Version 3.0.4

### ISSUE THREAD

**Issue by Anirataak** [mabe02/lanterna#525]
When I wanted to add the MenuBar to my panel I noticed that the MenuBar cannot be imported. So I checked the 3.0.4 version and noticed that in all other versions in the path src/main/java/com/googlecode/lanterna/gui2/ there is a folder Menu here and from this folder the MenuBar, Menu, MenuItem would be imported. In the 3.0.4 version this folder is not there, which means that you cannot create a MenuBar in this version.

I have now taken the 3.2.0-alpha1 version in my project, but lanterna-3.0.4 is the latest release.

![3 2 0-Alpha1](https://user-images.githubusercontent.com/69869489/99504190-77a7c080-297f-11eb-850a-d0cd655c6de3.PNG)
![3 0 4](https://user-images.githubusercontent.com/69869489/99504192-78405700-297f-11eb-83bf-5f775ba46508.PNG)

**Comment by mabe02** [comment]
Yes, Menu is a 3.1+ "feature"
