### ISSUE TITLE
Reduce CPU usage from useless redraws

### ISSUE THREAD

**Issue by guimeira** [mabe02/lanterna#531]
Hi!
First of all, thank you for this great library. I discovered it a couple of days ago and I love it!

I noticed that in some situations the library causes one of my cores to always stay at 100% usage. I noticed the event loop wasn't ever sleeping, the ``processEventsAndUpdate`` returned ``true`` all the time. which means the screen was being redrawn on every iteration, even though there were no changes to the interface. After some debugging, I tracked down two culprits in my specific use case.

**First:** The scrollbar of an ``ActionListBox``. When the ``AbstractListBox`` is drawn, if the number of items is greater than the component height, ``setScrollMaximum`` and ``setScrollPosition`` are always called, and they always invalidate the component, triggering a redraw:

https://github.com/mabe02/lanterna/blob/6920361cf5dff8bee9ac1dca9e8e76e15bca9d89/src/main/java/com/googlecode/lanterna/gui2/AbstractListBox.java#L471-L472

To fix it, inside ``setScrollMaximum`` and ``setScrollPosition``, I checked if the new value was different from the previous one and only then I invalidate the component.

**Second:** When the visibility of a component is changed using ``setVisible``, it invalidates the component. And the only way to clear the invalidation flag is by drawing it, but the component is never drawn because it's not visible, so the component stays invalid forever, which keeps triggering redraws.

https://github.com/mabe02/lanterna/blob/6920361cf5dff8bee9ac1dca9e8e76e15bca9d89/src/main/java/com/googlecode/lanterna/gui2/Panel.java#L268-L274

I tried to solve this in a few different ways but always ended up breaking something else (and that's the reason I'm opening an issue instead of sending a pull request). The only solution that worked for me was to create a ``validate`` method in the ``Component`` interface and modify the ``drawComponent`` method of ``Panel`` to call that method if the component is invisible, clearing the invalidation flag and preventing future useless redraws.
I'm not sure if that's the best solution, but since you know the library way better than I ever will, maybe you can come up with a better solution.

In any case, I'd be happy to provide a pull request if you want.

Once again, thanks for this great project!

**Comment by mabe02** [comment]
Good one, I suspect no one noticed this before. We should fix that.

**Comment by mabe02** [comment]
So oddly enough, I can't reproduce the issue with the ActionListBox. But the change you suggested makes sense so I will still do it.

**Comment by mabe02** [comment]
I've changed the Panel so that any invisible component that is marked as invalid will not make the Panel considered invalid. Also, when a component is made invisible, it will invalidate the parent instead of itself. See if this works, it's pushed to release/3.1 branch.

**Comment by guimeira** [comment]
I tried to come up with a small example that would reproduce the ActionListBox thing but also wasn't able to do it. Maybe it was only the hidden component that was causing the redraws. But I tested your fix in my application and it worked great, no more 100% CPU usage!
Thank you very much :smiley:
