### ISSUE TITLE
broken lines when using any Fontsize apart from 12

### ISSUE THREAD

**Issue by botboy0** [mabe02/lanterna#541]
I used a monospaced font to make sure it would work with the library. But because of some scaling issue that does not have to do 
with the Font I use (I checked that) the vertical Lines are broken.
![Bild_2021-04-19_020553](https://user-images.githubusercontent.com/10763071/115166489-c59e2d00-a0b3-11eb-8945-01181d0e9841.png)

My code:

`public class Main {
	public static void main(String[] args) throws IOException {
		
		// Setup terminal and screen layers
	
		  GraphicsEnvironment ge =  GraphicsEnvironment.getLocalGraphicsEnvironment();
		     try {
				ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("lib/font/fs.ttf")));
			} catch (FontFormatException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		     
		Font font = new Font("Fixedsys Excelsior 3.01", Font.PLAIN, 40);
		SwingTerminalFontConfiguration cfg= new SwingTerminalFontConfiguration(false, BoldMode.NOTHING, font);
		DefaultTerminalFactory factory = new DefaultTerminalFactory();
		factory.setInitialTerminalSize(new TerminalSize(20, 20));
		factory.setTerminalEmulatorFontConfiguration(cfg);
		Terminal terminal = factory.createTerminal();
		
		
		
	   
	
		Screen screen = new TerminalScreen(terminal);

		screen.startScreen();

		// Create window to hold the panel
		BasicWindow window = new BasicWindow();
		window.setHints(Arrays.asList(Window.Hint.FULL_SCREEN, Window.Hint.NO_DECORATIONS));
		window.setTheme(new SimpleTheme(new TextColor.RGB(255, 255, 255), TextColor.ANSI.BLACK));
	

		// Create gui and start gui
		MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
		
		Panel mainPanel = new Panel();
		mainPanel.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));

		Label label = new Label("Yeet");
		label.setTheme(new SimpleTheme(new TextColor.RGB(255, 255, 255), TextColor.ANSI.BLACK,SGR.FRAKTUR));
		label.addTo(mainPanel);

		window.setComponent(mainPanel.withBorder(Borders.singleLine("Main Panel")));
		gui.addWindowAndWait(window);
	}
}`

**Comment by avl42** [comment]
Have you tried using that Font with some standard Java multiline text widget and see if the lines touch there?

Can you debug your application with Eclipse or other IDE, and specifically step into the part where the Font is measured by Lanterna, and Lanterna determines the line spacing?

**Comment by botboy0** [comment]
Thank you for the quick reply, I am a bit unsure what is meant by a standard multiline text widget , are you referring to something like a content Panel/Action List Box made by Lanterna or a widget I would create in Swing not using Lanterna. 

I am using Eclipse and I will try to debug it into showing the measuring of line spacing in Lanterna, but I am a bit unsure how to go about that as well. I am unsure about the point where to debug and look into the variables specifically.

**Comment by botboy0** [comment]
Through editing the  Font I got to the point where it actually does work out to a point where I get continuous lines, but for some reason there is still places where there is a single 1-2 pixel gap in the lines.



![image](https://user-images.githubusercontent.com/10763071/115414923-c4294d80-a1f6-11eb-9818-c62692d00311.png)

**Comment by botboy0** [comment]
thanks this is no longer an issue
