### ISSUE TITLE
ProgressBar not updating visual progress

### ISSUE THREAD

**Issue by botboy0** [mabe02/lanterna#545]
Hello, I am currently trying to make a progressbar but whenever I set its value it doesnt update its visual progress apart from changing the text shown on screen
![image](https://user-images.githubusercontent.com/10763071/117497390-b86cb380-af78-11eb-8ce9-19a0ba43ac90.png)
![image](https://user-images.githubusercontent.com/10763071/117497457-cde1dd80-af78-11eb-8a60-e773e3b6ecf8.png)

**Comment by Chris-GW** [comment]
The problem lies in your used SimpleTheme at line 92, which does not specify any colors for the ProgressBar. This causes the filled part and missing part to both be drawn in black on a black background. 
You should set the theme definition for ProgressBar or use some build in themes.

```java
SimpleTheme theme = new SimpleTheme(new RGB(255, 255, 255), TextColor.ANSI.BLACK);
// customize theme Definition for ProgressBar
Definition definition = theme.getDefinition(ProgressBar.class);
definition.setActive(TextColor.ANSI.WHITE, TextColor.ANSI.BLUE); // define ProgressBar filled color as BLUE
window.setTheme(theme);

// or use some other registered dark themes
window.setTheme(LanternaThemes.getRegisteredTheme("blaster"))
```

**Comment by mabe02** [comment]
Thanks @Chris-GW, I'll close this. @botboy0 please re-open if needed.
