### ISSUE TITLE
Merge donated paging table code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#55]
```
A table implementation that can do multiple pages has been kindly donated, 
let's merge it in!
```

Original issue reported on code.google.com by `mab...@gmail.com` on 9 Dec 2012 at 1:11

Attachments:
* [demo.simpleDataEntry.v2.zip](https://storage.googleapis.com/google-code-attachments/lanterna/issue-55/comment-0/demo.simpleDataEntry.v2.zip)

**Comment by mabe02** [comment]
I think we did this...?
