### ISSUE TITLE
ALT modifier not evaluated on TERM=linux

### ISSUE THREAD

**Issue by francescomuia** [mabe02/lanterna#551]
In the unemulated terminal, TERM=linux, the modifier ALT or SHIFT is not recognized. This prevent to use scrolling.
I entered a few lines of logging and got the following output.

`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: currentMatching [^[]`
`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: matching Matching{partialMatch=true, fullMatch=KeyStroke{keytype=Escape}}`
`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: currentMatching [^[, []`
`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: matching Matching{partialMatch=true, fullMatch=KeyStroke{keytype=Character, character='[', modifiers=[alt]}}`
`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: currentMatching [^[, [, B]`
`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: matching Matching{partialMatch=false, fullMatch=KeyStroke{keytype=ArrowDown}}`
`Oct 05, 2021 8:58:21 AM com.googlecode.lanterna.input.InputDecoder getNextCharacter`
`INFO: AFTER WHILE KeyStroke{keytype=ArrowDown}`

**Comment by avl42** [comment]
Well, unfortunately the linux konsole just doesn't reveal this information
about modifiers.

E.g., whatever modifiers you press with the ArrowDown key, you only get an
Esc [ B sequence.

The only solution here would be to provide a patch for the linux kernel to
send different sequences
for modified keys in the konsole mode.

Btw., much of lanterna's input-decoding was contributed by me.   I kind of
know what I'm talking about ;-)

**Comment by mabe02** [comment]
Yeah, pretty much what @avl42 says :)
