### ISSUE TITLE
Terminal window resize and resizing disabling

### ISSUE THREAD

**Issue by Krzyshio** [mabe02/lanterna#568]
Is there any possibility to resize the terminal from the code layer at runtime?

On the other hand, is it possible to set the terminal as not resizable by the user?

**Comment by avl42** [comment]
Assuming you're talking about AWT- or SwingTerminals.
Then, if you need control over the Window (in Swing's sense, not
Lanterna's),
you could create a SwingTerminal and wrap it in a Swing Frame that you then
can control by means of Swing:  allow/disallow resizing by user,  resize it
from
Java code...

**Comment by mabe02** [comment]
Yeah, I don't think there's any way to resize xterm or other emulators by control codes. That seems both crazy and potentially dangerous. But if you use the Java terminal emulator that comes with Lanterna, you can resize it as @avl42 describes.
