### ISSUE TITLE
Text from previously shown panel stays on screen

### ISSUE THREAD

**Issue by Thastertyn** [mabe02/lanterna#571]
On linux (not sure if anywhere else), in the integrated vscode terminal, kitty and konsole, when i have a window and add and remove panels from it, the text from previous panels may stay on screen. 
This is what it might look like (anything not colored should not even be there)
![2023-05-05_08:16:48](https://user-images.githubusercontent.com/60262101/236394189-0b0c3b8c-47ed-4776-a694-b20e2ec17992.png)
Not sure if it is because of how my code works. I create a screen, window and a panel the same way one of the tutorials does
```
// Setup terminal and screen layers
terminal = new DefaultTerminalFactory().createTerminal();

screen = new TerminalScreen(terminal);
screen.startScreen();

// Create window to hold the panel
window = new BasicWindow();
window.setHints(Arrays.asList(Window.Hint.CENTERED));

// Create gui and start gui
textGUI = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLACK_BRIGHT));

// Create panel to hold components
final Panel mainPanel = new Panel();
mainPanel.setLayoutManager(new LinearLayout(Direction.VERTICAL));

window.setComponent(mainPanel);

Panel content = new Panel();
mainPanel.addComponent(content.withBorder(Borders.singleLine("MyApp")));

window.addWindowListener(new WindowSwitchListener(content, textGUI));
```
and add WindowSwitchListener which just listens for tab press to move between the panels
```
@Override
public void onInput(Window basePane, KeyStroke keyStroke, AtomicBoolean deliverEvent) {
	KeyType type = keyStroke.getKeyType();

	switch(type)
	{
		case Tab:
			next();
			break;
		case ReverseTab:
			previous();
			break;
		default:
			break;
	}
}
```
and next/previous simply does this
```
content.removeAllComponents();
content.addComponent(panels[current]);
```
I use a table as well, but that seems to be unaffected, but could be I'm just lucky with that

**Comment by Thastertyn** [comment]
Nevermind, the cause was some emoji in text. Terminal and emoji don't go together very well.

**Comment by mabe02** [comment]
There should be some support for detecting wide characters, but probably not emoji

**Comment by mabe02** [comment]
Seems like emoji is generally assumed to be two columns; let's update that then
