### ISSUE TITLE
update jacoco-maven-plugin

### ISSUE THREAD

**Issue by weberjn** [mabe02/lanterna#577]
Please update jacoco-maven-plugin to 0.8.10
With the current 0.8.5 and Java 17 there is an error

    [INFO] Running com.googlecode.lanterna.issue.Issue452Test
    java.lang.instrument.IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo.

**Comment by mabe02** [comment]
Done
