### ISSUE TITLE
VirtualScreen - scrolling page-wise

### ISSUE THREAD

**Issue by weberjn** [mabe02/lanterna#578]
Besides scrolling by line using ALT+ arrow keys VirtualScreen should also support scrolling by page using ALT + Page up/down, and down by pressing space as in a browser.

It should be configurable to use ALT or CTRL.

Also, the "Terminal too small, use ALT+arrows to scroll" help text could be on the horizontal scroll bar to save some space.

**Comment by mabe02** [comment]
Yeah, that makes sense
