### ISSUE TITLE
wrong javadoc or wrong visibility of a method ?

### ISSUE THREAD

**Issue by avl42** [mabe02/lanterna#592]
https://github.com/mabe02/lanterna/blob/54f5b4ca6b33eaa41cc666f5d7bce8f08ddc132a/src/main/java/com/googlecode/lanterna/terminal/ansi/UnixTerminal.java#L29

Here it suggests to override `getSTTYCommand()`, but that method is **private** in UnixLikeTTYTerminal.
Either it should suggest overriding `runSTTYCommand()`, or `getSTTYCommand()` should be made "protected".
I'd prefer the latter of the two.

**Comment by mabe02** [comment]
Yeah, it's outdated after some of the refactorings

**Comment by mabe02** [comment]
Made it protected, seems most straight-forward

**Comment by mabe02** [comment]
Commit here: https://github.com/mabe02/lanterna/commit/2f4e3b7f37d8645ef001c0dcc05d7ef2ad749044

For some reason Github didn't auto-detect it
