### ISSUE TITLE
Translation resource package problem

### ISSUE THREAD

**Issue by wsyong111** [mabe02/lanterna#606]
The properties files of zh-CN and zh-TW should use zh_CN instead of zh-CN
![image](https://github.com/mabe02/lanterna/assets/94914969/13c8095a-245d-4189-a80d-eb6e01039cc8)
change to
![image](https://github.com/mabe02/lanterna/assets/94914969/64e58e6d-d2f4-48eb-a64d-34b3bf9ef21e)

**Comment by avl42** [comment]
Could you prepare a "PR" ?

Martin (owner of this project) seems to be quite busy lately, so next time he looks around
it would accelerate the thing if he then only had to accept the PR.

**Comment by mabe02** [comment]
I've pushed a fix to 3.0+
