### ISSUE TITLE
Super slow on AIX (draws 1 line per second)

### ISSUE THREAD

**Issue by bmarwell** [mabe02/lanterna#607]
Hi,

on AIX (ssh'd into AIX using iTerm 2), the drawing is super slow.
1 Line at a time is being drawn.

Here is an example from a mockup which prints processes (unfinished, only shows pid and user so far).

That was about 8 seconds after starting the process.
This does not happen on Linux or Mac OS X. It is a little slow on AIX, too, but not that slow.
Using text Graphics. Haven't tried "normal" text yet.

![Screenshot 2024-06-24 at 09 49 37](https://github.com/mabe02/lanterna/assets/1413391/48e35c27-5d0c-42ef-90e6-44146ffb4a5e)

**Comment by bmarwell** [comment]
The reason is getting the terminal size. Calling it repeatedly will be extremely slow.

**Comment by mabe02** [comment]
Was that the library doing it or you?
