### ISSUE TITLE
Question about number of columns and lines that fit without scroll bars?

### ISSUE THREAD

**Issue by javafanboy** [mabe02/lanterna#614]
I would like to know how many columns and lines that fit within a multi line text box without scroll bars - is this possible?

**Comment by mabe02** [comment]
You can decide how big you want it to be

**Comment by javafanboy** [comment]
The dimensions are given by screen size and layout manager and I want to
make the width of the data to fit without scroll bars (by deciding what
detail data to include etc). I suppose I by trial and error can find out
how many columns to deduct from the set width of the text box etc but was
curious if some more elegant way existed ....

**Comment by javafanboy** [comment]
Seems there is no way to determine this other than trial and error. Luckily this is quite easy when we are talking whole character positions.
