### ISSUE TITLE
Creating Window that fill whole screen?

### ISSUE THREAD

**Issue by javafanboy** [mabe02/lanterna#615]
Is it possible to calculate how large I can make a Window to fill the whole horisontal width of my terminal or do I need to do "trial and error"?

**Comment by mabe02** [comment]
If you want a full-screen window that fills both horizontal and vertical space, you can set the background pane of the TextGUI to a regular panel and use that instead of a window to add components to. Check FullScreenTextGUITest sample class.

**Comment by javafanboy** [comment]
Thanbks - will hape a look at that option!
