### ISSUE TITLE
Any sugestions for creating a menu with check boxes?

### ISSUE THREAD

**Issue by javafanboy** [mabe02/lanterna#617]
I would have liked to create a menu with check boxes but as this is not supported directly I am looking for creative tips on how I could create something similar? I would have liked to use this to let the user select what columns to include in a text box...
I have considered dynamically replacing menu texts that includes an "X" when "toggled" or something but cant really get it to work.
Would it be possible to subclass MenuItem in some creative way??
Anybody that has managed to build something similar?

**Comment by mabe02** [comment]
The menu component doesn't do radio or check boxes functionality built in. You can extend MenuItem and pass in a custom implementation that returns a special label depending on the checked status. If you need special styling you can also override DefaultMenuItemRenderer and make your own.

**Comment by javafanboy** [comment]
Thanks will explore these options!
