### ISSUE TITLE
ResourceBundle.Control is not supported in named modules

### ISSUE THREAD

**Issue by Peter-Maeding** [mabe02/lanterna#620]
I have a lanterna app that uses modules. After setting a default locale other than English I noticed that the app still shows the english values (e.g. `LocalizedString.Cancel.toString()` will always return `"Cancel"`). This works as expected when used in an app without modules.

After some debugging I found that lanterna fails to load its resource bundles in BundleLocator on line 73: 
```java 
return ResourceBundle.getBundle(bundleName, locale, loader, new UTF8Control());
```
This code throws `java.lang.UnsupportedOperationException: ResourceBundle.Control not supported in named modules`

The javadoc of ResourceBundle.Control states the following about this problem:

> ResourceBundle.Control is designed for an application deployedin an unnamed module, for example to support resource bundles innon-standard formats or package localized resources in a non-traditional convention. ResourceBundleProvider is the replacement for ResourceBundle.Control when migrating to modules. UnsupportedOperationException will be thrown when a factory method that takes the ResourceBundle.Control parameter is called.
[...]
ResourceBundle.Control is not supported in named modules. If the ResourceBundle.getBundle method with a ResourceBundle.Control is called in a named module, the method will throw an UnsupportedOperationException. Any service providers of ResourceBundleControlProvider are ignored in named modules.

**Comment by avl42** [comment]
Thanks a lot for the analysis and reporting.

I'm not sure how important this "Control"-thing is for lanterna.  Maybe it
can just be removed without
any replacement.

My fear is that the replacement mentioned is only available for newer Java
versions than what are supported by Lanterna.

Do you feel able to create a PR for it - that would still work with e.g.
Java8 as well?

Is using named modules essential for your application?

**Comment by avl42** [comment]
Would it be a solution to put the current logic (with Control) into a
try-block and retry the same getBundle without Control in the catch-handler
for java.lang.UnsupportedOperationException ?

Peter Mäding ***@***.***> schrieb am Di., 5. Nov. 2024, 21:11:

**Comment by Peter-Maeding** [comment]
I honestly have no idea why I didn't think of that. That sounds like the most obvious and simplest solution. I'll try that an make a PR when I find the time.

**Comment by mabe02** [comment]
Thank you!
