### ISSUE TITLE
Is it possible to print a char[][]?

### ISSUE THREAD

**Issue by jabrena** [mabe02/lanterna#622]
I am thinking to explore Laterna to make visualization from AOC problems and I am not sure if it is possible to draw a char[][] with this library.

Does exist any example for it?

Many thanks in advance

Juan Antonio

**Comment by avl42** [comment]
unless I'm understanding it wrongly, this is a general Java question rather
than an issue with lanterna.

The problem with char[][] is, that it is an entirely uncommon way of
representing textual data, so your best approach would be to convert this
into a List of String objects, and then draw/write that.

Juan Antonio Breña Moral ***@***.***> schrieb am So., 15.
Dez. 2024, 22:56:

**Comment by mabe02** [comment]
Ultimately, it's just printing characters to a terminal like System.out.println. So if you can get your text printed using println, then it will probably work here too. Like @avl42 is saying, you'll need to decide how to print the 2d array (one row per sub-array? sub-arrays concatenated?) and likely transform it into a string or strings first.
