### ISSUE TITLE
Character fill is not configurable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#66]
```
For a text terminal with a minimal UI, a common styling of text input field is 
by periods or underlines rather than borders. 

TextBox and TextArea hard code the space character when calling fillArea. I 
tested using a period instead and this works.

I'm not sure what is the best way to allow this to be configurable. In my 
opinion it should be part of a theme definition, which TextGraphics uses to get 
the fill character. I made the changes and attached a patch for this, 
introducing an optional DefinitionBuilder. Not a minimal change, but hope it 
helps.
```

Original issue reported on code.google.com by `sivan.mo...@gmail.com` on 30 Jan 2013 at 12:39

Attachments:
* [Configurable_fill_character.patch](https://storage.googleapis.com/google-code-attachments/lanterna/issue-66/comment-0/Configurable_fill_character.patch)
* [Screen Shot 2013-01-29 at 4.35.54 PM.png](https://storage.googleapis.com/google-code-attachments/lanterna/issue-66/comment-0/Screen Shot 2013-01-29 at 4.35.54 PM.png)

**Comment by mabe02** [comment]
Closing; I think this is fixed in Lanterna 3
